dataset:
  name: PGDBj
  description: The PGDBj database is for integrated searches of plant genome-related information (genome analysis, DNA markers, QTLs, Orthologs, etc.) and plant resource information provided in Japan. Basic information is also provided about plants that have been subjected to genome analysis.
