- Group <http://pgdbj.jp/ortholog-db/resource/33090_cluster_1_57_0/33090:0>:
  - a:
    - orth:OrthologGroup
    - orth:ParalogGroup
  - orth:member*:
    - member: [ Group, Protein ]
  - orth:taxon:
    - taxon: TaxonomyId
  - dct:description:
    - description: "photosystem II protein T (chloroplast)"
  - dct:identifier:
    - identifier: "33090:0"
  - void:inDataset:
    - in_dataset: <http://pgdbj.jp/ortholog-db/resource/33090_clusters_1_57_0>
  - rdfs:label+:
    - group_label: "33090:0"
  - foaf:page+:
    - webpage: <http://pgdbj.jp/od/1.57.0/PORT33090/33090/TOC33090.html>
- Protein <http://www.ncbi.nlm.nih.gov/protein/NP_001030613.1>:
  - a: orth:Protein
  - dct:description:
    - descripton: "uncharacterized protein [Arabidopsis thaliana]"
  - rdfs:seeAlso:
    - protid: protid:NP_001030613.1
- TaxonomyId <http://identifiers.org/taxonomy/33090>:
  - a: orth:Taxon
  - up:organism:
    - uniprot_taxonomy: <http://purl.uniprot.org/taxonomy/33090>

- Class orth:Dataset:
  - a: owl:Class
  - rdfs:label:
    - class_label: "Dataset"
  - rdfs:subClassOf*:
    - subclass_of: SubClass
  - owl:equivalentClass*:
    - equivalent_class_cluster: ogo:Cluster
    - equivalent_class_protein: ogo:Protein
    - equivalent_class_gene: ogo:Gene
  - rdfs:isDefinedBy:
    - class_defined_by: <http://purl.jp/bio/11/orth>
- SubClass rdfs:subClassOf:
  - a:
    - owl:Class
    - owl:Restriction
  - rdfs:subClassOf*:
    - resource: orth:Resource
    - dataset_void: void:Dataset
    - dataset_dctype: dctype:Dataset
    - collection_dctype: dctype:Collection
    - collection_skos: skos:Collection
    - ortholog_group: orth:OrthologGroup
    - paralog_group: orth:ParalogGroup
    - homolog_group: orth:HomologGroup
    - sequence_unit: orth:SequenceUnit
    - obo: obo:SO_0000704
    - organism: orth:Organism
  - owl:onProperty*:
    - on_property_organism: orth:organism
    - on_property_indataset: orth:inDataset
    - on_property_member: orth:member
  - owl:allValuesFrom*:
    - allvalues_from_organism: orth:Organism
    - allvalues_from_dataset: orth:Dataset
    - allvalues_from_unionof: UnionOf
- UnionOf owl:unionOf:
  - a: owl:Class
  - owl:unionOf*:
    - union_of_group: orth:Group
    - union_of_sequenceunit: orth:SequenceUnit
- Relation orth:relation:
  - a:
    - owl:ObjectProperty
    - owl:SymmetricProperty
  - rdfs:label:
    - relation_label: "relation"
  - rdfs:comment*:
    - comment: "This property is intended to be used for specifying URI representing NCBI taxonomy ID."
  - rdfs:domain*:
    - relation_domain_resource: orth:Resource
    - relation_domain_group: orth:Group
    - relation_domain_sequenceunit: orth:SequenceUnit
  - rdfs:range*:
    - relation_range_resource: orth:Resource
    - relation_range_dataset: orth:Dataset
    - relation_range_unionof: UnionOf
    - relation_range_sequenceunit: orth:SequenceUnit
    - relation_range_gene: orth:Gene
    - relation_range_protein: orth:Protein
    - relation_range_transcript: orth:Transcript
    - relation_range_organism: orth:Organism
    - relation_range_taxon: orth:Taxon
  - rdfs:subPropertyOf*:
    - subpropertyof_dct_relation: dct:relation
    - subpropertyof_orth_relation: orth:relation
    - subpropertyof_groupmembership_relation: orth:groupMembershipRelation
    - subpropertyof_void_indataset: void:inDataset
    - subpropertyof_dct_ispartof: dct:isPartOf
    - subpropertyof_rdfs_member: rdfs:member
    - subpropertyof_skos_member: skos:member
    - subpropertyof_pairwise_relation: orth:pairwiseRelation
    - subpropertyof_homolog: orth:homolog
    - subpropertyof_reference: orth:reference
    - subpropertyof_crossreference: orth:crossReference
    - subpropertyof_organism: orth:organism
  - owl:equivalentProperty*:
    - equivalent_property: ogo:hasOrthologous
  - rdfs:isDefinedBy:
    - relation_defined_by: <http://purl.jp/bio/11/orth>
- DataType orth:value:
  - a: owl:DatatypeProperty
  - rdfs:label:
    - datatype_label: "value"
  - rdfs:domain*:
    - datatype_domain_resource: orth:Resource
    - datatype_domain_group: orth:Group
    - datatype_domain_unionof: UnionOf
  - rdfs:range:
    - datatype_range: rdfs:Literal
  - rdfs:subPropertyOf*:
    - subpropertyof_rdfvalue: rdf:value
    - subpropertyof_orthvalue: orth:value
    - subpropertyof_groupvalue: orth:groupValue
  - rdfs:isDefinedBy:
    - datatype_defined_by: <http://purl.jp/bio/11/orth>