rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
xsd: <http://www.w3.org/2001/XMLSchema#>
void: <http://rdfs.org/ns/void#>
pav: <http://purl.org/pav/>
foaf: <http://xmlns.com/foaf/0.1/>
orth: <http://purl.jp/bio/11/orth#>
up: <http://purl.uniprot.org/core/>
protid: <http://identifiers.org/ncbiprotein/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
owl: <http://www.w3.org/2002/07/owl#>
dctype: <http://purl.org/dc/dcmitype/>
skos: <http://www.w3.org/2004/02/skos/core#>
ogo: <http://miuras.inf.um.es/ontologies/OGO.owl#>
obo: <http://purl.obolibrary.org/obo/>