# Input file
#   https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt
- HGNC:
  - source("hgnc_complete_set.txt")
  - subject:
    - col("hgnc_id")
    - downcase
  - objects:
    - gene_id: col("symbol")
    - hgnc_id:
      - col("hgnc_id")
      - delete(/^HGNC:/)
    - description: col("name")
    - location: col("location")

- UniProt:
  - source("hgnc_complete_set.txt")
  - subject:
    - col("uniprot_ids")
    - split("|")
    - prepend("http://identifiers.org/uniprot/")
  - objects:
    - uniprot_id:
      - col("uniprot_ids")
      - split("|")

- PubMed:
  - source("hgnc_complete_set.txt")
  - subject:
    - col("pubmed_id")
    - split("|")
    - prepend("http://identifiers.org/pubmed/")
  - objects:
    - pubmed_id:
      - col("pubmed_id")
      - split("|")
