- HGNC hgnc:11998:
  - a:
    - obo:SO_0000704
    - m2r:Gene
  - rdfs:label:
    - gene_id: "TP53"
  - dct:identifier:
    - hgnc_id: "11998"
  - dct:description:
    - description: "tumor protein p53"
  - obo:so_part_of*:
    - location: "17p13.1"
  - rdfs:seeAlso*:
    - see_also: [ NCBIGene, Ensembl, ENA, INSDC, RefSeq, CCDS, UniProt, MGI, RGD, LRG, OMIM, MiRBase, Orphanet, EC ]
  - dct:references*:
    - reference: PubMed
  - skos:altLabel*:
    - alt_label: "p53"

- NCBIGene <http://identifiers.org/ncbigene/7157>:
  - a: idt:ncbigene
  - dct:identifier:
    - ncbigene_id: "7157"

- Ensembl <http://identifiers.org/ensembl/ENSG00000141510>:
  - a: idt:ensembl
  - dct:identifier:
    - ensembl_id: "ENSG00000141510"

- ENA <http://identifiers.org/ena.embl/AF307851>:
  - a: idt:ena.embl
  - dct:identifier:
    - ena_id: "AF307851"

- INSDC <http://identifiers.org/insdc/AF307851>:
  - a: idt:insdc
  - dct:identifier:
    - insdc_id: "AF307851"

- RefSeq <http://identifiers.org/refseq/NM_000546>:
  - a: idt:refseq
  - dct:identifier:
    - refseq_id: "NM_000546"

- CCDS <http://identifiers.org/ccds/CCDS45605> :
  - a: idt:ccds
  - dct:identifier:
    - ccds_id: "CCDS45605"

- UniProt <http://identifiers.org/uniprot/P04637>:
  - a: idt:uniprot
  - dct:identifier:
    - uniprot_id: "P04637"

- PubMed <http://identifiers.org/pubmed/20498374>:
  - a: idt:pubmed
  - dct:identifier:
    - pubmed_id: "20498374"

- MGI <http://identifiers.org/mgi/MGI:98834>:
  - a: idt:mgi
  - dct:identifier:
    - mgi_id: "98834"

- RGD <http://identifiers.org/rgd/3889>:
  - a: idt:rgd
  - dct:identifier:
    - rgd_id: "3889"

- LRG <http://identifiers.org/lrg/LRG_321>:
  - a: idt:lrg
  - dct:identifier:
    - lrg_id: "LRG_321"

- OMIM <http://identifiers.org/omim/191170>:
  - a: idt:omim
  - dct:identifier:
    - omim_id: 191170

- Orphanet <http://identifiers.org/orphanet/120204>:
  - a: idt:orphanet
  - dct:identifier:
    - orphanet_id: "120204"

- MiRBase <http://identifiers.org/mirbase/MI0000651>:
  - a: idt:mirbase
  - dct:identifier:
    - mirbase_id: "MI0000651"

- EC <http://identifiers.org/ec-code/2.3.2.27>:
  - a: idt:ec-code
  - dct:identifier:
    - ec_id: "2.3.2.27"
