sparql:
  description: Obrain gene records from the HGNC data
  variables: [gene_id, hgnc_id, description, location, ncbigene_id, ensembl_id, uniprot_id, pubmed_id]

stanza_sparql:
  description: Obtain a gene record from the HGNC data
  parameters:
    gene_id: TP53
  variables: [gene_id, description, see_also, reference, alt_label]

togoid:
  description: Extract link information from the HGNC data
  variables: [gene_id, hgnc_id, ncbigene_id, ensembl_id, ena_id, insdc_id, refseq_id, ccds_id, uniprot_id, pubmed_id, mgi_id, rgd_id, lrg_id, omim_id, orphanet_id, mirbase_id, ec_id]
