hgnc:
  output_dir: "stanza" # /path/to/output/dir
  label: "HGNC record"
  definition: "Stanza of a HGNC gene record"
  sparql: stanza_sparql  # defined in sparql.yaml
  parameters:
    gene:
      example: "TP53"
      description: HGNC gene symbol
      required: true
