dataset:
  name: HINT
  description: HINT (High-quality INTeractomes) is a database of high-quality protein-protein interactions. The interactions are collected from 8 interactome resources (BioGRID, MINT, iRefWeb, DIP, IntAct, HPRD, MIPS and the PDB), and manually varidated.
