rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
hco: <http://biohackathon.org/resource/hco/>
ncgm: <http://purl.jp/bio/ncgm/>
sio: <http://semanticscience.org/resource/>
med2rdf: <http://med2rdf.org/ontology/med2rdf#>
gvo: <http://genome-variation.org/resource/gvo#>
