rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
ncbigene: <http://identifiers.org/ncbigene/>
ncbiprotein: <http://identifiers.org/ncbiprotein/>
hop: <http://purl.org/net/orthordf/hOP/ontology#>
orth: <http://purl.org/net/orth#>
group: <http://purl.org/net/orthordf/hOP/group/>
organism: <http://purl.org/net/orthordf/hOP/organism/>
