title: Cellosaurus RDF
website: https://www.cellosaurus.org/
description: Cellosaurus is a knowledge resource on cell lines. It attempts to describe all cell lines used in biomedical research.
tags: [ Cell, Ontology/Terminology/Nomenclature, Bioresource, Health/Disease ]
provider: The Swiss Institute of Bioinformatics
creators:
  - name: The Swiss Institute of Bioinformatics
version: Release 56
issued: 2026-06-29
licenses:
  - Creative Commons Attribution 4.0 International (CC BY 4.0) License
