dc: <http://purl.org/dc/terms/>
void: <http://rdfs.org/ns/void#>
xsd: <http://www.w3.org/2001/XMLSchema#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
pav: <http://purl.org/pav/>
dcat: <http://www.w3.org/ns/dcat#>
foaf: <http://xmlns.com/foaf/0.1/>
owl: <http://www.w3.org/2002/07/owl#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
skos: <http://www.w3.org/2004/02/skos/core#>
weso-s: <http://weso.es/shapes/>
cello: <https://purl.expasy.org/cellosaurus/rdf/ontology/>
cvcl: <https://purl.expasy.org/cellosaurus/rdf/cvcl/>
xref: <https://purl.expasy.org/cellosaurus/rdf/xref/>
pub: <https://purl.expasy.org/cellosaurus/rdf/pub/>
orga: <https://purl.expasy.org/cellosaurus/rdf/orga/>
db: <https://purl.expasy.org/cellosaurus/rdf/db/>
fabio: <http://purl.org/spar/fabio/>
up: <http://purl.uniprot.org/core/>
bibo: <http://purl.org/ontology/bibo/>
widoco: <https://w3id.org/widoco/vocab#>
vann: <http://purl.org/vocab/vann/>
oa: <http://www.w3.org/ns/oa#>
wdt: <http://www.wikidata.org/prop/direct/>
wd: <http://www.wikidata.org/entity/>
sh: <http://www.w3.org/ns/shacl#>
schema: <https://schema.org/>
help: <https://api.cellosaurus.org/>
pubmed: <https://www.ncbi.nlm.nih.gov/pubmed/>
BAO: <http://www.bioassayontology.org/bao#BAO_>
BTO: <http://purl.obolibrary.org/obo/BTO_>
CLO: <http://purl.obolibrary.org/obo/CLO_>
NCIt: <http://purl.obolibrary.org/obo/NCIT_>
OBI: <http://purl.obolibrary.org/obo/OBI_>
OMIT: <http://purl.obolibrary.org/obo/OMIT_>
FBcv: <http://purl.obolibrary.org/obo/FBcv_>
GENO: <http://purl.obolibrary.org/obo/GENO_>
CARO: <http://purl.obolibrary.org/obo/CARO_>
CL: <http://purl.obolibrary.org/obo/CL_>
CHEBI: <http://purl.obolibrary.org/obo/CHEBI_>
ORDO: <http://www.orpha.net/ORDO/Orphanet_>
IAO: <http://purl.obolibrary.org/obo/IAO_>
EDAM: <http://edamontology.org/>
prism: <http://prismstandard.org/namespaces/basic/2.0/>
BFO: <http://purl.obolibrary.org/obo/BFO_>
OLS: <http://purl.obolibrary.org/obo/>
