title: GWAS catalog 
website: https://www.ebi.ac.uk/gwas/
description: 
tags: []
provider: European Bioinformatics Institute
creators:
  - name: European Bioinformatics Institute
rdf_creators:
  - name: European Bioinformatics Institute
version: 
issued: 
licenses:
  - Summary statistics are available under CC0 terms unless otherwise indicated
  - Other GWAS Catalog data can be used under the standard Terms of Use for EBI services which can be found at http://www.ebi.ac.uk/about/terms-of-use.
  - The code is available under the Apache version 2.0 license.
