endpoint:
  - https://rdfportal.org/primary/sparql
  - graph:
    - https://pubcasefinder.dbcls.jp/rdf
another_endpoint:
  - https://pubcasefinder-rdf.dbcls.jp/sparql
  - graph:
    - https://pubcasefinder.dbcls.jp/rdf
