use anyhow::{Context, Result};
use regex::Regex;
use std::collections::{HashMap, HashSet};

use crate::prefix::{expand_curie, is_uri_like};
use crate::turtle_oxrdf::is_valid_iri;
use crate::types::*;

/// Sentinel value used to mark skipped positions in a Multiple pipeline value.
/// Preserves positional alignment across split columns.
const SKIP_SENTINEL: &str = "\0__SKIP__\0";

// ─── blank node ID generation ─────────────────────────────────────

use std::cell::Cell;
thread_local! {
    static BNODE_COUNTER: Cell<u64> = Cell::new(0);
}

fn next_bnode_id() -> String {
    BNODE_COUNTER.with(|c| {
        let id = c.get();
        c.set(id + 1);
        format!("_:b{}", id)
    })
}

/// Process all rows and generate triples.
/// Returns (triples, convert_subjects) where convert_subjects is the set of
/// subject URIs generated by convert rules (as opposed to auto-generated ones).
///
/// `source_path` and `start_row` are used in warning messages.
/// `start_row` is the 1-based TSV row number of the FIRST row in `rows`
/// (header is row 1, so the first data row is row 2).
pub fn process_rows(
    rows: &[HashMap<String, String>],
    convert: &ConvertConfig,
    model: &Model,
    prefixes: &PrefixMap,
    source_path: &str,
    start_row: usize,
) -> Result<(Vec<Triple>, HashSet<String>)> {
    let mut all_triples = Vec::new();
    let mut all_convert_subjects = HashSet::new();

    for (i, row) in rows.iter().enumerate() {
        let row_num = start_row + i;
        let (triples, subjects) = process_single_row(row, convert, model, prefixes, source_path, row_num)
            .with_context(|| format!("Error processing row {}", row_num))?;
        all_triples.extend(triples);
        all_convert_subjects.extend(subjects);
    }

    Ok((all_triples, all_convert_subjects))
}

/// Process a single TSV row through all subject rules
fn process_single_row(
    row: &HashMap<String, String>,
    convert: &ConvertConfig,
    model: &Model,
    prefixes: &PrefixMap,
    source_path: &str,
    row_num: usize,
) -> Result<(Vec<Triple>, HashSet<String>)> {
    // Global variables shared across all subject rules within one row
    let mut global_vars = Variables::new();
    let mut all_triples = Vec::new();
    let mut convert_subjects = HashSet::new();

    // subject_name -> list of generated subject URIs
    let mut generated_subjects: HashMap<String, Vec<String>> = HashMap::new();

    // ── Phase 1: compute all subject URIs and variables ──
    for rule in &convert.subject_rules {
        let mut local_vars = global_vars.clone();

        for var_def in &rule.pre_variables {
            let val = exec_pipeline(&var_def.pipeline, "", row, &local_vars, prefixes)?;
            if let PipelineValue::Single(v) = &val {
                local_vars.insert(var_def.name.clone(), v.clone());
            }
        }

        for var_def in &rule.subject_pipeline.variables {
            let val = exec_pipeline(&var_def.pipeline, "", row, &local_vars, prefixes)?;
            if let PipelineValue::Single(v) = &val {
                local_vars.insert(var_def.name.clone(), v.clone());
            }
        }

        // Generate subject URIs
        let subject_uris = exec_pipeline(
            &rule.subject_pipeline.steps, "", row, &local_vars, prefixes,
        )?;
        let uris = pipeline_to_vec(&subject_uris);
        // Track as convert-generated subjects
        for u in &uris {
            convert_subjects.insert(u.clone());
        }
        generated_subjects.insert(rule.name.clone(), uris);

        // Propagate variables to global scope
        for (k, v) in &local_vars {
            global_vars.insert(k.clone(), v.clone());
        }
    }

    // ── Phase 2: generate triples ──
    for rule in &convert.subject_rules {
        let mut local_vars = global_vars.clone();

        // Re-evaluate pre-variables (they might depend on other rules' vars now)
        for var_def in &rule.pre_variables {
            let val = exec_pipeline(&var_def.pipeline, "", row, &local_vars, prefixes)?;
            if let PipelineValue::Single(v) = &val {
                local_vars.insert(var_def.name.clone(), v.clone());
            }
        }
        for var_def in &rule.subject_pipeline.variables {
            let val = exec_pipeline(&var_def.pipeline, "", row, &local_vars, prefixes)?;
            if let PipelineValue::Single(v) = &val {
                local_vars.insert(var_def.name.clone(), v.clone());
            }
        }

        // Drop empty subject URIs: with the prepend/append emptiness fix, a
        // NULL subject column yields "" rather than a bare prefix, and an
        // empty-subject triple is invalid output.
        let subject_uris: Vec<String> = generated_subjects
            .get(&rule.name)
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .filter(|u| !u.is_empty())
            .collect();
        if subject_uris.is_empty() {
            continue;
        }

        let model_subject = model.find_subject(&rule.name);

        // ── rdf:type triples ──
        if let Some(ms) = model_subject {
            for subj in &subject_uris {
                for rdf_type in &ms.rdf_types {
                    all_triples.push(Triple {
                        subject: subj.clone(),
                        predicate: "a".to_string(),
                        object: RdfTerm::Curie(rdf_type.clone()),
                        subject_name: Some(rule.name.clone()),
                        object_name: None,
                    });
                }
            }
        }

        // ── object triples ──
        let mut obj_vars = local_vars.clone();

        // Separate inline variable defs ($xxx) from real object rules
        let mut real_obj_rules: Vec<&ObjectRule> = Vec::new();
        for obj_rule in &rule.object_rules {
            if obj_rule.name.starts_with('$') {
                // Variable definition in objects section
                let val = exec_pipeline(&obj_rule.pipeline, "", row, &obj_vars, prefixes)?;
                if let PipelineValue::Single(v) = &val {
                    obj_vars.insert(obj_rule.name.clone(), v.clone());
                }
            } else {
                real_obj_rules.push(obj_rule);
            }
        }

        // Track blank node IDs across all object rules of this subject rule.
        // Key = the predicate path from the subject to a blank node, e.g.
        // "<subjectURI>|m2r:variation|faldo:location|faldo:begin". Two leaf
        // objects sharing a blank-node ancestor produce the same key prefix
        // and therefore reuse the same blank node id.
        let mut bnode_map: HashMap<String, String> = HashMap::new();

        for obj_rule in &real_obj_rules {
            // Resolve where this object sits in the model tree: the chain of
            // blank nodes from the subject down to it, the attaching
            // predicate, and the leaf ObjectDef.
            let obj_path = model.object_path(&rule.name, &obj_rule.name);

            // Fallback predicate, used only when the object is absent from
            // the model (validation normally rejects that before we get here).
            let predicate_uri = format!("unknown:{}", obj_rule.name);

            // Execute pipeline, handling inline var defs
            let mut pipeline_vars = obj_vars.clone();
            let pipeline_result = exec_object_pipeline(
                &obj_rule.pipeline, "", row, &mut pipeline_vars, prefixes,
            )?;

            // Detect lang/datatype from pipeline operations
            let pipeline_lang = find_lang_in_ops(&obj_rule.pipeline, &pipeline_vars);
            let pipeline_dt = find_datatype_in_ops(&obj_rule.pipeline, &pipeline_vars);

            // Determine how to create the RDF term
            let value_type = obj_path.as_ref().map(|p| &p.leaf.value_type);

            // ── Helper closure to emit triples (handles nested blank nodes) ──
            let object_cols = extract_col_refs(&obj_rule.pipeline);
            let object_name = obj_rule.name.clone();
            let subject_name = rule.name.clone();
            let emit_triple = |subj: &str, val: &str,
                               all: &mut Vec<Triple>,
                               bmap: &mut HashMap<String, String>|
                {
                    if val.is_empty() { return; }
                    let term = make_rdf_term(val, value_type, &pipeline_lang, &pipeline_dt, prefixes);

                    // Warn if a boolean was expected but the value didn't parse as one
                    if matches!(value_type, Some(ObjectValueType::LiteralBoolean))
                        && !matches!(term, RdfTerm::LiteralBoolean(_))
                    {
                        warn_boolean_parse_failure(
                            source_path, row_num,
                            &object_name, &object_cols, val, row,
                        );
                    }

                    match &obj_path {
                        Some(path) => {
                            // Walk the blank-node chain from the subject down.
                            // Each blank node is created lazily the first time
                            // its predicate-path key is seen, then reused.
                            let mut parent = subj.to_string();
                            let mut path_key = subj.to_string();
                            for (i, step) in path.blanks.iter().enumerate() {
                                path_key.push('|');
                                path_key.push_str(step.predicate);
                                let parent_for_edge = parent.clone();
                                let is_first = i == 0;
                                let bnode_id = bmap.entry(path_key.clone())
                                    .or_insert_with(|| {
                                        let id = next_bnode_id();
                                        // Edge into the blank node:
                                        //   parent --predicate--> _:bN
                                        // Only the first edge starts at the
                                        // real subject; deeper edges start at
                                        // a blank node (subject_name = None).
                                        all.push(Triple {
                                            subject: parent_for_edge.clone(),
                                            predicate: step.predicate.to_string(),
                                            object: RdfTerm::BlankNode(id.clone()),
                                            subject_name: if is_first {
                                                Some(subject_name.clone())
                                            } else {
                                                None
                                            },
                                            object_name: None,
                                        });
                                        // The blank node's own rdf:type triples.
                                        for t in step.rdf_types {
                                            all.push(Triple {
                                                subject: id.clone(),
                                                predicate: "a".to_string(),
                                                object: RdfTerm::Curie(t.clone()),
                                                subject_name: None,
                                                object_name: None,
                                            });
                                        }
                                        id
                                    })
                                    .clone();
                                parent = bnode_id;
                            }
                            // Leaf edge: parent --leaf_predicate--> value.
                            // `parent` is the real subject when there are no
                            // blank nodes, otherwise the innermost blank node.
                            all.push(Triple {
                                subject: parent,
                                predicate: path.leaf_predicate.to_string(),
                                object: term,
                                subject_name: if path.blanks.is_empty() {
                                    Some(subject_name.clone())
                                } else {
                                    None
                                },
                                object_name: Some(object_name.clone()),
                            });
                        }
                        None => {
                            // Object missing from model — emit directly with a
                            // placeholder predicate.
                            all.push(Triple {
                                subject: subj.to_string(),
                                predicate: predicate_uri.clone(),
                                object: term,
                                subject_name: Some(subject_name.clone()),
                                object_name: Some(object_name.clone()),
                            });
                        }
                    }
                };

            match &pipeline_result {
                PipelineValue::Single(val) => {
                    if !val.is_empty() {
                        for subj in &subject_uris {
                            emit_triple(subj, val, &mut all_triples, &mut bnode_map);
                        }
                    }
                }
                PipelineValue::Multiple(vals) => {
                    if subject_uris.len() <= 1 {
                        // Single subject: a multi-valued object means the
                        // subject has *several objects on the same
                        // predicate*. Emit one triple per value so e.g. a
                        // split `variant_types` column yields
                        // `variant_type: [a, b]` in JSON-LD / a repeated
                        // predicate in Turtle — rather than silently
                        // dropping every value past the first.
                        if let Some(subj) = subject_uris.first() {
                            for val in vals {
                                if val == SKIP_SENTINEL || val.is_empty() {
                                    continue;
                                }
                                emit_triple(subj, val, &mut all_triples, &mut bnode_map);
                            }
                        }
                    } else {
                        // Multiple subjects (the subject pipeline was split,
                        // one row → many subject URIs): pair subjects and
                        // values position-by-position.
                        // - When values < subjects: extra subjects get no triple
                        // - When values > subjects: extra values are truncated
                        // - When values == subjects: 1-to-1
                        let pair_count = vals.len().min(subject_uris.len());

                        // Warn if both subject and object were split, but counts differ.
                        let subject_was_split = rule.subject_pipeline.steps.iter()
                            .any(|op| matches!(op, Operation::Split(_)));
                        let object_was_split = obj_rule.pipeline.iter()
                            .any(|op| matches!(op, Operation::Split(_)));
                        if subject_was_split && object_was_split && vals.len() != subject_uris.len() {
                            let subject_cols = extract_col_refs(&rule.subject_pipeline.steps);
                            let object_cols = extract_col_refs(&obj_rule.pipeline);
                            warn_split_mismatch(
                                source_path, row_num,
                                &rule.name, &subject_cols, subject_uris.len(),
                                &obj_rule.name, &object_cols, vals.len(),
                                row,
                            );
                        }

                        for i in 0..pair_count {
                            let val = &vals[i];
                            if val == SKIP_SENTINEL || val.is_empty() {
                                continue;
                            }
                            emit_triple(&subject_uris[i], val, &mut all_triples, &mut bnode_map);
                        }
                    }
                }
                PipelineValue::Skip => {}
            }

            // ── Emit rdf:type triples for Reference-typed objects ──
            if let Some(ObjectValueType::Reference(ref_name)) = value_type {
                let ref_uris: Vec<String> = match &pipeline_result {
                    PipelineValue::Single(val) if !val.is_empty() => vec![val.clone()],
                    PipelineValue::Multiple(vals) => vals.iter()
                        .filter(|v| *v != SKIP_SENTINEL && !v.is_empty())
                        .cloned()
                        .collect(),
                    _ => vec![],
                };
                emit_ref_type_triples(ref_name, &ref_uris, model, &mut all_triples);
            }

            // Merge vars back
            for (k, v) in &pipeline_vars {
                obj_vars.insert(k.clone(), v.clone());
            }
        }

        // ── Reference objects (defined in model but not in convert) ──
        // Only direct (non-blank-nested) leaf objects are considered, matching
        // the previous behavior; auto-emitted references are a top-level
        // feature.
        if let Some(ms) = model_subject {
            for pred_def in &ms.predicates {
                for child in &pred_def.children {
                    let ObjectSpec::Leaf(obj_def) = child else {
                        continue;
                    };
                    let has_rule = rule.object_rules.iter().any(|r| r.name == obj_def.name);
                    if has_rule {
                        continue;
                    }

                    match &obj_def.value_type {
                        ObjectValueType::Reference(ref_name) => {
                            if let Some(ref_uris) = generated_subjects.get(ref_name.as_str()) {
                                // Broadcast rules:
                                // - 1 subject + N refs:  subject gets all N refs (e.g. HGNC → PubMed[])
                                // - N subjects + 1 ref:  all subjects share the same ref (e.g. DbNSFP → Variation)
                                // - N == M:              1-to-1
                                // - N != M (both > 1):   1-to-1 with truncation
                                if subject_uris.len() == 1 {
                                    for ref_uri in ref_uris {
                                        all_triples.push(Triple {
                                            subject: subject_uris[0].clone(),
                                            predicate: pred_def.uri.clone(),
                                            object: RdfTerm::Uri(ref_uri.clone()),
                                            subject_name: Some(rule.name.clone()),
                                            object_name: Some(obj_def.name.clone()),
                                        });
                                    }
                                } else if ref_uris.len() == 1 {
                                    for subj in &subject_uris {
                                        all_triples.push(Triple {
                                            subject: subj.clone(),
                                            predicate: pred_def.uri.clone(),
                                            object: RdfTerm::Uri(ref_uris[0].clone()),
                                            subject_name: Some(rule.name.clone()),
                                            object_name: Some(obj_def.name.clone()),
                                        });
                                    }
                                } else {
                                    let pair_count = ref_uris.len().min(subject_uris.len());
                                    for i in 0..pair_count {
                                        all_triples.push(Triple {
                                            subject: subject_uris[i].clone(),
                                            predicate: pred_def.uri.clone(),
                                            object: RdfTerm::Uri(ref_uris[i].clone()),
                                            subject_name: Some(rule.name.clone()),
                                            object_name: Some(obj_def.name.clone()),
                                        });
                                    }
                                }
                                emit_ref_type_triples(ref_name, ref_uris, model, &mut all_triples);
                            }
                        }
                        ObjectValueType::ReferenceList(ref_names) => {
                            for ref_name in ref_names {
                                if let Some(ref_uris) = generated_subjects.get(ref_name.as_str()) {
                                    if subject_uris.len() == 1 {
                                        for ref_uri in ref_uris {
                                            all_triples.push(Triple {
                                                subject: subject_uris[0].clone(),
                                                predicate: pred_def.uri.clone(),
                                                object: RdfTerm::Uri(ref_uri.clone()),
                                                subject_name: Some(rule.name.clone()),
                                                object_name: Some(obj_def.name.clone()),
                                            });
                                        }
                                    } else if ref_uris.len() == 1 {
                                        for subj in &subject_uris {
                                            all_triples.push(Triple {
                                                subject: subj.clone(),
                                                predicate: pred_def.uri.clone(),
                                                object: RdfTerm::Uri(ref_uris[0].clone()),
                                                subject_name: Some(rule.name.clone()),
                                                object_name: Some(obj_def.name.clone()),
                                            });
                                        }
                                    } else {
                                        let pair_count = ref_uris.len().min(subject_uris.len());
                                        for i in 0..pair_count {
                                            all_triples.push(Triple {
                                                subject: subject_uris[i].clone(),
                                                predicate: pred_def.uri.clone(),
                                                object: RdfTerm::Uri(ref_uris[i].clone()),
                                                subject_name: Some(rule.name.clone()),
                                                object_name: Some(obj_def.name.clone()),
                                            });
                                        }
                                    }
                                    emit_ref_type_triples(ref_name, ref_uris, model, &mut all_triples);
                                }
                            }
                        }
                        _ => {}
                    }
                }
            }
        }

        // Merge local vars back to global
        for (k, v) in &obj_vars {
            global_vars.insert(k.clone(), v.clone());
        }
    }

    Ok((all_triples, convert_subjects))
}

// ─── Pipeline execution ────────────────────────────────────────────

fn exec_pipeline(
    ops: &[Operation],
    initial: &str,
    row: &HashMap<String, String>,
    vars: &Variables,
    prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    exec_pipeline_from(ops, PipelineValue::Single(initial.to_string()), row, vars, prefixes)
}

/// Execute a pipeline starting from a given PipelineValue
fn exec_pipeline_from(
    ops: &[Operation],
    initial: PipelineValue,
    row: &HashMap<String, String>,
    vars: &Variables,
    prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    let mut current = initial;
    for op in ops {
        current = apply_op(&current, op, row, vars, prefixes)?;
    }
    Ok(current)
}

/// Execute object pipeline with inline variable definitions
fn exec_object_pipeline(
    ops: &[Operation],
    initial: &str,
    row: &HashMap<String, String>,
    vars: &mut Variables,
    prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    exec_object_pipeline_from(ops, PipelineValue::Single(initial.to_string()), row, vars, prefixes)
}

/// Execute object pipeline from a given PipelineValue, with support for
/// InlineVarDef and Switch (which need mutable vars).
fn exec_object_pipeline_from(
    ops: &[Operation],
    initial: PipelineValue,
    row: &HashMap<String, String>,
    vars: &mut Variables,
    prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    let mut current = initial;
    for op in ops {
        match op {
            Operation::InlineVarDef(name, sub_ops) => {
                // Pass current pipeline value so pick() etc. can operate on it
                let val = exec_pipeline_from(sub_ops, current.clone(), row, vars, prefixes)?;
                if let PipelineValue::Single(v) = &val {
                    vars.insert(name.clone(), v.clone());
                }
                // current value unchanged
            }
            Operation::Switch { input, cases, default_case } => {
                let switch_val = match input {
                    Some(arg) => resolve_switch_input(arg, row, vars),
                    None => match &current {
                        PipelineValue::Single(s) => s.clone(),
                        _ => String::new(),
                    }
                };
                let matched = cases.iter()
                    .find(|(cv, _)| *cv == switch_val)
                    .map(|(_, ops)| ops)
                    .or(default_case.as_ref());
                if let Some(case_ops) = matched {
                    current = exec_object_pipeline_from(case_ops, current, row, vars, prefixes)?;
                }
            }
            _ => {
                current = apply_op(&current, op, row, vars, prefixes)?;
            }
        }
    }
    Ok(current)
}

fn apply_op(
    current: &PipelineValue,
    op: &Operation,
    row: &HashMap<String, String>,
    vars: &Variables,
    _prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    match op {
        Operation::Col(col_name) => {
            let resolved = expand_vars(col_name, vars);
            let val = row.get(&resolved).cloned().unwrap_or_default();
            Ok(PipelineValue::Single(val))
        }

        Operation::Split(sep) => {
            match current {
                PipelineValue::Single(s) => {
                    if s.is_empty() {
                        return Ok(PipelineValue::Skip);
                    }
                    let mut parts: Vec<String> = s.split(sep.as_str())
                        .map(|p| {
                            let trimmed = p.trim();
                            if trimmed.is_empty() {
                                SKIP_SENTINEL.to_string()
                            } else {
                                trimmed.to_string()
                            }
                        })
                        .collect();
                    // Trim trailing sentinels (caused by trailing delimiters like "a;b;")
                    while parts.last().map_or(false, |p| p == SKIP_SENTINEL) {
                        parts.pop();
                    }
                    if parts.is_empty() || parts.iter().all(|p| p == SKIP_SENTINEL) {
                        Ok(PipelineValue::Skip)
                    } else {
                        Ok(PipelineValue::Multiple(parts))
                    }
                }
                PipelineValue::Multiple(vals) => {
                    let mut all = Vec::new();
                    for v in vals {
                        if v == SKIP_SENTINEL {
                            all.push(SKIP_SENTINEL.to_string());
                            continue;
                        }
                        let mut parts: Vec<String> = v.split(sep.as_str())
                            .map(|p| {
                                let trimmed = p.trim();
                                if trimmed.is_empty() {
                                    SKIP_SENTINEL.to_string()
                                } else {
                                    trimmed.to_string()
                                }
                            })
                            .collect();
                        // Trim trailing sentinels
                        while parts.last().map_or(false, |p| p == SKIP_SENTINEL) {
                            parts.pop();
                        }
                        all.extend(parts);
                    }
                    if all.is_empty() || all.iter().all(|p| p == SKIP_SENTINEL) {
                        Ok(PipelineValue::Skip)
                    } else {
                        Ok(PipelineValue::Multiple(all))
                    }
                }
                PipelineValue::Skip => Ok(PipelineValue::Skip),
            }
        }

        Operation::Prepend(prefix) => {
            let resolved = expand_vars(prefix, vars);
            // An empty value means the source column was absent (NULL).
            // Prepending onto "nothing" keeps it "nothing" so the triple is
            // skipped downstream — otherwise `col()` + `prepend("ncbigene:")`
            // on a NULL column would fabricate the bare prefix "ncbigene:"
            // and emit an invalid triple like `gene:X rdfs:seeAlso ncbigene:`.
            map_values(current, |s| {
                if s.is_empty() { s } else { format!("{}{}", resolved, s) }
            })
        }

        Operation::Append(suffix) => {
            let resolved = expand_vars(suffix, vars);
            // Same rationale as Prepend: appending onto an absent (empty)
            // value keeps it absent rather than producing a bare suffix.
            map_values(current, |s| {
                if s.is_empty() { s } else { format!("{}{}", s, resolved) }
            })
        }

        Operation::Join(args) => {
            if args.len() < 2 {
                return Ok(current.clone());
            }
            let sep = expand_vars(args.last().unwrap(), vars);
            let parts: Vec<String> = args[..args.len() - 1]
                .iter()
                .map(|a| expand_vars(a, vars))
                .collect();
            Ok(PipelineValue::Single(parts.join(&sep)))
        }

        Operation::Skip(skip_vals) => {
            let resolved: Vec<String> = skip_vals.iter().map(|v| expand_vars(v, vars)).collect();
            match current {
                PipelineValue::Single(s) => {
                    if resolved.contains(s) {
                        Ok(PipelineValue::Skip)
                    } else {
                        Ok(current.clone())
                    }
                }
                PipelineValue::Multiple(vals) => {
                    // Replace matching values with sentinel to preserve positional alignment
                    let replaced: Vec<String> = vals.iter()
                        .map(|v| {
                            if resolved.contains(v) {
                                SKIP_SENTINEL.to_string()
                            } else {
                                v.clone()
                            }
                        })
                        .collect();
                    // If all values are sentinels, skip entirely
                    if replaced.iter().all(|v| v == SKIP_SENTINEL) {
                        Ok(PipelineValue::Skip)
                    } else {
                        Ok(PipelineValue::Multiple(replaced))
                    }
                }
                PipelineValue::Skip => Ok(PipelineValue::Skip),
            }
        }

        Operation::Replace(pattern, replacement) => {
            let rp = expand_vars(replacement, vars);
            let rpa = expand_vars(pattern, vars);
            if let Ok(re) = Regex::new(&rpa) {
                map_values(current, |s| re.replace_all(&s, rp.as_str()).to_string())
            } else {
                map_values(current, |s| s.replace(&rpa, &rp))
            }
        }

        Operation::Delete(pattern) => {
            let rpa = expand_vars(pattern, vars);
            if let Ok(re) = Regex::new(&rpa) {
                map_values(current, |s| re.replace_all(&s, "").to_string())
            } else {
                map_values(current, |s| s.replace(&rpa, ""))
            }
        }

        Operation::Pick(n) => {
            match current {
                PipelineValue::Multiple(vals) => {
                    // Extract nth element (0-based), skipping sentinels
                    if let Some(val) = vals.get(*n) {
                        if val == SKIP_SENTINEL {
                            Ok(PipelineValue::Skip)
                        } else {
                            Ok(PipelineValue::Single(val.clone()))
                        }
                    } else {
                        Ok(PipelineValue::Skip)
                    }
                }
                PipelineValue::Single(_s) => {
                    if *n == 0 {
                        Ok(current.clone())
                    } else {
                        Ok(PipelineValue::Skip)
                    }
                }
                PipelineValue::Skip => Ok(PipelineValue::Skip),
            }
        }

        // lang/datatype are metadata-only – don't change the flowing value
        Operation::Lang(_) | Operation::Datatype(_) => Ok(current.clone()),

        Operation::Capitalize => {
            map_values(current, |s| {
                let mut c = s.chars();
                match c.next() {
                    None => String::new(),
                    Some(ch) => ch.to_uppercase().to_string() + c.as_str(),
                }
            })
        }

        Operation::Upcase => map_values(current, |s| s.to_uppercase()),
        Operation::Downcase => map_values(current, |s| s.to_lowercase()),

        Operation::VarRef(var_name) => {
            let resolved = expand_vars(var_name, vars);
            Ok(PipelineValue::Single(resolved))
        }

        Operation::StringTemplate(tpl) => {
            let resolved = expand_vars(tpl, vars);
            Ok(PipelineValue::Single(resolved))
        }

        Operation::InlineVarDef(_, _) => {
            // Handled in exec_object_pipeline_from
            Ok(current.clone())
        }

        Operation::Switch { input, cases, default_case } => {
            // Simple switch (without mutable vars).
            // For full support with InlineVarDefs in cases, use exec_object_pipeline_from.
            let switch_val = match input {
                Some(arg) => resolve_switch_input(arg, row, vars),
                None => match current {
                    PipelineValue::Single(s) => s.clone(),
                    _ => return Ok(current.clone()),
                }
            };
            let matched = cases.iter()
                .find(|(cv, _)| *cv == switch_val)
                .map(|(_, ops)| ops)
                .or(default_case.as_ref());
            if let Some(case_ops) = matched {
                exec_pipeline_from(case_ops, current.clone(), row, vars, _prefixes)
            } else {
                Ok(current.clone())
            }
        }
    }
}

// ─── helpers ───────────────────────────────────────────────────────

fn map_values<F>(current: &PipelineValue, f: F) -> Result<PipelineValue>
where
    F: Fn(String) -> String,
{
    match current {
        PipelineValue::Single(s) => Ok(PipelineValue::Single(f(s.clone()))),
        PipelineValue::Multiple(vs) => {
            Ok(PipelineValue::Multiple(vs.iter().map(|v| {
                if v == SKIP_SENTINEL { v.clone() } else { f(v.clone()) }
            }).collect()))
        }
        PipelineValue::Skip => Ok(PipelineValue::Skip),
    }
}

fn vec_to_pipeline(v: Vec<String>) -> PipelineValue {
    match v.len() {
        0 => PipelineValue::Skip,
        1 => PipelineValue::Single(v.into_iter().next().unwrap()),
        _ => PipelineValue::Multiple(v),
    }
}

fn pipeline_to_vec(pv: &PipelineValue) -> Vec<String> {
    match pv {
        PipelineValue::Single(s) => vec![s.clone()],
        PipelineValue::Multiple(v) => v.clone(),
        PipelineValue::Skip => vec![],
    }
}

/// Expand $var references in a string (longest match first)
fn expand_vars(s: &str, vars: &Variables) -> String {
    let mut result = s.to_string();
    let mut names: Vec<&String> = vars.keys().collect();
    names.sort_by(|a, b| b.len().cmp(&a.len()));
    for name in names {
        if let Some(val) = vars.get(name) {
            result = result.replace(name.as_str(), val);
        }
    }
    result
}

/// Resolve the discriminant value for a `switch(<arg>)` operation.
///
/// `switch` accepts three argument shapes; this resolves the first two
/// (the no-argument form is handled by the caller, which switches on the
/// current pipeline value instead):
///
///   * `switch($var)` — the argument starts with `$`, so it is a variable
///     reference. Resolved purely through `expand_vars`, preserving the
///     original behavior.
///   * `switch("Column")` / `switch(Column)` — the argument is a column
///     name. Resolved by looking up that column in the current `row`.
///
/// For the column form, if the named column does not exist in the row we
/// fall back to `expand_vars` (so a bare token that happens to be a
/// variable name still works, and an unknown token degrades to its literal
/// form rather than silently yielding an empty discriminant). This is what
/// makes `switch("Gender")` match against the row's `Gender` column value
/// rather than the literal string `"Gender"`.
fn resolve_switch_input(arg: &str, row: &HashMap<String, String>, vars: &Variables) -> String {
    if arg.starts_with('$') {
        // Variable reference — unchanged behavior.
        return expand_vars(arg, vars);
    }
    // Column reference: look the value up in the current row.
    if let Some(col_val) = row.get(arg) {
        return col_val.clone();
    }
    // Not a column — fall back to variable expansion (and ultimately to the
    // literal token itself if it's neither a column nor a variable).
    expand_vars(arg, vars)
}

/// Look for lang() in a flat list of ops
fn find_lang_in_ops(ops: &[Operation], vars: &Variables) -> Option<String> {
    for op in ops {
        if let Operation::Lang(tag) = op {
            return Some(expand_vars(tag, vars));
        }
    }
    None
}

/// Look for datatype() in a flat list of ops
fn find_datatype_in_ops(ops: &[Operation], vars: &Variables) -> Option<String> {
    for op in ops {
        if let Operation::Datatype(dt) = op {
            return Some(expand_vars(dt, vars));
        }
    }
    None
}

/// Build an RdfTerm from a string value + model type + pipeline metadata
fn make_rdf_term(
    value: &str,
    value_type: Option<&ObjectValueType>,
    pipeline_lang: &Option<String>,
    pipeline_dt: &Option<String>,
    prefixes: &PrefixMap,
) -> RdfTerm {
    let value = value.trim();

    // Pipeline-level lang/datatype override model-level types
    if let Some(lang) = pipeline_lang {
        return RdfTerm::LiteralLangString(value.to_string(), lang.clone());
    }
    if let Some(dt) = pipeline_dt {
        return RdfTerm::LiteralDatatype(value.to_string(), dt.clone());
    }

    match value_type {
        Some(ObjectValueType::Uri) => {
            // Work out which absolute IRI this value denotes, if any:
            // a full http(s) IRI, an explicit <...> IRI, or a CURIE whose
            // prefix is known. An unknown prefix / a value with no scheme
            // leaves `resolved` as None.
            let resolved: Option<String> =
                if value.starts_with("http://") || value.starts_with("https://") {
                    Some(value.to_string())
                } else if value.starts_with('<') && value.ends_with('>') {
                    Some(value[1..value.len() - 1].to_string())
                } else {
                    expand_curie(value, prefixes)
                };

            match resolved {
                // Resolved to an IRI that oxrdf accepts → a proper URI term.
                Some(iri) if is_valid_iri(&iri) => RdfTerm::Uri(iri),
                // Resolved to a string that is NOT a valid IRI because it
                // carries characters the IRI grammar forbids — e.g. a
                // `civic:drug_` CURIE built from the drug name
                // "Peginterferon Alfa-2b" expands to a string containing a
                // space. Percent-encode those characters and keep the value
                // as a URI, so the model's URI typing (and the JSON-LD
                // `@type: @id` coercion derived from it) stay consistent.
                Some(iri) => {
                    let encoded = percent_encode_forbidden(&iri);
                    if is_valid_iri(&encoded) {
                        RdfTerm::Uri(encoded)
                    } else {
                        // Still not a valid IRI even after encoding (e.g. a
                        // stray `%` that is not a valid `%XX` escape). Fall
                        // back to a literal so the triple is still emitted
                        // rather than silently dropped by the oxrdf
                        // validation pass in `flush_chunk`.
                        RdfTerm::LiteralString(value.to_string())
                    }
                }
                // No known prefix and no scheme. If the bare value is itself
                // a valid absolute IRI (e.g. `urn:isbn:1`) keep it as a CURIE
                // term as before; otherwise it cannot be a URI term at all,
                // so emit it as a literal rather than letting validation
                // drop the triple.
                None if is_valid_iri(value) => RdfTerm::Curie(value.to_string()),
                None => RdfTerm::LiteralString(value.to_string()),
            }
        }
        Some(ObjectValueType::Reference(_)) => {
            RdfTerm::Uri(value.to_string())
        }
        Some(ObjectValueType::LiteralInteger) => {
            if let Ok(i) = value.parse::<i64>() {
                RdfTerm::LiteralInteger(i)
            } else if value.parse::<f64>().is_ok() {
                RdfTerm::LiteralFloat(ensure_decimal_point(value))
            } else {
                RdfTerm::LiteralString(value.to_string())
            }
        }
        Some(ObjectValueType::LiteralFloat) => {
            if value.parse::<f64>().is_ok() {
                RdfTerm::LiteralFloat(ensure_decimal_point(value))
            } else {
                RdfTerm::LiteralString(value.to_string())
            }
        }
        Some(ObjectValueType::LiteralBoolean) => {
            match value.to_lowercase().as_str() {
                "true" | "1" | "yes" | "y" | "t" => RdfTerm::LiteralBoolean(true),
                "false" | "0" | "no" | "n" | "f" => RdfTerm::LiteralBoolean(false),
                _ => RdfTerm::LiteralString(value.to_string()),
            }
        }
        Some(ObjectValueType::LiteralLangString { lang }) => {
            RdfTerm::LiteralLangString(value.to_string(), lang.clone())
        }
        Some(ObjectValueType::LiteralDatatype { datatype }) => {
            RdfTerm::LiteralDatatype(value.to_string(), datatype.clone())
        }
        Some(ObjectValueType::LiteralString) | None => {
            // Auto-detect
            if value.starts_with("http://") || value.starts_with("https://") {
                RdfTerm::Uri(value.to_string())
            } else if is_uri_like(value, prefixes) {
                if let Some(expanded) = expand_curie(value, prefixes) {
                    RdfTerm::Uri(expanded)
                } else {
                    RdfTerm::Curie(value.to_string())
                }
            } else {
                RdfTerm::LiteralString(value.to_string())
            }
        }
        _ => RdfTerm::LiteralString(value.to_string()),
    }
}

/// Percent-encode the characters the IRI grammar forbids outright so a
/// would-be URI value becomes a usable IRI.
///
/// The encoded set is exactly the characters that may never appear in an
/// IRI: the control characters `U+0000`–`U+0020` (which includes the space)
/// and the delimiters `<` `>` `"` `{` `}` `|` `^` `` ` `` `\`. Each is
/// replaced by its `%XX` form (all are single-byte ASCII). Every other
/// character — including non-ASCII ones, which RDF 1.1 IRIs allow — is
/// passed through unchanged.
///
/// This rescues a URI-typed value that resolved to an otherwise-illegal
/// IRI: e.g. a `civic:drug_` CURIE built from the drug name
/// "Peginterferon Alfa-2b" expands to `…/drug_Peginterferon Alfa-2b`, and
/// encoding the space yields the valid IRI `…/drug_Peginterferon%20Alfa-2b`.
///
/// `%` is deliberately *not* encoded: it is legal in an IRI as the start of
/// an escape, so leaving it alone means a value that already contains valid
/// `%XX` escapes is not double-encoded. The trade-off is that a stray `%`
/// which is not a valid escape leaves the result still invalid; the caller
/// re-validates the encoded string and falls back to a literal in that case.
fn percent_encode_forbidden(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\u{00}'..='\u{20}' | '<' | '>' | '"' | '{' | '}' | '|' | '^' | '`' | '\\' => {
                out.push_str(&format!("%{:02X}", c as u32));
            }
            _ => out.push(c),
        }
    }
    out
}

/// Ensure a numeric string has a decimal point so it serializes as xsd:decimal
/// shorthand (e.g. "10" → "10.0", "3.14" → "3.14", "1e5" → "1e5").
/// Emit rdf:type triples for URIs that reference a model subject.
/// E.g., if `ref_name` is "TCGAProject" and model defines `TCGAProject: a tcgao:Project`,
/// then for each `ref_uri`, emit `<ref_uri> a tcgao:Project`.
/// Extract all `col(...)` column names referenced in a pipeline.
/// Returns column names in the order they appear.
fn extract_col_refs(ops: &[Operation]) -> Vec<String> {
    let mut cols = Vec::new();
    for op in ops {
        match op {
            Operation::Col(name) => cols.push(name.clone()),
            Operation::InlineVarDef(_, sub_ops) => cols.extend(extract_col_refs(sub_ops)),
            Operation::Switch { cases, default_case, .. } => {
                for (_, sub_ops) in cases {
                    cols.extend(extract_col_refs(sub_ops));
                }
                if let Some(d) = default_case {
                    cols.extend(extract_col_refs(d));
                }
            }
            _ => {}
        }
    }
    cols
}

/// Format columns as "name1=value1, name2=value2" for warning messages.
fn format_cols(cols: &[String], row: &HashMap<String, String>) -> String {
    if cols.is_empty() {
        return "<no col() reference>".to_string();
    }
    cols.iter()
        .map(|c| format!("{}={:?}", c, row.get(c).map(|s| s.as_str()).unwrap_or("")))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Emit a warning about subject/object split mismatch.
fn warn_split_mismatch(
    source_path: &str,
    row_num: usize,
    subject_name: &str,
    subject_cols: &[String],
    subject_count: usize,
    object_name: &str,
    object_cols: &[String],
    object_count: usize,
    row: &HashMap<String, String>,
) {
    eprintln!(
        "warning: split count mismatch at {}:{}: subject '{}' (count={}, cols: {}) vs object '{}' (count={}, cols: {})",
        source_path, row_num,
        subject_name, subject_count, format_cols(subject_cols, row),
        object_name, object_count, format_cols(object_cols, row),
    );
}

/// Emit a warning about boolean parse failure.
fn warn_boolean_parse_failure(
    source_path: &str,
    row_num: usize,
    object_name: &str,
    object_cols: &[String],
    value: &str,
    row: &HashMap<String, String>,
) {
    eprintln!(
        "warning: cannot parse as boolean at {}:{}: object '{}' (cols: {}) value={:?}",
        source_path, row_num,
        object_name, format_cols(object_cols, row), value,
    );
}

fn emit_ref_type_triples(ref_name: &str, ref_uris: &[String], model: &Model, triples: &mut Vec<Triple>) {
    if let Some(ref_subject) = model.find_subject(ref_name) {
        for rdf_type in &ref_subject.rdf_types {
            for ref_uri in ref_uris {
                triples.push(Triple {
                    subject: ref_uri.clone(),
                    predicate: "a".to_string(),
                    object: RdfTerm::Curie(rdf_type.clone()),
                    subject_name: Some(ref_subject.name.clone()),
                    object_name: None,
                });
            }
        }
    }
}

fn ensure_decimal_point(s: &str) -> String {
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s.to_string()
    } else {
        format!("{}.0", s)
    }
}
