rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
skos: <http://www.w3.org/2004/02/skos/core#> .
dct: <http://purl.org/dc/terms/> .
xsd: <http://www.w3.org/2001/XMLSchema#> .
obo: <http://purl.obolibrary.org/obo/> .
sio: <http://semanticscience.org/resource/> .
im: <http://purl.jp/bio/10/imethyl/dataset/> .
imo: <http://purl.jp/bio/10/imethyl/ontology/> .
imd: <http://purl.jp/bio/10/imethyl/dataset/> .
ims: <http://purl.jp/bio/10/imethyl/sample/> .
faldo: <http://biohackathon.org/resource/faldo#>
