uniprot_enzyme: <http://purl.uniprot.org/enzyme/>
pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
rhea: <http://rdf.rhea-db.org/>
obo: <http://purl.obolibrary.org/obo/>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>