title: NLM Catalog
website: https://www.ncbi.nlm.nih.gov/nlmcatalog/
description: NLMの書誌データ：雑誌、書籍、視聴覚資料、コンピュータソフトウェア、電子リソース、その他の資料に関する情報
tags: [ Ontology/Terminology/Nomenclature, Journal article/Report/Bibliography ]
provider: National Library of Medicine 
rdf_provider: Database Center for Life Science
version: 
issued: 2025-06-30
license:
  - name:                              
  - url: 
  - credit: 
