title: NLM Catalog
website: https://www.ncbi.nlm.nih.gov/nlmcatalog/
description: 雑誌、書籍、視聴覚資料、コンピュータ・ソフトウェア、電子リソース、その他の資料に関するNLM書誌データ
tags: [ Ontology/Terminology/Nomenclature, Journal article/Report/Bibliography ]
provider: ライフサイエンス統合データベースセンター
creators:
  - name: 川島秀一
    affiliation: ライフサイエンス統合データベースセンター
version: 
issued: 2023-05-08
license:
  - name:                              
  - url: 
  - credit: 
