- NLMCatalog nlmcatalog:0431420:
  - a: bibo:Journal
  - dct:title:
    - title: "AANA journal"
  - fabio:hasNLMJournalTitleAbbreviation:
    - journal_abbreviation: "AANA J"
  - bibo:isbm?:
    - isbn: "0094-6354"
  - prism:eISSN?:
    - eissn: "2162-5239" 
  - fabio:hasNationalLibraryOfMedicineJournalId:
    - journal_id: "2"
