nlmcatalog: <http://www.ncbi.nlm.nih.gov/nlmcatalog/>
dct: <http://purl.org/dc/terms/>
bibo: <http://purl.org/ontology/bibo/>
prism: <http://prismstandard.org/namespaces/1.2/basic/>
fabio: <http://purl.org/spar/fabio/>
