title: Integbioデータベースカタログ/RDF
website: https://catalog.integbio.jp/dbcatalog/
description: ntegbioデータベースカタログ/RDFはIntegbioデータベースカタログデータをRDFへ変換したものです
tags: [Others, Others]
provider: 
creators:
  - name: 井手隆広
    affiliation: NBDC, JST
  - name: 信定知江
    affiliation: NBDC, JST
  - name: 坂東明日佳
    affiliation: NBDC, JST
rdf_creators:
  - name: 井手隆広
    affiliation: NBDC, JST
  - name: 信定知江 
    affiliation: NBDC, JST
  - name: 坂東明日佳
    affiliation: NBDC, JST
version: release_20230302
issued: 2023-03-02
licenses:
  - http://creativecommons.org/publicdomain/zero/1.0/
  - Integbio Database Catalog© National Bioscience Database Center licensed under CC Attribution 2.1 Japan
