title: Integbio Database Catalog/RDF
website: https://catalog.integbio.jp/dbcatalog/en/
description: Integbio Database Catalog/RDF is a translation of Integbio Database Catalog data into RDF
tags: [Others, Others]
provider: 
creators:
  - name: Takahiro Ide
    affiliation: NBDC, JST
  - name: Tomoe Nobusada
    affiliation: NBDC, JST
  - name: Asuka Bando
    affiliation: NBDC, JST
rdf_creators:
  - name: Takahiro Ide
    affiliation: NBDC, JST
  - name: Tomoe Nobusada
    affiliation: NBDC, JST
  - name: Asuka Bando
    affiliation: NBDC, JST
version: release_20230302
issued: 2023-03-02
licenses:
  - http://creativecommons.org/publicdomain/zero/1.0/
  - Integbio Database Catalog© National Bioscience Database Center licensed under CC Attribution 2.1 Japan
