- DatabaseInfo db:nbdc00448:
  - a: dcat:Dataset
  - dcterms:title+:
    - database_name: '"FANTOM4"@en'
  - dcterms:alternative*:
    - alternative_name: '"Functional Annotation of the Mammalian Genome 4"@en'
  - dcterms:description+:
    - database_description: '"FANTOM is a database about functional annotations of the Mammalian genomes. It contains experimental data of the FANTOM consortium which is an international collaborative research project initiated and organized by the RIKEN Omics Science Center. This database includes CAGE tags, mapping, and promoters (clusters or aggregations of CAGE tags as units of promoter) for human and mouse, and information about the experiments and data processing. Users are able to use genome browser or EDGE express DB which is designed for integrating and interpreting large high-throughput expression datasets in the context of biological networks."@en'
  - dcterms:identifier:
    - database_id: "NBDC00448"
  - dcterms:language+:
    - language: lang:ja
  - dcterms:publisher*:
    - []:
      - a: foaf:Organization
      - rdfs:label*:
        - organization_name: '"国立研究開発法人理化学研究所　横浜研究所"@ja'
      - schema:addressCountry*:
        - country_region: '"Japan"@en'
      - rdfs:seeAlso:
        - xref_jglobal: <https://jglobal.jst.go.jp/detail?JGLOBAL_ID=200905002425357790>
      - foaf:page:
        - jglobal_id: <http://stirdf.jst.go.jp/id/200905002425357790>
  - dcterms:references*:
    - pubmed_id: pubmed:19377475, pubmed:20211142, pubmed:19377474, pubmed:19377478
  - rdfs:seeAlso:
    - xref_similardb: db:nbdc00638, db:nbdc00447, db:nbdc00735, db:nbdc00053, db:nbdc00734, db:nbdc00252, db:nbdc00015, db:nbdc01389, db:nbdc01666, db:nbdc00256
    - xref_togotv: <http://togotv.dbcls.jp/ja/?search=FANTOM4>
    - xref_dbarchive: <http://dbarchive.biosciencedbc.jp/jp/fantom4/desc.html>
  - dcat:distribution*:
    - []:
      - a: dcat:Distribution
      - dcterms:description*:
        - downloadmetadata_url: <http://fantom.gsc.riken.jp/4/download/>
      - dcterms:rights*:
        - dbrights_url: <http://fantom.gsc.riken.jp/4/download/>
      - dcat:accessURL*:
        - downloadpage_url: <http://fantom.gsc.riken.jp/4/download/>
  - dcat:landingPage{1,2}:
    - landingpage_url: <http://fantom.gsc.riken.jp/4/index.php?lang=en>, <http://fantom.gsc.riken.jp/4/index.php?lang=jp>
  - dcat:theme*:
    - theme_tag: DatabaseTag
    - taxonomy_id: taxddbj:9606
  - foaf:status{2}:
    - status: '"Active"@en'
- DatabaseTag tag:T0001:
  - a: skos:Concept
  - dcterms:identifier:
    - tag_id: "T0001"
  - skos:definition{2}:
    - tag_definition: '"DB for genomes or genes"@en'
  - rdfs:label{2}:
    - tag: '"Genome/Gene"@en'
  - skos:prefLabel{2}:
    - tag_label: '"Genome/Gene"@en'