rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
node: <http://example.org/vg/node/>
path: <http://example.org/vg/path/>
vg: <http://biohackathon.org/resource/vg#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
faldo: <http://biohackathon.org/resource/faldo#>
