endpoint:
  - https://rdfportal.org/primary/sparql
  - graph:
    - http://jcggdb.jp/rdf/diseases/paconto
    - http://jcggdb.jp/rdf/diseases/paconto-schema.rdf
another_endpoint:
  - https://sparql.glycoinfo.org/sparql
