title: RDF title
website: https://example.com/
description: RDF description.
tags: []
provider:
creators:
  - name: Name 1
    affiliation: Affiliation 1
  - name: Name 2
    affiliation: Affiliation 2
version: 2020-01-01
issued: 2020-01-01
licenses:
  - Attribution 4.0 International (CC BY 4.0) 
