dataset:
  name: Nucleic Acid Drug Database
  description: DB is focused on nucleic acid drugs known as biopharmaceuticals and displayed approval drugs and information on three phases of clinical trial stage.
