title: Nucleic Acid Drug Database
website: https://medals.jp/edrugnainfo.html
description: DB is focused on nucleic acid drugs known as biopharmaceuticals and displayed approval drugs and information on three phases of clinical trial stage.
tags: [Drug/Chemical, RNA, Sequence, Structure, Journal article/Report/Bibliography]
provider: Molecular Profiling Research Center for Drug Discovery (molprof), The National Institute of Advanced Industrial Science and Technology (AIST)
creators:
  - name: Kazuhiko Fukui
    affiliation: Molecular Profiling Research Center for Drug Discovery (molprof), The National Institute of Advanced Industrial Science and Technology (AIST)
  - name: Takayuki Amemiya
    affiliation: Molecular Profiling Research Center for Drug Discovery (molprof), The National Institute of Advanced Industrial Science and Technology (AIST)
  - name: Hiroshi Kouno
    affiliation: Molecular Profiling Research Center for Drug Discovery (molprof), The National Institute of Advanced Industrial Science and Technology (AIST)/Department of Applied Biological Science, Faculty of Science and Technology, Tokyo University of Science
version: 2019-05-14
issued: 2019-05-14
licenses:
  - Attribution-ShareAlike 2.1 Japan (CC BY-SA 2.1) 
