endpoint:
  - https://sparql.glyconavi.org/sparql
  - graph:
    - http://rdf.glycoinfo.org/wurcs/0.5.1
    - http://rdf.glycoinfo.org/wurcs/ms/0.2
    - http://rdf.glycoinfo.org/wurcs/seq/0.3
another_endpoint:
  - https://sparql.glyconavi.org/sparql
  - graph:
    - http://rdf.glycoinfo.org/wurcs-rdf-0.5.1-20190905
