endpoint:
  - https://rdfportal.org/pubchem/sparql
  - graph:
    - http://rdf.ncbi.nlm.nih.gov/pubchem/compound
    - http://rdf.ncbi.nlm.nih.gov/pubchem/substance
    - http://rdf.ncbi.nlm.nih.gov/pubchem/descriptor/compound
    - http://rdf.ncbi.nlm.nih.gov/pubchem/descriptor/substance
    - http://rdf.ncbi.nlm.nih.gov/pubchem/synonym
    - http://rdf.ncbi.nlm.nih.gov/pubchem/inchikey
    - http://rdf.ncbi.nlm.nih.gov/pubchem/measuregroup
    - http://rdf.ncbi.nlm.nih.gov/pubchem/endpoint
    - http://rdf.ncbi.nlm.nih.gov/pubchem/bioassay
    - http://rdf.ncbi.nlm.nih.gov/pubchem/protein
    - http://rdf.ncbi.nlm.nih.gov/pubchem/pathway
    - http://rdf.ncbi.nlm.nih.gov/pubchem/conserveddomain
    - http://rdf.ncbi.nlm.nih.gov/pubchem/gene
    - http://rdf.ncbi.nlm.nih.gov/pubchem/reference
    - http://rdf.ncbi.nlm.nih.gov/pubchem/source
    - http://rdf.ncbi.nlm.nih.gov/pubchem/concept
    - http://rdf.ncbi.nlm.nih.gov/pubchem/patent
    - http://rdf.ncbi.nlm.nih.gov/pubchem/taxonomy
    - http://rdf.ncbi.nlm.nih.gov/pubchem/cell
    - http://rdf.ncbi.nlm.nih.gov/pubchem/cooccurrence
    - http://rdf.ncbi.nlm.nih.gov/pubchem/disease
    - http://rdf.ncbi.nlm.nih.gov/pubchem/book
    - http://rdf.ncbi.nlm.nih.gov/pubchem/journal
    - http://rdf.ncbi.nlm.nih.gov/pubchem/author
    - http://rdf.ncbi.nlm.nih.gov/pubchem/organization
    - http://rdf.ncbi.nlm.nih.gov/pubchem/grant
    - http://rdf.ncbi.nlm.nih.gov/pubchem/void
