title: PubChem RDF
website: https://pubchem.ncbi.nlm.nih.gov/
description: PubChem は、NIHが提供する、網羅的な化合物のデータベースです。詳細な情報は次のURLを参照してください: https://pubchemdocs.ncbi.nlm.nih.gov/about 注意\: エンドポイントには次のURLのファイルは含まれていません。 ftp\://ftp.ncbi.nlm.nih.gov/pubchem/RDF/compound/nbr2d/ , ftp\://ftp.ncbi.nlm.nih.gov/pubchem/RDF/compound/nbr3d/
tags: [Drug/Chemical, Other biomolecule]
provider: National Center for Biotechnology Information
rdf_provider: National Center for Biotechnology Information
version:
issued: 2025-05-28
license:
  - name:                              
  - url: https://www.ncbi.nlm.nih.gov/home/about/policies/
  - credit: 
