owl: <http://www.w3.org/2002/07/owl#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dcterms: <http://purl.org/dc/terms/>
vocab: <http://rdf.ncbi.nlm.nih.gov/pubchem/vocabulary#>
bao: <http://www.bioassayontology.org/bao#>
bioassay: <http://rdf.ncbi.nlm.nih.gov/pubchem/bioassay/>
source:  <http://rdf.ncbi.nlm.nih.gov/pubchem/source/>
taxonomy: <http://rdf.ncbi.nlm.nih.gov/pubchem/taxonomy/>
measuregroup: <http://rdf.ncbi.nlm.nih.gov/pubchem/measuregroup/>
endpoint: <http://rdf.ncbi.nlm.nih.gov/pubchem/endpoint/>
protein: <http://rdf.ncbi.nlm.nih.gov/pubchem/protein/>
substance: <http://rdf.ncbi.nlm.nih.gov/pubchem/substance/>
compound: <http://rdf.ncbi.nlm.nih.gov/pubchem/compound/>
reference: <http://rdf.ncbi.nlm.nih.gov/pubchem/reference/>
patent: <http://rdf.ncbi.nlm.nih.gov/pubchem/patent/>
patentassignee: <http://rdf.ncbi.nlm.nih.gov/pubchem/patentassignee/>
patentcpc: <http://rdf.ncbi.nlm.nih.gov/pubchem/patentcpc/>
patentipc: <http://rdf.ncbi.nlm.nih.gov/pubchem/patentipc/>
pathway: <http://rdf.ncbi.nlm.nih.gov/pubchem/pathway/>
synonym: <http://rdf.ncbi.nlm.nih.gov/pubchem/synonym/>
concept: <http://rdf.ncbi.nlm.nih.gov/pubchem/concept/>
gene: <http://rdf.ncbi.nlm.nih.gov/pubchem/gene/>
conserveddomain: <http://rdf.ncbi.nlm.nih.gov/pubchem/conserveddomain/>
descriptor: <http://rdf.ncbi.nlm.nih.gov/pubchem/descriptor/>
inchikey: <http://rdf.ncbi.nlm.nih.gov/pubchem/inchikey>
pav: <http://purl.org/pav/>
biopax: <http://www.biopax.org/release/biopax-level3.owl#>
sio: <http://semanticscience.org/resource/>
obo: <http://purl.obolibrary.org/obo/>
cito: <http://purl.org/spar/cito/>
epo_patent: <http://data.epo.org/linked-data/def/patent/>
epo_cpc: <http://data.epo.org/linked-data/def/cpc/>
epo_ipc: <http://data.epo.org/linked-data/def/ipc/>
pdbo: <http://rdf.wwpdb.org/schema/pdbx-v40.owl#>
up: <http://purl.uniprot.org/core/>
fabio: <http://purl.org/spar/fabio/>
foaf: <http://xmlns.com/foaf/0.1/>
skos: <http://www.w3.org/2004/02/skos/core#>
chembl: <http://rdf.ebi.ac.uk/resource/chembl/molecule/>
ensembl: <http://rdf.ebi.ac.uk/resource/ensembl/>
# TODO: check these are used (delete if not)
cooccurrence: <http://rdf.ncbi.nlm.nih.gov/pubchem/cooccurrence/>
author: <http://rdf.ncbi.nlm.nih.gov/pubchem/author/>
book: <http://rdf.ncbi.nlm.nih.gov/pubchem/book/>
cell: <http://rdf.ncbi.nlm.nih.gov/pubchem/cell/>
disease: <http://rdf.ncbi.nlm.nih.gov/pubchem/disease/>
grant: <http://rdf.ncbi.nlm.nih.gov/pubchem/grant/>
journal: <http://rdf.ncbi.nlm.nih.gov/pubchem/journal/>
organization: <http://rdf.ncbi.nlm.nih.gov/pubchem/organization/>
edam: <http://edamontology.org/>
vcard2006: <http://www.w3.org/2006/vcard/ns#>
prism: <http://prismstandard.org/namespaces/basic/3.0/>
frapo: <http://purl.org/cerif/frapo/>
