rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
dct:	<http://purl.org/dc/terms/>
bao:	<http://www.bioassayontology.org/bao#>
bioassay:	<http://rdf.ncbi.nlm.nih.gov/pubchem/bioassay/>
source:		<http://rdf.ncbi.nlm.nih.gov/pubchem/source/>
taxonomy:	<http://rdf.ncbi.nlm.nih.gov/pubchem/taxonomy/>
measuregroup:	<http://rdf.ncbi.nlm.nih.gov/pubchem/measuregroup/>
endpoint:	<http://rdf.ncbi.nlm.nih.gov/pubchem/endpoint/>
protein:	<http://rdf.ncbi.nlm.nih.gov/pubchem/protein/>
substance:	<http://rdf.ncbi.nlm.nih.gov/pubchem/substance/>
pubchemv:	<http://rdf.ncbi.nlm.nih.gov/pubchem/vocabulary#>
reference:	<http://rdf.ncbi.nlm.nih.gov/pubchem/reference/>
biopax:	<http://www.biopax.org/release/biopax-level3.owl#>
sio:	<http://semanticscience.org/resource/>
obo:	<http://purl.obolibrary.org/obo/>
cito:	<http://purl.org/spar/cito/>