title:  dbscSNV  
website: http://www.liulab.science/dbscsnv.html  
description: a comprehensive database of all potential human SNVs within splicing consensus regions and their functional annotations  
tags: ["SNV", "splicing consensus region"]
provider: The University of Texas Health Science Center at Houston 
creators:
  - name: Med2RDF project  
    affiliation: http://med2rdf.org/ 
version: 1.1
issued: 2015-04-12 
licenses:
  - No information is available. 
