- DbscSNV <http://identifiers.org/hco/1/GRCh38#248914432-C-T>:
    - a: dbscsnv:DbscSNV
    - rdfs:label:
        - variation_label: "1-248914432-C-T"
    - m2r:reference_allele:
        - ref_allele: "C"
    - m2r:alternative_allele:
        - alt_allele: "T"
    - faldo:position:
        - position: 248914432
    - faldo:reference:
        - reference: <http://identifiers.org/hco/1/GRCh38>
    - dbscsnv:damage_prediction*:
        - damage_prediction:
            - RandomForest
            - AdaBoost
    - dbscsnv:hasEnsembl:
        - dbscsnv_ensembl: DbscSNVEnsembl
    - dbscsnv:hasRefSeq:
        - dbscsnv_refseq: DbscSNVRefSeq

- DbscSNVEnsembl <http://identifiers.org/hco/1/GRCh38#248914432-C-T-Ensembl>:
    - a: dbscsnv:Ensembl
    - dbscsnv:is_ensembl:
        - is_ensembl: "y"
    - dbscsnv:ensembl_region:
        - ensembl_region: "UTR5"
    - dbscsnv:ensembl_gene:
        - ensembl_gene_id: "ENSG00000187634"
    - dbscsnv:ensembl_functional_consequence:
        - ensembl_functional_consequence: "nonsynonymous SNV"
    - dbscsnv:ensembl_id_c_change_p_change:
        - ensembl_id_c_change_p_change: "ENSG00000198400:ENST00000497019:exon11:c.C1115A:p.A372D;"

- DbscSNVRefSeq <http://identifiers.org/hco/1/GRCh38#248914432-C-T-RefSeq>:
    - a: dbscsnv:RefSeq
    - dbscsnv:is_refseq:
        - is_refseq: "n"
    - dbscsnv:refseq_region:
        - refseq_region: "upstream"
    - dbscsnv:refseq_functional_consequence:
        - refseq_functional_consequence: "nonsynonymous SNV"
    - dbscsnv:refseq_id_c_change_p_change:
        - refseq_id_c_change_p_change: "NBPF11:NM_183372:exon10:c.A1148G:p.Y383C;"
    - dbscsnv:refseq_gene:
        - refseq_gene: "SAMD11"

- RandomForest <http://identifiers.org/hco/1/GRCh38#248914432-C-T-RandomForest>:
    - a:
        - dbscsnv:DamagePrediction
        - dbscsnv:RandomForest
    - dbscsnv:score:
        - random_forest_score: 0.03

- AdaBoost <http://identifiers.org/hco/1/GRCh38#248914432-C-T-AdaBoost>:
    - a:
        - dbscsnv:DamagePrediction
        - dbscsnv:AdaBoost
    - dbscsnv:score:
        - ada_boost_score: 0.007645
