dcmiterms: <http://dublincore.org/documents/dcmi-terms/>
hco: <http://identifiers.org/hco/1#>
med2rdf: <http://med2rdf.org/ontology/med2rdf#>
dbscsnv: <http://purl.jp/bio/10/med2rdf/dbscsnv/>
dbscsnv_algorithm: <http://purl.jp/bio/10/med2rdf/dbscsnv/algorithm/>
dbscsnv_faldo: <http://purl.jp/bio/10/med2rdf/dbscsnv/faldo/>
dbscsnv_gene: <http://purl.jp/bio/10/med2rdf/dbscsnv/gene/>
dbscsnv_variation: <http://purl.jp/bio/10/med2rdf/dbscsnv/variation/>
ensembl_gene: <http://rdf.ebi.ac.uk/resource/ensembl.gene/>
sio: <http://semanticscience.org/ontology/>
faldo: <http://biohackathon.org/resource/faldo#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>