- Gene:
    - source("nightly-FeatureSummaries_head101.tsv")
    - subject:
        - tsv("feature_id")
        - prepend("gene:")
    - objects:
        - gene_identifier: tsv("feature_id")
        - gene_label: tsv("name")
        - ncbigene:
            - tsv("entrez_id")
            - prepend("ncbigene:")
        # - variation:

- Variation:
    - source("nightly-VariantSummaries_head101.tsv")
    - subject:
        - tsv("variant_id")
        - prepend("variants:")
    - objects:
        - variation_identifier: tsv("variant_id")
        - variation_label: tsv("variant")
        # variant_originカラムなし
        # - variant_origin:
        - reference_build: tsv("reference_build")
        - transcript_label: tsv("representative_transcript")
        - ensembl_version: tsv("ensembl_version")
        # variant_summaryカラムなし
        # - variation_description:
        # m2r:disease civic:LymphoidLeukemia,civic:ChronicMyeloidLeukemia,civic:BoneMarrowCancer,civic:PolycythemiaVera
        # (Disease.disease_code)
        # - disease:
        - enst:
            - tsv("representative_transcript")
            - replace(/\.\d+$/, "")
            - prepend("enst:")
        # frameshift_truncation,dominant_negative_variant
        # map(lambda x: urllib.parse.quote(x.replace(" ","").replace("/","-"))  , self.variant_types.split(','))
        - variant_type:
            - tsv("variant_types")
            - skip("N/A")
            - split(",")
            - prepend("civic:")
        # Evidenceクラス evidence_idはnightly-ClinicalEvidenceSummaries.tsvファイルにある
        # => どのように関連付けるか不明
        # - evidence:

- Evidence:
    - source("nightly-ClinicalEvidenceSummaries_head101.tsv")
    - subject:
        - tsv("evidence_id")
        - prepend("evidence:")
    - objects:
        - evidence_description: tsv("evidence_statement")
        - clinical_significance: tsv("significance")
        - evidence_direction: tsv("evidence_direction")
        - evidence_type: tsv("evidence_type")
        - rating: tsv("rating")
        - evidence_level: tsv("evidence_level")
        - evidence_status: tsv("evidence_status")
        - citation: tsv("citation")

        # ToDo: 以下の処理は source_typeカラムの値が PubMed の場合のみ限定する必要がある
        - pubmed:
            - tsv("citation_id")
            - prepend("pubmed:")

        # model.yamlの例で drug_Palbociclib となっており、Palbociclib という値は
        # therapiesカラムに現れるが、これを使って良いか？
        - drug:
            - tsv("therapies")
            - split(",")
            - prepend("civic:drug_")
