- Gene:
    - source("civic.duckdb", :duckdb, "feature_variants")
    - subject:
        - col("features_feature_id")
        - prepend("gene:")
    - objects:
        - gene_identifier: col("features_feature_id")
        - gene_label: col("features_name")
        - ncbigene:
            - col("features_entrez_id")
            - prepend("ncbigene:")

        # Variation
        - variation:
            - col("variants_variant_id")
            - prepend("variants:")

- Variation:
    - source("civic.duckdb", :duckdb, "variants")
    - subject:
        - col("variant_id")
        - prepend("variants:")
    - objects:
        - variation_identifier: col("variant_id")
        - variation_label: col("variant")
        # variant_originカラムなし
        # - variant_origin:
        - reference_build: col("reference_build")
        - transcript_label: col("representative_transcript")
        - ensembl_version: col("ensembl_version")
        # variant_summaryカラムなし
        # - variation_description:
        # m2r:disease civic:LymphoidLeukemia,civic:ChronicMyeloidLeukemia,civic:BoneMarrowCancer,civic:PolycythemiaVera
        # (Disease.disease_code)
        # - disease:
        - enst:
            - col("representative_transcript")
            - replace(/\.\d+$/, "")
            - prepend("enst:")
        # frameshift_truncation,dominant_negative_variant
        # map(lambda x: urllib.parse.quote(x.replace(" ","").replace("/","-"))  , self.variant_types.split(','))
        - variant_type:
            - col("variant_types")
            - skip("N/A")
            - split(",")
            - prepend("civic:")
        # Evidenceクラス evidence_idはnightly-ClinicalEvidenceSummaries.tsvファイルにある
        # => どのように関連付けるか不明
        # - evidence:

- Evidence:
    - source("civic.duckdb", :duckdb, "clinical_evidences")
    - subject:
        - col("evidence_id")
        - prepend("evidence:")
    - objects:
        - evidence_description: col("evidence_statement")
        - clinical_significance: col("significance")
        - evidence_direction: col("evidence_direction")
        - evidence_type: col("evidence_type")
        - rating: col("rating")
        - evidence_level: col("evidence_level")
        - evidence_status: col("evidence_status")
        - citation: col("citation")
        - pubmed:
            - switch("source_type"):
                "PubMed":
                    - col("citation_id")
                    - prepend("pubmed:")

        # model.yamlの例で drug_Palbociclib となっており、Palbociclib という値は
        # therapiesカラムに現れるが、これを使って良いか？
        - drug:
            - col("therapies")
            - split(",")
            - prepend("civic:drug_")
