rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
ncbigene: <http://identifiers.org/ncbigene/>
pubmed: <http://identifiers.org/pubmed/>
enst: <http://rdf.ebi.ac.uk/resource/ensembl.transcript/>
faldo: <http://biohackathon.org/resource/faldo#>
m2r: <http://med2rdf.org/ontology/med2rdf#>
civic: <http://purl.jp/bio/10/civic/>
civico: <http://purl.jp/bio/10/civic/ontology#>
gene: <http://civic.genome.wustl.edu/links/genes/>
evidence: <http://civic.genome.wustl.edu/links/evidence_items/>
variants: <http://civic.genome.wustl.edu/links/variants/>
