endpoint: https://integbio.jp/primary/sparql
graphs:
  - http://rdf.glycoinfo.org/glycoepitope
  - http://www.glycoepitope.jp/epitopes/glycoepitope.owl
ontologies:
  - http://www.glycoepitope.jp/epitopes/glycoepitope.owl
