title: GlycoEpitope
website: https://www.glycoepitope.jp/
description: GlycoEpitopeは、糖鎖抗体とその抗原についてのデータベースです
tags: [ Other biomolecule, Structure ]
provider: 立命館大学
creators:
  - name: 川嵜敏祐
    affiliation: 立命館大学
  - name: 奥田修二郎
    affiliation: 新潟大学
version: version 3
issued: 2015-11-18
license:
  - name: Creative Commons Attribution-ShareAlike 2.1 Japan (CC BY-SA 2.1 JP)
  - url: https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en
  - credit: GlycoEpitope licensed under CC Attribution-Share Alike 2.1 Japan
