title: GlycoEpitope
website: https://www.glycoepitope.jp/
description: GlycoEpitope is a database of useful information on carbohydrate antigens and antibodies.
tags: [ Other biomolecule, Structure ]
provider: Ritsumeikan University
creators:
  - name: Tshisuke Kawasaki
    affiliation: Ritsumeikan University
  - name: Shujiro Okuda
    affiliation: Niigata University
version: version 3
issued: 2015-11-18
license:
  - name: Creative Commons Attribution-ShareAlike 2.1 Japan (CC BY-SA 2.1 JP)
  - url: https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en
  - credit: GlycoEpitope licensed under CC Attribution-Share Alike 2.1 Japan
