- GlycanEpitope glycoepitope:EP0001:
  - a: glycan:Glycan_epitope
  - dct:identifier: "EP0001"
  - rdfs:label:
    - label: "HNK-1"
  - glycan:catalized_by:
    - enzyme: Enzyme
  - glycan:has_glycosequence:
    - glycosequence: Glyep
  - glycan:has_resource_entry:
    - resource: Jcggdb
  - glycoepitope:has_affinity_to:
    - affinity_to: Receptor
  - glycoepitope:has_antibody:
    - antibody: Antibody
  - glycoepitope:tissue:
    - tussue: Tissue

- Enzyme glycoepitope:EP0001\/enzyme\/1:
  - a: glycan:Enzyme
  - dct:description: "glucuronyltransferase P"

- Glyep <http://www.glycoepitope.jp/epitopes/EP0001/glyep>:
  - a: glycan:Glycosequence
  - glycan:has_sequence: '"HSO3(-3)GlcA(b1-3)Gal(b1-4)GlcNAc-R"^^xsd:string'

- Jcggdb <http://jcggdb.jp/idb/jcggdb/JCGG-STR032038>:
  - a: glycan:Resource_entry
  - dct:identifier: "JCGG-STR032038"

- Receptor <http://www.glycoepitope.jp/epitopes/EP0001/receptor/L%2Dselecti>:
  - a: glycan:Receptor
  - rdfs:label: "L-selectin"

- Antibody <http://www.glycoepitope.jp/epitopes/AN0008>:
  - a: glycan:Antibody
  - dct:identifier: "AN0008"
  - glycoepitope:has_affinity_to: Glycan_epitope
  - glycoepitope:organism: "Rat"
  - rdfs:label: "334"

- Tissue <http://www.glycoepitope.jp/epitopes/rdfs/list.ttl#natural%2520killer%2520cell>:
  - a: uniprot:Tissue
  - rdfs:label: "natural killer cell"
