rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
skos: <http://www.w3.org/2004/02/skos/core#>
dct: <http://purl.org/dc/terms/>
xsd: <http://www.w3.org/2001/XMLSchema#>
obo: <http://purl.obolibrary.org/obo/>
glycan: <http://purl.jp/bio/12/glyco/glycan#>
glycoepitope: <http://www.glycoepitope.jp/epitopes/>
uniprot: <http://www.uniprot.org/core/>
