title: GlyCosmos
website: https://glycosmos.org/
description: RDF description.
tags: [Glycan]
provider: GlyCosmos Portal
creators:
  - name: Kiyoko F. Aoki-Kinoshita
    affiliation: Soka University
  - name: Osamu Kanie
    affiliation: Tokai University
  - name: Toshisuke Kawasaki
    affiliation: Ritsumeikan University
  - name: Tadashi Suzuki
    affiliation: RIKEN
  - name: Kiichiro Totani
    affiliation: Seikei University
  - name: Hiroshi Nakada
    affiliation: Kyoto Sangyo University
  - name: Shunji Natsuka
    affiliation: Niigata University
  - name: Shoko Nishihara
    affiliation: Soka University
  - name: Yoshiki Yamaguchi
    affiliation: Tohoku Medical and Pharmaceutical University
  - name: Katsuko Yamashita
    affiliation: Yokohama City University
  - name: Issaku Yamada
    affiliation: The Noguchi Institute
version: 2021-08-09
issued: 2021-08-09
licenses:
  - Creative Commons Attribution 4.0 International License (CC BY 4.0)
