bibo: <http://purl.org/ontology/bibo/>
dct: <http://purl.org/dc/terms/>
glycan: <http://purl.jp/bio/12/glyco/glycan#>
glytoucan: <http://www.glytoucan.org/glyco/owl/glytoucan#>
info: <http://rdf.glycoinfo.org/glycan/>
ncbitaxon: <http://purl.org/obo/owl/NCBITaxon#>
obo: <http://purl.obolibrary.org/obo/>
owl: <http://www.w3.org/2002/07/owl#>
p15: <http://rdf.glytoucan.org/partner/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
ref: <http://rdf.glycoinfo.org/references/>
resent: <http://rdf.glycoinfo.org/resource-entry/>
skos: <http://www.w3.org/2004/02/skos/core#>
src: <http://rdf.glycoinfo.org/source/>
up: <http://purl.uniprot.org/core/>
wurcs: <http://www.glycoinfo.org/glyco/owl/wurcs#>
sbsmpt: <http://www.glycoinfo.org/glyco/owl/relation#>
mass: <https://glycoinfo.gitlab.io/wurcsframework/org/glycoinfo/wurcsframework/1.0.1/wurcsframework-1.0.1.jar#>
dcterms: <http://purl.org/dc/terms/>
