sparql:
  description: SPARQL description.
  variables: [Glycan,iupac_condensed,sequence,glyco_src]

subsumption:
  description: get subsumption relationship.
  variables: [WurcsURI, mass, subsuming_wurcs]
