title: Bgee
website: https://www.bgee.org/
description: 複数の動物種にわたる遺伝子発現パターンの検索と比較のためのデータベース
tags: [Gene, Gene expression]
provider: SIB Swiss Institute of Bioinformatics
version: 15.2.3
issued: 2024-00-00
licenses:
  - Commons Zero license (CC0) 
