title: Bgee
website: https://www.bgee.org/
description: A database for retrieval and comparison of gene expression patterns across multiple animal species 
tags: [Gene, Gene expression]
provider: SIB Swiss Institute of Bioinformatics
version: 15.2.3
issued: 2024-00-00
licenses:
  - Commons Zero license (CC0) 
