rdfs: <http://www.w3.org/2000/01/rdf-schema#>
oma: <http://omabrowser.org/ontology/oma#>
bgee: <http://bgee.org/#>
orth: <http://purl.org/net/orth#>
genex: <http://purl.org/genex#>
obo: <http://purl.obolibrary.org/obo/>
up: <http://purl.uniprot.org/uniprot/>
core: <http://purl.uniprot.org/core/>
taxonomy: <http://purl.uniprot.org/taxonomy/>
lscr: <http://purl.org/lscr#>
ncbigene: <https://www.ncbi.nlm.nih.gov/gene/>
ensg: <http://rdf.ebi.ac.uk/resource/ensembl/>
dcterms: <http://purl.org/dc/terms/>
efo: <http://www.ebi.ac.uk/efo/>