Q1-1-1:
  description: What is the expression level of the APOC1 gene?
  variables: [expression_level]
  parameters:
    gene_name: "APOC1"
  options:
    distinct: true

Q2-1-1:
  description: At which developmental stage is the APOC1 gene expressed?
  variables: [expression_condition_developmental_stage]
  parameters:
    gene_name: "APOC1"
  options:
    distinct: true