title: PubMed 
website: https://pubmed.ncbi.nlm.nih.gov/
description: PubMed comprises more than 30 million citations for biomedical literature from MEDLINE, life science journals,
tags: [ Others, Journal article/Report/Bibliography, ]
provider: National Institute of Technology and Evaluation
rdf_provider: Database Center for Life Science
rdf_creators:
  - name: Med2RDF project
    affiliation: http://med2rdf.org/
    version: release_20250630
issued: 2025-06-30
licenses:
  - https://www.nlm.nih.gov/databases/download.html
  - Source\: U.S. National Library of Medicine.
