Person:
  - $id: csv("id")
  - subject:
    - "http://example.org/ontology/person/$id"
  - objects:
    - id: $id
    - name:
      - $first_name: csv("first name")
      - $last_name: csv("last name")
      - $lang: csv("lang")
      - "$last_name $first_name"
      - lang($lang)
