rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
xsd:   <http://www.w3.org/2001/XMLSchema#>
dct:   <http://purl.org/dc/terms/>
skos:  <http://www.w3.org/2004/02/skos/core#>
foaf:  <http://xmlns.com/foaf/0.1/>
expsn: <http://example.org/ontology/person/>
