tcgao: <https://portal.gdc.cancer.gov/resources/ontology/>
tcgas: <https://portal.gdc.cancer.gov/resources/samples/>
tcgap: <https://portal.gdc.cancer.gov/projects/>
tcgac: <https://portal.gdc.cancer.gov/cases/>
tcgaf: <https://portal.gdc.cancer.gov/files/>
dct: <http://purl.org/dc/terms/>
