- HiNT:
    - source("HomoSapiens_binary_all_head101.txt")
    - $uniprot_a: tsv("Uniprot_A")
    - $uniprot_b: tsv("Uniprot_B")
    - subject:
        - "hnt:$uniprot_a-$uniprot_b"
    - objects:
        - data_source: "http://identifiers.org/HINT"
        - display_hame: "$uniprot_a-$uniprot_b"
        - evidence: "pint:evidence-pubmed_14667819-MI_0018-high-throughput"
        - name: "$uniprot_a-$uniprot_b"
        - pair0: "uni:$uniprot_a"
        - pair1: "uni:$uniprot_b"
        - network_variety: str("binary")
        - accuracy: str("high")
