- HiNT hnt:A0A024QYV7-Q00653:
  - a: bp3:MolecularInteraction
  - bp3:dataSource:
    - data_source: <http://identifiers.org/HINT>
  - bp3:displayName:
    - display_hame: '"A0A024QYV7-Q00653"^^xsd:string'
  - bp3:evidence+:
    - evidence: pint:evidence-pubmed_14743216-MI_0007-literature-curated
  - bp3:name:
    - name: '"A0A024QYV7-Q00653"^^xsd:string'
  - bp3:participant:
    - []:
      - obo:BFO_0000051:
        - pair0: uni:A0A024QYV7
#    - []:
#      - obo:BFO_0000051:
        - pair1: uni:Q00653
  - pint:networkVariety*:
    - network_variety: '"binary"^^xsd:string'
  - pint:accuracy?:
    - accuracy: '"low"^^xsd:string'
