rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dc: <http://purl.org/dc/elements/1.1/>
dct: <http://purl.org/dc/terms/>
skos: <http://www.w3.org/2004/02/skos/core#>
hnt: <http://purl.jp/10/hint/>
bp3: <http://www.biopax.org/release/biopax-level3.owl#>
pint: <http://purl.jp/10/pint/>
uni: <http://identifiers.org/uniprot/>
obo: <http://purl.obolibrary.org/obo/>
