title: PolyInfo BDG_S, ID definition
website: https://polymer.nims.go.jp/
description: NIMS polymer database PoLyInfo-Bio Linkage Project, Definition of biodegradation IDs and linking schemas for synthetic polymers.
tags: [Drug/Chemical]
provider: National Institute for Materials Science
creators:
  - name: Masashi Ishii
    affiliation: National Institute for Materials Science
version: 0.2
issued: 2020-02-06
license:
  - name: Creative Commons BY 4.0 International (CC BY 4.0)                             
  - url: https://creativecommons.org/licenses/by/4.0/
  - credit: CC BY 4.0 by National Institute for Materials Science (NIMS), Japan
