biodg: <http://dice.nims.go.jp/ontology/polymer-bio-ont/Biodeg#>
dc: <http://purl.org/dc/elements/1.1/>
dcterms: <http://purl.org/dc/terms/>
homo: <http://dice.nims.go.jp/ontology/PoLyInfo-ont/polyinfo-rdf/Homopolymer#>
obo: <http://purl.obolibrary.org/obo/>
owl: <http://www.w3.org/2002/07/owl#>
pobi: <http://dice.nims.go.jp/ontology/polymer-bio-ont/Schema#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
ref: <http://dice.nims.go.jp/ontology/polymer-bio-ont/Reference#>
taxonomy: <http://identifiers.org/taxonomy/>
wdt: <http://dice.nims.go.jp/ontology/polymer-bio-ont/Property#>
xsd: <http://www.w3.org/2001/XMLSchema#>
bibo: <http://purl.org/ontology/bibo/>
prism: <http://prismstandard.org/namespaces/basic/2.0/>
cu: <http://dice.nims.go.jp/ontology/PoLyInfo-ont/polyinfo-rdf/ConstitutionalUnit#>
pli: <http://dice.nims.go.jp/ontology/PoLyInfo-ont/Schema#>
sio: <http://semanticscience.org/resource/>
