sparql:
  description: NIMS polymer database PoLyInfo-Bio Linkage Project, Definition of biodegradation IDs and linking schemas for synthetic polymers
  variables: [BioDegradation, bio_degradation_label, has_participant, bio_degradation_id, bio_degradation_ref, Homopolymer, homopolymer_label, homopolymer_id, constitutional_unit, abbreviation, japanese_name, monomer_based_name, other_name, structure_based_name, ConstitutionalUnit, molecular_formula, molecular_weight, reaction_formula, smiles, constitutional_unit_id, MolecularFormula, MolecularWeight]

sparql2:
  description: NIMS polymer database PoLyInfo-Bio Linkage Project, Definition of biodegradation IDs and linking schemas for synthetic polymers
  variables: [BioDegradation, bio_degradation_label, bio_degradation_id, has_participant, bio_degradation_id, bio_degradation_ref, Homopolymer, homopolymer_id, abbreviation]
