title: DDBJ
website: http://www.ddbj.nig.ac.jp/index-e.html
description: Semantic Representation of DDBJ Annotated Sequence Records.
tags: [Genome, Gene, cDNA, Tag sequence (nucleic acid), Polymorphism, Other DNA, RNA, Sequence, Ontology/Terminology/Nomenclature, Others]
provider: National Institute of Genetics
creators:
  - name: Takatomo Fujisawa
    affiliation: National Institute of Genetics
  - name: Toshiaki Katayama
    affiliation: Database Center for Life Science
  - name: Yasukazu Nakamura
    affiliation: National Institute of Genetics
version: 105.0
issued: 2016-07-30
licenses:
  - Referred to in International Nucleotide Sequence Database Collaboration Policy (http://www.insdc.org/policy.html)
