title: MediaDive RDF
website: https://mediadive.dsmz.de/
description: MediaDive is the largest collection of cultivation media and growth conditions.
tags: [ Organism, Cell, Bioresource ]
provider: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
creators:
  - name: Julia Koblitz
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
version: 2024-10
issued: 2025-09-16
licenses:
  - Creative Commons Attribution 4.0 International (CC BY 4.0)
