title: MediaDive RDF
website: https://mediadive.dsmz.de/
description: MediaDive is the world's largest collection of cultivation media.
tags: [ Organism, Cell, Bioresource ]
provider: DSMZ
creators:
  - name: Julia Koblitz
    affiliation: DSMZ
version: release_20251016
issued: 2025-10-16
licenses:
  - Creative Commons Attribution 4.0 International (CC BY 4.0)
