dataset:
  name: ChEBI RDF
  description: "ChEBI (Chemical Entities of Biological Interest) is a freely accessible, ontology-driven database of \u2018small molecular entities\u2019, including their chemical structures, names, definitions, roles, and biological relationships. It provides manually curated, non-proprietary data supported by links to external resources and is widely used in chemical biology and bioinformatics"
