title: ChEBI RDF
website: https://www.ebi.ac.uk/chebi/
description: ChEBI (Chemical Entities of Biological Interest) is a freely accessible, ontology-driven database of ‘small molecular entities’, including their chemical structures, names, definitions, roles, and biological relationships. It provides manually curated, non-proprietary data supported by links to external resources and is widely used in chemical biology and bioinformatics
tags: [ Drug/Chemical ]
provider: European Bioinformatics Institute
creators:
  - name: European Bioinformatics Institute
version: Release 242
issued: 2025-06-02
licenses:
  - Creative Commons License (CC BY 4.0), and governed by EMBL-EBI’s terms of use and Long-term data preservation policy.
