endpoint:
  - https://rdfportal.org/primary/sparql
  - graph:
    - http://nanbyodata.jp/ontology/nando
another_endpoint:
  - https://togodx.dbcls.jp/human/sparql
  - graph:
    - http://rdf.integbio.jp/dataset/togosite/nando
