title: NANDO 
website: https://nanbyodata.jp/
description: NANDO is a vocabulary that systematically and comprehensively organizes designated intractable diseases and pediatric chronic specific diseases, including their subtypes. Each disease in NANDO is linked to Mondo (Monarch Disease Ontology), a disease vocabulary adopted by many international databases and systems, enabling integration with major international disease databases such as OMIM and Orphanet.
tags: [ Health/Disease, Tag sequence (nucleic acid), Ontology/ Terminology/Nomenclature ]
provider:
creators:
  - name: Kota Ninomiya
    affiliation: Graduate School of Pharmaceutical Sciences, The University of Tokyo / National Institute of Public Health
  - name: Terue Takatsuki
    affiliation: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems
  - name: Jae-Moon Shin
    affiliation: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems
  - name: Yasunori Yamamoto
    affiliation: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems
  - name: Toshiaki Katayama
    affiliation: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems
  - name: Hiroshi Masuya
    affiliation: Integrated Bioresource Information Division, BioResource Research Center, Riken
  - name: Shuichi Kawashima
    affiliation: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems
  - name: Soichi Ogishima
    affiliation: Advanced Research Center for Innovations in Next-Generation Medicine, Tohoku University
  - name: Atsuo Kikuchi
    affiliation: Graduate School of Medicine, Tohoku University
  - name: Toyofumi Fujiwara
    affiliation: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems
version: 2024-11-21
issued: 2023-11-21
licenses:
  - Attribution 4.0 International (CC BY 4.0) Database Center for Life Science
