title: NANDO 
website: https://nanbyodata.jp/
description: NANDOは指定難病制度および小児慢性特定疾病制度を対象に、難病名を体系的かつ網羅的に整理した語彙集です。NANDOの各疾患は、国際的に多くのデータベースやシステムで採用されている疾患語彙集Mondo（Monarch Disease Ontology）と紐づけられており、OMIMやOrphanetといった国外の主要疾患データベースとの連携が可能です。
tags: [ Health/Disease, Tag sequence (nucleic acid), Ontology/ Terminology/Nomenclature ]
provider:
creators:
  - name: 仁宮 洸太
    affiliation: 東京大学薬学系研究科，国立保健医療科学院
  - name: 高月 照江
    affiliation: 大学共同利用機関法人 情報・システム研究機構 データサイエンス共同利用基盤施設 ライフサイエンス統合データベースセンター
  - name: 申 在紋
    affiliation: 大学共同利用機関法人 情報・システム研究機構 データサイエンス共同利用基盤施設 ライフサイエンス統合データベースセンター
  - name: 山本 泰智
    affiliation: 大学共同利用機関法人 情報・システム研究機構 データサイエンス共同利用基盤施設 ライフサイエンス統合データベースセンター
  - name: 片山 俊明
    affiliation: 大学共同利用機関法人 情報・システム研究機構 データサイエンス共同利用基盤施設 ライフサイエンス統合データベースセンター
  - name: 桝屋 啓志
    affiliation: 理化学研究所 バイオリソース研究センター 統合情報開発室
  - name: 川島 秀一
    affiliation: 大学共同利用機関法人 情報・システム研究機構 データサイエンス共同利用基盤施設 ライフサイエンス統合データベースセンター
  - name: 荻島 創一
    affiliation: 東北大学 高等研究機構 未来型医療創成センター
  - name: 菊池 敦生
    affiliation: 東北大学 大学院医学系研究科
  - name: 藤原 豊史
    affiliation: 大学共同利用機関法人 情報・システム研究機構 データサイエンス共同利用基盤施設 ライフサイエンス統合データベースセンター
version: 2024-11-21
issued: 2024-11-21
licenses:
  - Attribution 4.0 International (CC BY 4.0) Database Center for Life Science
