title: Open TG-GATEs
website: http://toxico.nibiohn.go.jp/english/index.html
description: Open TG-GATEs is a public toxicogenomics database
tags: [Gene, Drug/Chemical, Health/Disease, Gene expression]
provider: National Institutes of Biomedical Innovation, Health and Nutrition
creators:
  - name: Yoshinobu Igarashi
    affiliation: National Institutes of Biomedical Innovation, Health and Nutrition
  - name: Shuichi Kawashima
    affiliation: Research Organization of Information and Systems Database Center for Life ScienceDatabase Center for Life Science
  - name: Daisuke Satoh
    affiliation: Level Five Co., Ltd.
  - name: Maori Ito
    affiliation: Pharmaceuticals and Medical Devices Agency
  - name: Chioko Nagao
    affiliation: National Institutes of Biomedical Innovation, Health and Nutrition
  - name: Kenji Mizuguchi
    affiliation: National Institutes of Biomedical Innovation, Health and Nutrition
version: 2017-03-17
issued: 2017-03-17
licenses:
  - http://toxico.nibiohn.go.jp/english/agreement.html
