affymetrix: <http://bio2rdf.org/affymetrix:>
taxonomy: <http://identifiers.org/taxonomy/>
probe: <http://purl.jp/bio/101/opentggates/Probe/>
array: <http://purl.jp/bio/101/opentggates/Array/>
chip: <http://purl.jp/bio/101/opentggates/Chip/>
unitset: <http://purl.jp/bio/101/opentggates/UnitSet/>
unitsetprofile: <http://purl.jp/bio/101/opentggates/UnitSetProfile/>
experimentset: <http://purl.jp/bio/101/opentggates/ExperimentSet/>
condition: <http://purl.jp/bio/101/opentggates/ExperimentalCondition/>
sample: <http://purl.jp/bio/101/opentggates/Sample/>
animal: <http://purl.jp/bio/101/opentggates/IndividualAnimal/>
compound: <http://purl.jp/bio/101/opentggates/ChemicalCompound/>
pathology: <http://purl.jp/bio/101/opentggates/Pathology/>
grade: <http://purl.jp/bio/101/opentggates/PathologicalGrade/>
findings: <http://purl.jp/bio/101/opentggates/PathologicalFindings/>
topography: <http://purl.jp/bio/101/opentggates/PathologicalTopography/
ontology: <http://purl.jp/bio/101/opentggates/ontology/>
slide: <http://virtualslide.nibiohn.go.jp/Authenticate3.php?image_id=>
uniprot: <http://purl.uniprot.org/uniprot/>
pubchem: <http://identifiers.org/pubchem.compound/>
kegg: <http://identifiers.org/kegg.drug/>
cas: <http://identifiers.org/cas/>
taxon: <http://identifiers.org/taxonomy/>
dct: <http://purl.org/dc/terms/>
sio: <http://semanticscience.org/resource/>
skos: <http://www.w3.org/2004/02/skos/core#>
foaf: <http://xmlns.com/foaf/0.1/>
obo: <http://purl.obolibrary.org/obo/>
ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>