title: NAROジーンバンク微生物バイオリソースデータセット
website: https://www.gene.affrc.go.jp/
description: 農研機構農業生物資源ジーンバンクが維持・管理・分譲している食料・農業に係る微生物遺伝資源のデータセット
tags: [ Organism, Bioresource ]
provider: 国立研究開発法人 農業・食品産業技術総合研究機構　遺伝資源研究センター
creators:
  - name: 田中 剛
    affiliation: 農研機構高度分析研究センター
  - name: 田中 聡
    affiliation: トランジット株式会社
version: 
issued: 2023-08-23
license:
  - name: Creative commons Attribution 4.0 International (CC BY 4.0)
  - url: https://creativecommons.org/licenses/by/4.0/
  - credit: Genebank Project, NARO licensed under CC 表示 - 継承 4.0 国際
