title: Dataset of NARO Genebank Microorganism Bioresource
website: https://www.gene.affrc.go.jp/
description: A dataset for microbes which are maintained, managed and provided from Genebank Project, NARO.
tags: [ Organism, Bioresource ]
provider: The Research Center of Genetic Resources, NARO (National Agriculture and Food Research Organization)
creators:
  - name: Tsuyoshi Tanaka
    affiliation: Research Center for Advanced Analysis, NARO
  - name: Satoshi Tanaka
    affiliation: Trans-IT Co., Ltd.
version: 
issued: 2023-08-23
license:
  - name: Creative commons Attribution 4.0 International (CC BY 4.0)
    url: https://creativecommons.org/licenses/by/4.0/
    credit: Genebank Project, NARO licensed under CC Atribution 4.0 International License.
