- Gene maff:101029:
  - a: mccv:MCCV_000001
  - dct:identifier:
    - entry_id: "MAFF_101029"
  - mccv:MCCV_000010:
    - gene_id: "MAFF 101029"
  - mccv:MCCV_000038:
    - organism_category: mccv:MCCV_000040
