maff: <https://www.gene.affrc.go.jp/databases-micro_search_detail.php?maff=>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
mccv: <http://purl.jp/bio/10/mccv#>
taxonomy: <http://identifiers.org/taxonomy/>
