title: BacDive RDF
website: https://bacdive.dsmz.de/
description: BacDive is the worldwide largest database for standardized bacterial information. Its mission is to mobilize and integrate research data on strain level from diverse sources and make it freely accessible. 
tags: [ Organism, Cell, Bioresource ]
provider: DSMZ
creators:
  - name: Julia Koblitz
    affiliation: DSMZ
version: release_20251016
issued: 2025-10-16
licenses:
  - Creative Commons Attribution 4.0 International (CC BY 4.0)
