title: BacDive RDF
website: https://bacdive.dsmz.de/
description: BacDive is the worldwide largest knowledgebase for standardized bacterial information. 
tags: [ Organism, Cell, Bioresource ]
provider: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
creators:
  - name: Julia Koblitz
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
  - name: Lorenz Christian Reimer
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
  - name: Joaquim Sardá Carbasse
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
  - name: Isabel Schober
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
version: 2024_12
issued: 2025-09-16
licenses:
  - Creative Commons Attribution 4.0 International (CC BY 4.0)
