- CellMotility cell_motility:50:
  - a:
    - schema:CellMotility
    - schema:MicrobialPhenotype
    - schema:Phenotype
  - rdfs:label:
    - cell_motility_label: false
  - schema:describesStrain: Strain
  - schema:hasPhenotypeInformation:
    - cell_motility_phyenotype_information: false
  - schema:hasReference:
    - reference: <https://purl.dsmz.de/bacdive/reference/23241>
  - schema:isMotile:
    - is_motile: false

- Strain strain:38:
  - a: schema:Strain
  - dct:description:
    - strain_description: "Belnapia moabensis CP2C is an aerobe, non-halophilic, mesophilic bacterium that forms circular colonies and was isolated from biological soil crusts."
  - rdfs:hasScientificName: 
    - scientific_name: "Belnapia moabensis Reddy et al. 2006" 
  - rdfs:label:
    - strain_label: "Belnapia moabensis 38"
  - schema:hasBacDiveID: 
    - strain_bacdive_id: 38
  - schema:hasClass: 
    - strain_class: "Alphaproteobacteria"
  - schema:hasDesignation:
    - strain_designation: "CP2C"
  - schema:hasDomain:
    - strain_domain: "Bacteria"
  - schema:hasFamily:
    - strain_family: "Acetobacteraceae"
  - schema:hasGenus:
    - strain_genus: "Belnapia"
  - schema:hasOrder:
    - strain_order: "Rhizobiales"
  - schema:hasPhylum:
    - strain_phylum: "Proteobacteria"
  - schema:hasReference:
    - strain_reference: <https://purl.dsmz.de/bacdive/reference/6490>
  - schema:hasSpecies:
    - strain_species: "Belnapia moabensis"
  - schema:hasSpeciesEpithet:
    - strain_species_epithet: "moabensis"
  - schema:hasStrainNames:
    - strain_names: "CP2C"
  - schema:hasStrainNumber:
    - strain_number: "DSM 16746, ATCC BAA-1043, CIP 109215"
  - schema:hasTaxID:
    - strain_taxid: 1121106
  - schema:hasTaxonomicRank:
    - strain_taxonomic_rank: "Acetobacteraceae"
  - schema:isTypeStrain:
    - strain_is_typestrain: true
  - schema:matchesTaxIDLevel:
    - strain_taxid_level: "species"
