rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dc: <http://purl.org/dc/elements/1.1/>
dct: <http://purl.org/dc/terms/>
skos: <http://www.w3.org/2004/02/skos/core#>
obo: <http://purl.obolibrary.org/obo/>
schema: <https://purl.dsmz.de/schema/>
strain: <https://purl.dsmz.de/bacdive/strain/>
reference: <https://purl.dsmz.de/bacdive/reference/>
mediadive: <https://purl.dsmz.de/mediadive/medium/>
cell_motility: <https://purl.dsmz.de/bacdive/cell_motility/>
