rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dc: <http://purl.org/dc/elements/1.1/>
dct: <http://purl.org/dc/terms/>
skos: <http://www.w3.org/2004/02/skos/core#>
obo: <http://purl.obolibrary.org/obo/>
schema: <https://purl.dsmz.de/schema/>
strain: <https://purl.dsmz.de/bacdive/strain/>
reference: <https://purl.dsmz.de/bacdive/reference/>
cell_shape: <https://purl.dsmz.de/bacdive/cell_shape/>
culture_medium: <https://purl.dsmz.de/mediadive/culture_medium/>
cell_motility: <https://purl.dsmz.de/bacdive/cell_motility/>
colony_morphology: <https://purl.dsmz.de/bacdive/colony_morphology/>
culture_collection_number: <https://purl.dsmz.de/bacdive/culture_collection_number/>
culture_ph: <https://purl.dsmz.de/bacdive/culture_pH/>
culture_temp: <https://purl.dsmz.de/bacdive/culture_temp/>
enzyme: <https://purl.dsmz.de/bacdive/enzyme/>
gc_content: <https://purl.dsmz.de/bacdive/gc_content/>
gram_stain: <https://purl.dsmz.de/bacdive/gram_stain/>
halophily: <https://purl.dsmz.de/bacdive/halophily/>
isolation: <https://purl.dsmz.de/bacdive/isolation/>
location: <https://purl.dsmz.de/bacdive/location/>
oxygen_tolerance: <https://purl.dsmz.de/bacdive/oxygen_tolerance/>
risk_assessment: <https://purl.dsmz.de/bacdive/risk_assessment/>
sequence_16s: <https://purl.dsmz.de/bacdive/sequence_16S/>
sequence_genomes: <https://purl.dsmz.de/bacdive/sequence_genomes/>
strain_designation: <https://purl.dsmz.de/bacdive/strain_designation/>
