title: GTDB
website: https://gtdb.ecogenomic.org/  
description: The Genome Taxonomy Database   
tags: ["taxonomy", "bacteria", "archaea"]
provider: The University of Queensland
creators:
  - name: Shuichi Kawashima  
    affiliation: https://dbcls.rois.ac.jp/ 
version: 2024-06-27
issued: 2024-06-27
licenses:
  - See licenses at https://gtdb.ecogenomic.org/licenses 

