- GtdbStrain gtdb:GB_GCA_000003645.1:
  - a: gtdb:Taxon
  - rdfs:subClassOf:
    - gtdb_species: GtdbSpecies
  - gtdb:rank:
    - rank_strain: gtdb:Strain
  - rdfs:seeAlso:
    - bioproject: bioproject:PRJNA29699
    - biosample: biosample:SAMN00727677
    - insdc_gca: gca:GCA_000003955.1
    - ncbi_taxonomy: taxid:526994
    - ncbi_genome: ncbigenome:GCA_000003955.1
  - gtdb:ambiguous_bases:
    - ambiguous_bases: 20
  - gtdb:checkm2_completeness:
    - checkm2_completeness: 100
  - gtdb:checkm2_contamination:
    - checkm2_contamination: 0
  - gtdb:checkm2_model:
    - checkm2_model: "Specific"
  - gtdb:checkm_completeness:
    - checkm_completeness: 99.07
  - gtdb:checkm_contamination:
    - checkm_contamination: 0.02
  - gtdb:checkm_marker_count:
    - checkm_marker_count: 1171
  - gtdb:checkm_marker_lineage:
    - checkm_marker_lineage: "g__Bacillus (UID902)"
  - gtdb:checkm_marker_set_count:
    - checkm_marker_set_count: 324
  - gtdb:checkm_strain_heterogeneity:
    - checkm_strain_heterogeneity: 0
  - gtdb:coding_bases:
    - coding_bases: 4406087
  - gtdb:coding_density:
    - coding_density: 83.6113269667772
  - gtdb:contig_count:
    - contig_count: 241
  - gtdb:gc_count:
    - gc_count: 1853735
  - gtdb:gc_percentage:
    - gc_percentage: 35.33882173743543
  - gtdb:genome_size:
    - genome_size: 5269725
  - gtdb:gtdb_genome_representative:
    - gtdb_genome_representative: "RS_GCF_001883995.1"
  - gtdb:gtdb_representative:
    - gtdb_representative: "f"
  - gtdb:gtdb_taxonomy:
    - gtdb_taxonomy: "d__Bacteria;p__Bacillota;c__Bacilli;o__Bacillales;f__Bacillaceae_G;g__Bacillus_A;s__Bacillus_Aparanthracis"
  - gtdb:gtdb_type_designation_ncbi_taxa:
    - gtdb_type_designation_ncbi_taxa: "not type material"
  - gtdb:gtdb_type_designation_ncbi_taxa_sources:
    - gtdb_type_designation_ncbi_taxa_sources: "none"
  - gtdb:gtdb_type_species_of_genus:
    - gtdb_type_species_of_genus: "f"
  - gtdb:l50_contigs:
    - l50_contigs: 28
  - gtdb:l50_scaffolds:
    - l50_scaffolds: 1
  - gtdb:longest_contig:
    - longest_contig: 182414
  - gtdb:longest_scaffold:
    - longest_scaffold: 5269725
  - gtdb:lsu_23s_contig_len:
    - lsu_23s_contig_len: 5269725
  - gtdb:lsu_23s_count:
    - lsu_23s_count: 7
  - gtdb:lsu_23s_length:
    - lsu_23s_length: 2245
  - gtdb:lsu_23s_query_id:
    - lsu_23s_query_id: "CM000714.1"
  - gtdb:lsu_5s_contig_len:
    - lsu_5s_contig_len: 5269725
  - gtdb:lsu_5s_count:
    - lsu_5s_count: 3
  - gtdb:lsu_5s_length:
    - lsu_5s_length: 116
  - gtdb:lsu_5s_query_id:
    - lsu_5s_query_id: "CM000714.1"
  - gtdb:lsu_silva_23s_blast_align_len:
    - lsu_silva_23s_blast_align_len: 2244
  - gtdb:lsu_silva_23s_blast_bitscore:
    - lsu_silva_23s_blast_bitscore: 4145
  - gtdb:lsu_silva_23s_blast_evalue:
    - lsu_silva_23s_blast_evalue: 0
  - gtdb:lsu_silva_23s_blast_perc_identity:
    - lsu_silva_23s_blast_perc_identity: 100
  - gtdb:lsu_silva_23s_blast_subject_id:
    - lsu_silva_23s_blast_subject_id: "CP023179.4713149.4716078"
  - gtdb:lsu_silva_23s_taxonomy:
    - lsu_silva_23s_taxonomy: "Bacteria;Firmicutes;Bacilli;Bacillales;Bacillaceae;Bacillus;Bacillus cereus"
  - gtdb:mean_contig_length:
    - mean_contig_length: 21766
  - gtdb:mean_scaffold_length:
    - mean_scaffold_length: 5269725
  - gtdb:mimag_high_quality:
    - mimag_high_quality: "f"
  - gtdb:mimag_low_quality:
    - mimag_low_quality: "f"
  - gtdb:mimag_medium_quality:
    - mimag_medium_quality: "t"
  - gtdb:n50_contigs:
    - n50_contigs: 53899
  - gtdb:n50_scaffolds:
    - n50_scaffolds: 5269725
  - gtdb:ncbi_assembly_level:
    - ncbi_assembly_level: "Chromosome"
  - gtdb:ncbi_assembly_name:
    - ncbi_assembly_name: "ASM364v1"
  - gtdb:ncbi_assembly_type:
    - ncbi_assembly_type: "na"
  - gtdb:ncbi_bioproject:
    - ncbi_bioproject: "PRJNA29657"
  - gtdb:ncbi_biosample:
    - ncbi_biosample: "SAMN00717290"
  - gtdb:ncbi_contig_count:
    - ncbi_contig_count: 241
  - gtdb:ncbi_contig_n50:
    - ncbi_contig_n50: 53899
  - gtdb:ncbi_country:
    - ncbi_country: "none"
  - gtdb:ncbi_date:
    - ncbi_date: '"2009-05-29"^^xsd:date'
  - gtdb:ncbi_genbank_assembly_accession:
    - ncbi_genbank_assembly_accession: "GCA_000003645.1"
  - gtdb:ncbi_genome_category:
    - ncbi_genome_category: "none"
  - gtdb:ncbi_genome_representation:
    - ncbi_genome_representation: "full"
  - gtdb:ncbi_isolate:
    - ncbi_isolate: "na"
  - gtdb:ncbi_isolation_source:
    - ncbi_isolation_source: "none"
  - gtdb:ncbi_lat_lon:
    - ncbi_lat_lon: "none"
  - gtdb:ncbi_molecule_count:
    - ncbi_molecule_count: 1
  - gtdb:ncbi_ncrna_count:
    - ncbi_ncrna_count: 0
  - gtdb:ncbi_organism_name:
    - ncbi_organism_name: "Bacillus cereus m1293"
  - gtdb:ncbi_protein_count:
    - ncbi_protein_count: "none"
  - gtdb:ncbi_refseq_category:
    - ncbi_refseq_category: "na"
  - gtdb:ncbi_rrna_count:
    - ncbi_rrna_count: 2
  - gtdb:ncbi_scaffold_count:
    - ncbi_scaffold_count: 1
  - gtdb:ncbi_scaffold_l50:
    - ncbi_scaffold_l50: 1
  - gtdb:ncbi_scaffold_n50:
    - ncbi_scaffold_n50: 5269725
  - gtdb:ncbi_scaffold_n75:
    - ncbi_scaffold_n75: 5269725
  - gtdb:ncbi_scaffold_n90:
    - ncbi_scaffold_n90: 5269725
  - gtdb:ncbi_seq_rel_date:
    - ncbi_seq_rel_date: '"2009-05-29"^^xsd:date'
  - gtdb:ncbi_spanned_gaps:
    - ncbi_spanned_gaps: 241
  - gtdb:ncbi_species_taxid:
    - ncbi_species_taxid: 1396
  - gtdb:ncbi_ssu_count:
    - ncbi_ssu_count: 0
  - gtdb:ncbi_strain_identifiers:
    - ncbi_strain_identifiers: "m1293"
  - gtdb:ncbi_submitter:
    - ncbi_submitter: "Naval Medical Research Center"
  - gtdb:ncbi_taxid:
    - ncbi_taxid: "526973"
  - gtdb:ncbi_taxonomy_string:
    - ncbi_taxonomy_string: "d__Bacteria;p__Bacillota;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus;s__Bacillus cereus"
  - gtdb:ncbi_taxonomy_unfiltered:
    - ncbi_taxonomy_unfiltered: "d__Bacteria;x__Terrabacteria group;p__Bacillota;c__Bacilli;o__Bacillales;f__Bacillaceae;g__Bacillus;x__Bacillus cereus group;s__Bacillus cereus;x__Bacillus cereus m1293"
  - gtdb:ncbi_total_gap_length:
    - ncbi_total_gap_length: 24100
  - gtdb:ncbi_total_length:
    - ncbi_total_length: 5269725
  - gtdb:ncbi_translation_table:
    - ncbi_translation_table: 11
  - gtdb:ncbi_trna_count:
    - ncbi_trna_count: 72
  - gtdb:ncbi_type_material_designation:
    - ncbi_type_material_designation: "na"
  - gtdb:ncbi_ungapped_length:
    - ncbi_ungapped_length: 5245625
  - gtdb:ncbi_unspanned_gaps:
    - ncbi_unspanned_gaps: 0
  - gtdb:ncbi_wgs_master:
    - ncbi_wgs_master: "ACLS00000000.1"
  - gtdb:protein_count:
    - protein_count: 5337
  - gtdb:scaffold_count:
    - scaffold_count: 1
  - gtdb:ssu_contig_len:
    - ssu_contig_len: 5269725
  - gtdb:ssu_count:
    - ssu_count: 5
  - gtdb:ssu_gg_blast_align_len:
    - ssu_gg_blast_align_len: "none"
  - gtdb:ssu_gg_blast_bitscore:
    - ssu_gg_blast_bitscore: "none"
  - gtdb:ssu_gg_blast_evalue:
    - ssu_gg_blast_evalue: "none"
  - gtdb:ssu_gg_blast_perc_identity:
    - ssu_gg_blast_perc_identity: "none"
  - gtdb:ssu_gg_blast_subject_id:
    - ssu_gg_blast_subject_id: "none"
  - gtdb:ssu_gg_taxonomy:
    - ssu_gg_taxonomy: "none"
  - gtdb:ssu_length:
    - ssu_length: 849
  - gtdb:ssu_query_id:
    - ssu_query_id: "CM000715.1"
  - gtdb:ssu_silva_blast_align_len:
    - ssu_silva_blast_align_len: 849
  - gtdb:ssu_silva_blast_bitscore:
    - ssu_silva_blast_bitscore: 1568
  - gtdb:ssu_silva_blast_evalue:
    - ssu_silva_blast_evalue: 0
  - gtdb:ssu_silva_blast_perc_identity:
    - ssu_silva_blast_perc_identity: 100
  - gtdb:ssu_silva_blast_subject_id:
    - ssu_silva_blast_subject_id: "CP023179.299511.301065"
  - gtdb:ssu_silva_taxonomy:
    - ssu_silva_taxonomy: "Bacteria;Firmicutes;Bacilli;Bacillales;Bacillaceae;Bacillus;Bacillus cereus"
  - gtdb:total_gap_length:
    - total_gap_length: 24100
  - gtdb:trna_aa_count:
    - trna_aa_count: 19
  - gtdb:trna_count:
    - trna_count: 72
  - gtdb:trna_selenocysteine_count:
    - trna_selenocysteine_count: 0

- GtdbSpecies gtdb:s__Bacillus_Aparanthracis:
  - a: gtdb:Taxon
  - rdfs:subClassOf:
    - gtdb_genus: GtdbGenus
  - gtdb:rank:
    - rank_species: gtdb:Species
  - skos:altLabel:
    - species_label: "Bacillus_A%20paranthracis"

- GtdbGenus gtdb:g__Bacillus_A:
  - a: gtdb:Taxon
  - rdfs:subClassOf:
    - gtdb_family: GtdbFamily
  - gtdb:rank:
    - rank_genus: gtdb:Genus
  - skos:altLabel:
    - genus_label: "g__Bacillus_A"

- GtdbsFamily gtdb:f__Bacillaceae_G:
  - a: gtdb:Taxon
  - rdfs:subClassOf:
    - gtdb_order: GtdbOrder
  - gtdb:rank:
    - rank_family: gtdb:Family
  - skos:altLabel:
    - family_label: "f__Bacillaceae_G"

- GtdbsOrder gtdb:o__Bacillales:
  - a: gtdb:Taxon
  - rdfs:subClassOf:
    - gtdb_class: GtdbClass
  - gtdb:rank:
    - rank_order: gtdb:Order
  - skos:altLabel:
    - order_label: "o__Bacillales"

- GtdbsClass gtdb:c__Bacilli:
  - a: gtdb:Taxon
  - rdfs:subClassOf:
    - gtdb_phylum: GtdbPhylum
  - gtdb:rank:
    - rank_class: gtdb:Class
  - skos:altLabel:
    - class_label: "c__Bacilli"

- GtdbsPhylum gtdb:p__Bacillota:
  - a: gtdb:Taxon
  - rdfs:subClassOf:
    - gtdb_domain: GtdbDomain
  - gtdb:rank:
    - rank_phylum: gtdb:Phylum
  - skos:altLabel:
    - phylum_label: "p__Bacillota"

- GtdbsDomain gtdb:d__Bacteria:
  - a: gtdb:Taxon
  - gtdb:rank:
    - rank_domain: gtdb:Domain
  - skos:altLabel:
    - domain_label: "d__Bacteria"

