rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
skos: <http://www.w3.org/2004/02/skos/core#>
dct: <http://purl.org/dc/terms/>
xsd: <http://www.w3.org/2001/XMLSchema#>
obo: <http://purl.obolibrary.org/obo/>
gtdb: <http://identifiers.org/gtdb/>
taxid: <http://identifiers.org/taxonomy/>
biosample: <http://identifiers.org/biosample/>
bioproject: <http://identifiers.org/bioproject/>
gca: <http://identifiers.org/insdc.gca/>
ncbigenome: <http://www.ncbi.nlm.nih.gov/datasets/genome/>
