HGNC:
  - $table("hgnc_id")
  - $downcase

gene_id: $table("symbol")

hgnc_id:
  - $table("hgnc_id")
  - $delete(/^HGNC:/)

description: $table("name")

location: $table("location")

UniProt:
  - $table("uniprot_ids")
  - $prepend("http://identifiers.org/uniprot/")

uniprot_id: $table("uniprot_ids")

PubMed:
  - $table("pubmed_id")
  - $split("|")
  - $prepend("http://identifiers.org/pubmed/")

pubmed_id:
  - $table("pubmed_id")
  - $split("|")
