endpoint: 
  - https://rdfportal.org/primary/sparql
  - graph:
    - http://rdfportal.org/dataset/hgnc
another_endpoint:
  - http://sparql.med2rdf.org/sparql
  - graph:
    - http://rdfportal.org/dataset/hgnc

