title: HGNC\: The resource for approved human gene nomenclature
website: https://www.genenames.org/
description: The HGNC is a resource for approved human gene nomenclature containing ~42000 gene
tags: [ Gene, Ontology/ Terminology/Nomenclature ]
provider: HUGO Gene Nomenclature Committee at the European Bioinformatics Institute
rdf_creators:
  - name: Med2RDF project
    affiliation: http://med2rdf.org/
version: release_20250630
issued: 2025-06-30
licenses:
  - https://www.genenames.org/about/
  - HUGO Gene Nomenclature Committee at the European Bioinformatics Institute
