endpoint: 
  - https://rdfportal.org/pdb/sparql
  - graph:
    - http://bmrbpub.protein.osaka-u.ac.jp/rdf/bmr
    - http://bmrbpub.protein.osaka-u.ac.jp/rdf/bms
    - http://bmrbpub.protein.osaka-u.ac.jp/schema/mmcifmr-star.owl
