title: BMRB/RDF
website: https://bmrbpub.pdbj.org/
description: BMRB/RDF is a translation of NMR-STAR data into RDF
tags: [ Protein, Other biomolecule, Others, Sequence, Structure ]
provider: Institute for Protein Research, Osaka University
creators:
  - name: Masashi Yokochi
    affiliation: Institute for Protein Research, Osaka University
  - name: Naohiro Kobayashi
    affiliation: Institute for Protein Research, Osaka University
  - name: Akira Kinjo
    affiliation: Institute for Protein Research, Osaka University
  - name: Takeshi Iwata
    affiliation: Institute for Protein Research, Osaka University
  - name: Haruki Nakamura
    affiliation: Institute for Protein Research, Osaka University
  - name: Chojiro Kojima
    affiliation: Institute for Protein Research, Osaka University
  - name: Toshimichi Fujiwara
    affiliation: Institute for Protein Research, Osaka University
  - name: Eldon L. Ulrich
    affiliation: Department of Biochemistry, University of Wisconsin-Madison
  - name: John L. Markley
    affiliation: Department of Biochemistry, University of Wisconsin-Madison
  - name: Yannis E. Ioannidis
    affiliation: Department of Informatics & Telecommunications, University of Athens
  - name: Miron Livny
    affiliation: Department of Computer Sciences, University of Wisconsin-Madison
version: 2023-04-29
issued: 2023-04-29
license:
  - name: Creative Commons Attribution 2.1 Japan (CC BY 2.1 JP)
  - url: https://creativecommons.org/licenses/by/2.1/jp/deed.en
  - credit: BMRB/RDF licensed under CC Attribution 2.1 Japan.
