if:    <http://med2rdf.org/if/800126_2590014F1021_1_015_1F#>
pi:    <http://med2rdf.org/pi/800126_2590014F1021_1_12#>
yjc:   <http://med2rdf.org/if/yjcode/>
pio:   <http://med2rdf.org/ontology/pio/>
ifo:   <http://med2rdf.org/ontology/ifo/>
rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
owl:   <http://www.w3.org/2002/07/owl#>
xsd:   <http://www.w3.org/2001/XMLSchema#>
dct:   <http://purl.org/dc/terms/>
skos:  <http://www.w3.org/2004/02/skos/core#>
foaf:  <http://xmlns.com/foaf/0.1/>
pav:   <http://purl.org/pav/>
olo:   <http://purl.org/ontology/olo/core#>
bibo:  <http://purl.org/ontology/bibo/>
prism: <http://prismstandard.org/namespaces/1.2/basic/>
pmid:  <http://rdf.ncbi.nlm.nih.gov/pubmed/>
