sparql:
  description: get InChI InChIkey for a compound
  variables: [Compound, iupac_inchi, InChIKey]
sparql_atc:
  description: get ATC code for a compound
  variables: [compound_with_inn, INN,  atc_code, atc_label, parent_atc]
