title: ChIP-Atlas RDF
website: https://chip-atlas.org/
description: ChIP-Atlas RDF developed by DBCLS
tags: []
provider: Database Center for Life Science
creators:
  - name: Tazro Ohta
    affiliation: Database Center for Life Science
  - name: Shuya Ikeda
    affiliation: Database Center for Life Science
  - name: Hirokazu Chiba
    affiliation: Database Center for Life Science
version: 20210827
issued: 2021-08-27
licenses:
  - Attribution 4.0 International (CC BY 4.0)
