regulation_pairs:
  description: Get regulation pairs
  variables: [PutativeRegulation, tg_tf, tg_target]

colocalization_pairs:
  description: Get colocalization pairs
  variables: [Colocalization, colo_tf, colo_partner_tf]
