- DbSNPValiation dbsnp:1000017372:
  - a:
    - m2r:Variation
    - obo:SO_0001483
  - dct:identifier:
    - identifier: "rs1000017372"
  - dbsnpo:is_created_in_build:
    - build: 150, 152
  - faldo:location:
    - []:
      - a:
        - faldo:Position
        - faldo:ExactPosition
      - faldo:reference:
        - reference: hco:1#GRCh37, refseq:NC_000001.10
      - faldo:position:
        - position: 746943
  - m2r:referenceAllele:
    - reference_allele: "A"
  - dct:hasPart:
    - allele: dbSNPAllele

- DbSNPAllele dbsnp:1000017372#G:
  - a: dbsnpo:Allele
  - m2r:alternativeAllele:
    - alternative_allele: "G"
  - dct:isPartOf:
    - valiation: dbsnp:1000017372
  - sio:SIO_000216:
    - []:
      - a: dct:Frequency
      - dct:source:
        - source: "TOPMED"
      - rdf:value:
        - frequency: 2.389e-5
    #- []:
    #  - a: dct:Frequency
    #  - dct:source:
    #    - source: "GnomAD"
    #  - rdf:value:
    #    - frequency: 3.236e-5
