title: MedGen
website: https://www.ncbi.nlm.nih.gov/medgen
description: MedGen organizes Information related to human medical genetics, such as attributes of conditions with a genetic contribution.
tags: [ Health/Disease, Ontology/Terminology/Nomenclature ]
provider: National Center for Biotechnology Information
creators:
  - name: Shuichi Kawashima
    affiliation: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems
  - name: Med2RDF project
version: Med2RDF version based on release_20230605
issued: 2023-06-05
licenses:
  - url: https://www.ncbi.nlm.nih.gov/home/about/policies/
  - Source: U.S. National Library of Medicine.
