title: MedGen
website: https://www.ncbi.nlm.nih.gov/medgen
description: MedGenは遺伝が寄与している病態の属性など、ヒト医学遺伝学に関連する情報を整理したデータベースです
tags: [ Health/Disease, Ontology/Terminology/Nomenclature ]
provider: National Center for Biotechnology Information
creators:
  - name: 川島 秀一
    affiliation: 大学共同利用機関法人 情報・システム研究機構 データサイエンス共同利用基盤施設 ライフサイエンス統合データベースセンター
  - name: Med2RDF project
version: Med2RDF version based on release_20230605
issued: 2023-06-05
licenses:
  - url: https://www.ncbi.nlm.nih.gov/home/about/policies/
  - Source: U.S. National Library of Medicine.
