- MedGen medgen:C0023467:
  - a: mo:ConceptID
  - mo:sty:
    - sty: sty:T191
  - dct:identifier:
    - identifier: "C0023467"
  - rdfs:label+:
    - label: "Acute myeloid leukemia"
  - skos:definition:
    - description: "CEBPA-associated familial acute myeloid leukemia (AML) is ..."
  - mo:disease_has_associated_gene+:
    - disease_has_associated_gene: MedGen  # medgen:C1334291
  - mo:expanded_form_of+:
    - expanded_form_of: MedGen             # medgen:C0023467 Acute myeloid leukemia
  - mo:has_alias+:
    - has_alias: MedGen                    # medgen:C0023467 Acute myeloid leukemia
  - mo:has_expanded_form+:
    - has_expanded_form: MedGen            # medgen:C0023467 Acute myeloid leukemia
  - mo:has_manifestation+:
    - has_manifestation: MedGen            # medgen:C0023467 Acute myeloid leukemia
  - mo:has_permuted_term+:
    - has_permuted_term: MedGen            # medgen:C0023467 Acute myeloid leukemia
  - mo:inverse_isa+:
    - inverse_isa: MedGen                  # medgen:C0023467 Acute myeloid leukemia
  - mo:isa+:
    - isa: MedGen                          # medgen:C0023467 Acute myeloid leukemia
  - mo:manifestation_of+:
    - manifestation_of: MedGen             # medgen:C1832442 Myelodysplasia, immunodeficiency, facial dysmorphism, short stature, and psychomotor delay
  - mo:mapped_from+:
    - mapped_from: MedGen                  # medgen:C1857225 Dohle bodies and leukemia
  - mo:undefined_relationship+:
    - undefined_relationship: MedGen       # medgen:C0023465 Acute monocytic leukemia
  - mo:alias_of:
      - alias_of: MedGen                   # medgen:C0023467 Acute myeloid leukemia
  - mo:permuted_term_of:
      - permuted_term_of: MedGen           # medgen:C0023467 Acute myeloid leukemia
  - mo:name:
    - []:
      - rdfs:label+:
        - name_label: "Acute myeloid leukemia"
      - dct:source:
        - name_source: mo:GTR
      - mo:suppress:
        - name_suppress: mo:N
  - mo:mgdef:
    - []:
      - mo:suppress:
        - suppress: mo:N
      - dct:source:
        - mgdef_source: mo:GeneReviews
      - skos:definition:
        - mgdef_definition: "CEBPA-associated familial acute myeloid leukemia (AML) is ..."
  - mo:mgconso+:
    - []:
      - mo:aui:
        - mgconso_aui: "AN1498512"
      - mo:ispref:
        - mgconso_ispref: medgen_med2rdf_ispref:Y
      - mo:stt:
        - mgconso_stt: mo:PF
      - mo:ts:
        - mgconso_ts: mo:P
      - rdfs:label+:
        - mgconso_label: "acute myeloid leukemia"
      - dct:source:
        - mgconso_source: mo:MONDO
      - mo:suppress:
        - mgconso_suppress: mo:N
  - mo:mgsat+:
    - []:
      - a: mo:MGSAT
      - mo:metaui:
        - metaui: "AN0169990"
      - mo:stype:
        - stype: "AUI"
      - dct:identifier:
        - mgsat_identifier: "ATN13265373"
      - dct:source:
        - mgsat_source: mo:GTR
      - rdf:value:
        - mgsat_value: "CN004254"
      - rdfs:label+:
        - mgsat_label: "NCBI_ALTERNATE_ID"
      - mo:suppress:
        - mgsat_suppress: mo:N

- MedGenMgrel:
  - a: mo:MGREL
  - dct:identifier:
    - mgrel_identifiler: "R71411348"
  - mo:cui1:
    - mgrel_cui1: MedGen    # medgen:C0023467
  - mo:aui1:
    - mgrel_aui1: "A12992602"
  - mo:cui2:
    - mgrel_cui2: MedGen    # medgen:C0023439
  - mo:aui2:
    - mgrel_aui2: "A0079307"
  - dct:source:
    - mgrel_source: mo:MSH
  - mo:suppress:
    - mgrel_suppress: mo:N
  - mo:rela:
    - mgrel_rela: "manifestation_of"

- MedGenUid medgen:9730:
  - a: mo:MGUID
  - dct:references+:
    - pubmed: pubmed:182115
  - rdfs:label:
    - medgen_uid_label: "Acute myeloid leukemia"
  - rdfs:seeAlso:
    - mengen_cid: MedGen    # medgen:C0023467 Acute myeloid leukemia

- NCBIGene ncbigene:221927:
  - a: mo:NCBIGene
  - ncbigeneo:taxid*:
    - taxonomy: taxonomy:9606
  - obo:RO_0003302:
    - medgen: MedGen
