- MedGen medgen:C0023467:
  - a: mo:ConceptID
  - mo:sty:
    - sty: sty:T191
  - dct:identifier:
    - identifier: "C0023467"
  - rdfs:label+:
    - label: "Acute myeloid leukemia"
  - skos:definition:
    - definition: "CEBPA-associated familial acute myeloid leukemia (AML) is defined as AML in which a heterozygous germline CEBPA pathogenic variant is present in a family in which multiple individuals have AML. In contrast, sporadic CEBPA-associated AML is defined as AML in which a CEBPA pathogenic variant(s) is identified in leukemic cells but not in the non-leukemic cells. Too few individuals with CEBPA-associated familial AML have been reported to be certain about the natural history of the disease. In the majority of individuals, the age of onset of familial AML appears to be earlier than sporadic AML; disease onset has been reported in persons as young as age 1.8 years and older than age 45 years. The prognosis of CEBPA-associated familial AML appears to be favorable compared with sporadic CEBPA-associated AML. Individuals with CEBPA-associated familial AML who have been cured of their initial disease may be at greater risk of developing additional independent leukemic episodes in addition to the risk of relapse due to preexisting clones."
  - mo:disease_has_associated_gene+:
    - disease_has_associated_gene: MedGen  # medgen:C1334291
  - mo:expanded_form_of+:
    - expanded_form_of: MedGen             # medgen:C0023467 Acute myeloid leukemia
  - mo:has_alias+:
    - has_alias: MedGen                    # medgen:C0023467 Acute myeloid leukemia
  - mo:has_expanded_form+:
    - has_expanded_form: MedGen            # medgen:C0023467 Acute myeloid leukemia
  - mo:has_manifestation+:
    - has_manifestation: MedGen            # medgen:C0023467 Acute myeloid leukemia
  - mo:has_permuted_term+:
    - has_permuted_term: MedGen            # medgen:C0023467 Acute myeloid leukemia
  - mo:inverse_isa+:
    - inverse_isa: MedGen                  # medgen:C0023467 Acute myeloid leukemia
  - mo:isa+:
    - isa: MedGen                          # medgen:C0023467 Acute myeloid leukemia
  - mo:manifestation_of+:
    - manifestation_of: MedGen             # medgen:C1832442 Myelodysplasia, immunodeficiency, facial dysmorphism, short stature, and psychomotor delay
  - mo:mapped_from+:
    - mapped_from: MedGen                  # medgen:C1857225 Dohle bodies and leukemia
  - mo:undefined_relationship+:
    - undefined_relationship: MedGen       # medgen:C0023465 Acute monocytic leukemia
  - mo:alias_of:
      - alias_of: MedGen                   # medgen:C0023467 Acute myeloid leukemia
  - mo:permuted_term_of:
      - permuted_term_of: MedGen           # medgen:C0023467 Acute myeloid leukemia
  - mo:name:
    - []:
      - rdfs:label+:
        - name_label: "Acute myeloid leukemia"
      - dct:source:
        - name_source: mo:GTR
      - mo:supress:
        - name_supress: mo:N
  - mo:mgdef:
    - []:
      - mo:supress:
        - supress: mo:N
      - dct:source:
        - mgdef_source: mo:GeneReviews
      - skos:definition:
        - mgdef_definition: "CEBPA-associated familial acute myeloid leukemia (AML) is defined as AML in which a heterozygous germline CEBPA pathogenic variant is present in a family in which multiple individuals have AML. In contrast, sporadic CEBPA-associated AML is defined as AML in which a CEBPA pathogenic variant(s) is identified in leukemic cells but not in the non-leukemic cells. Too few individuals with CEBPA-associated familial AML have been reported to be certain about the natural history of the disease. In the majority of individuals, the age of onset of familial AML appears to be earlier than sporadic AML; disease onset has been reported in persons as young as age 1.8 years and older than age 45 years. The prognosis of CEBPA-associated familial AML appears to be favorable compared with sporadic CEBPA-associated AML. Individuals with CEBPA-associated familial AML who have been cured of their initial disease may be at greater risk of developing additional independent leukemic episodes in addition to the risk of relapse due to preexisting clones."
  - mo:mgconso+:
    - []:
      - mo:aui:
        - mgconso_aui: "AN1498512"
      - mo:ispref:
        - mgconso_ispref: medgen_med2rdf_ispref:Y
      - mo:stt:
        - mgconso_stt: mo:PF
      - mo:ts:
        - mgconso_ts: mo:P
      - rdfs:label+:
        - mgconso_label: "acute myeloid leukemia"
      - dct:source:
        - mgconso_source: mo:MONDO
      - mo:supress:
        - mgconso_supress: mo:N
  - mo:mgsat+:
    - []:
      - a: mo:MGSAT
      - mo:metaui:
        - metaui: "AN0169990"
      - mo:stype:
        - stype: "AUI"
      - dct:identifier:
        - mgsat_identifier: "ATN13265373"
      - dct:source:
        - mgsat_source: mo:GTR
      - rdf:value:
        - mgsat_value: "CN004254"
      - rdfs:label+:
        - metaui_label: "NCBI_ALTERNATE_ID"
      - mo:supress:
        - mgsat_supress: mo:N

- MedGenMgrel:
  - a: mo:MGREL
  - dct:identifier:
    - mgrel_identifiler: "R71411348"
  - mo:cui1:
    - mgrel_cui1: MedGen    # medgen:C0023467
  - mo:aui1:
    - mgrel_aui1: "A12992602"
  - mo:cui2:
    - mgrel_cui2: MedGen    # medgen:C0023439
  - mo:aui2:
    - mgrel_aui2: "A0079307"
  - dct:source:
    - mgrel_source: mo:MSH
  - mo:supress:
    - mgrel_supress: mo:N
  - mo:rela:
    - mgrel_rela: "manifestation_of"

- MedGenUid medgen:9730:
  - dct:references+:
    - pubmed: pubmed:182115
  - rdfs:label:
    - medgen_uid_label: "Acute myeloid leukemia"
  - rdfs:seeAlso:
    - mengen_cid: MedGen    # medgen:C0023467 Acute myeloid leukemia

- NCBIGene ncbigene:221927:
  - ncbigeneo:taxid:
    - taxonomy: taxonomy:9606
  - obo:RO_0003302:
    - medgen: medgen:C3281029