- Medgen medgen:C0023467:
  - a: mo:ConceptID
  - mo:sty:
    - sty: sty:T191
  - dct:identifier:
    - identifier: "C0023467"
  - rdfs:label+:
    - label: "Acute myeloid leukemia"
  - skos:definition:
    - definition: "CEBPA-associated familial acute myeloid leukemia (AML) is defined as AML in which a heterozygous germline CEBPA pathogenic variant is present in a family in which multiple individuals have AML. In contrast, sporadic CEBPA-associated AML is defined as AML in which a CEBPA pathogenic variant(s) is identified in leukemic cells but not in the non-leukemic cells. Too few individuals with CEBPA-associated familial AML have been reported to be certain about the natural history of the disease. In the majority of individuals, the age of onset of familial AML appears to be earlier than sporadic AML; disease onset has been reported in persons as young as age 1.8 years and older than age 45 years. The prognosis of CEBPA-associated familial AML appears to be favorable compared with sporadic CEBPA-associated AML. Individuals with CEBPA-associated familial AML who have been cured of their initial disease may be at greater risk of developing additional independent leukemic episodes in addition to the risk of relapse due to preexisting clones."
  - mo:disease_has_associated_gene+:
    - disease_has_associated_gene: medgen:C1334291
  - mo:expanded_form_of+:
    - expanded_form_of: medgen:C0023467 # Acute myeloid leukemia
  - mo:has_alias+:
    - has_alias: medgen:C0023467 # Acute myeloid leukemia
  - mo:has_expanded_form+:
    - has_expanded_form: medgen:C0023467 # Acute myeloid leukemia
  - mo:has_manifestation+:
    - has_manifestation: medgen:C0023467 # Acute myeloid leukemia
  - mo:has_permuted_term+:
    - has_permuted_term: medgen:C0023467 # Acute myeloid leukemia
  - mo:inverse_isa+:
    - inverse_isa: medgen:C0023467 # Acute myeloid leukemia
  - mo:isa+:
    - isa: medgen:C0023467 # Acute myeloid leukemia
  - mo:manifestation_of+:
    - manifestation_of: medgen:C1832442 # Myelodysplasia, immunodeficiency, facial dysmorphism, short stature, and psychomotor delay
  - mo:mapped_from+:
    - mapped_from: medgen:C1857225 # Dohle bodies and leukemia
  - mo:undefined_relationship+:
    - undefined_relationship: medgen:C0023465 # Acute monocytic leukemia
  - mo:name:
    - []:
      - a: mo:MGNAME
      - rdfs:label+:
        - name_label: "Acute myeloid leukemia"
  - mo:mgdef:
    - []:
      - a: mo:MGDEF
      - mo:supress:
        - supress: mo:N
      - dct:source:
        - mgdef_source: mo:GeneReviews
      - skos:definition:
        - mgdef_definition: "CEBPA-associated familial acute myeloid leukemia (AML) is defined as AML in which a heterozygous germline CEBPA pathogenic variant is present in a family in which multiple individuals have AML. In contrast, sporadic CEBPA-associated AML is defined as AML in which a CEBPA pathogenic variant(s) is identified in leukemic cells but not in the non-leukemic cells. Too few individuals with CEBPA-associated familial AML have been reported to be certain about the natural history of the disease. In the majority of individuals, the age of onset of familial AML appears to be earlier than sporadic AML; disease onset has been reported in persons as young as age 1.8 years and older than age 45 years. The prognosis of CEBPA-associated familial AML appears to be favorable compared with sporadic CEBPA-associated AML. Individuals with CEBPA-associated familial AML who have been cured of their initial disease may be at greater risk of developing additional independent leukemic episodes in addition to the risk of relapse due to preexisting clones."
  - mo:mgconso+:
    - []:
      - a: mo:MGCONSO
      - mo:aui:
        - mgconso_aui_gtr: "AN0169990"
      - mo:ispref:
        - mgconso_ispref_gtr: medgen_med2rdf_ispref:Y
      - mo:stt:
        - mgconso_stt_gtr: mo:PF
      - mo:ts:
        - mgconso_ts: mo:P
      - rdfs:label+:
        - mgconso_label_gtr: "Acute myeloid leukemia"
      - dct:source:
        - mgconso_source_gtr: mo:GTR
    - []:
      - a: mo:MGCONSO
      - mo:aui:
        - mgconso_aui_hp: "AN0526903"
      - mo:ispref:
        - mgconso_ispref_hp: medgen_med2rdf_ispref:Y
      - mo:stt:
        - mgconso_stt_hp: mo:VO
      - mo:ts:
        - mgconso_ts_hp: mo:P
      - rdfs:label+:
        - mgconso_label_hp: "Acute myeloblastic leukemia"
      - dct:source:
        - mgconso_source_hp: mo:HPO
    - []:
      - a: mo:MGCONSO
      - mo:aui:
        - mgconso_aui_mondo: "AN1498512"
      - mo:ispref:
        - mgconso_ispref_mondo: medgen_med2rdf_ispref:Y
      - mo:stt:
        - mgconso_stt_mondo: mo:PF
      - mo:ts:
        - mgconso_ts_mondo: mo:P
      - rdfs:label+:
        - mgconso_label_mondo: "acute myeloid leukemia"
      - dct:source:
        - mgconso_source_mondo: mo:MONDO
    - []:
      - a: mo:MGCONSO
      - mo:aui:
        - mgconso_aui_mesh: "A0019606"
      - mo:ispref:
        - mgconso_ispref_mesh: medgen_med2rdf_ispref:Y
      - mo:stt:
        - mgconso_stt_mesh: mo:VW
      - mo:ts:
        - mgconso_ts_mesh: mo:S
      - rdfs:label+:
        - mgconso_label_mesh: "acute myeloid leukemia"
      - dct:source:
        - mgconso_source_mesh: mo:MSH
    - []:
      - a: mo:MGCONSO
      - mo:aui:
        - mgconso_aui_nci: "A17681474"
      - mo:ispref:
        - mgconso_ispref_nci: medgen_med2rdf_ispref:Y
      - mo:stt:
        - mgconso_stt_nci: mo:PF
      - mo:ts:
        - mgconso_ts_nci: mo:S
      - rdfs:label+:
        - mgconso_label_nci: "Acute Myeloid Leukemia Not Otherwise Specified"
      - dct:source:
        - mgconso_source_nci: mo:NCI
    - []:
      - a: mo:MGCONSO
      - mo:aui:
        - mgconso_aui_omim: "A11930044"
      - mo:ispref:
        - mgconso_ispref_omim: medgen_med2rdf_ispref:N
      - mo:stt:
        - mgconso_stt_omim: mo:VCW
      - mo:ts:
        - mgconso_ts_omim: mo:S
      - rdfs:label+:
        - mgconso_label_omim: "Acute myeloid leukemia"
      - dct:source:
        - mgconso_source_omim: mo:OMIM
    - []:
      - a: mo:MGCONSO
      - mo:aui:
        - mgconso_aui_ordo: "AN0468386"
      - mo:ispref:
        - mgconso_ispref_ordo: medgen_med2rdf_ispref:Y
      - mo:stt:
        - mgconso_stt_ordo: mo:VO
      - mo:ts:
        - mgconso_ts_ordo: mo:P
      - rdfs:label+:
        - mgconso_label_ordo: "AML"
      - dct:source:
        - mgconso_source_ordo: mo:ORDO
    - []:
      - a: mo:MGCONSO
      - mo:aui:
        - mgconso_aui_snomedct: "A17320427"
      - mo:ispref:
        - mgconso_ispref_snomedct: medgen_med2rdf_ispref:N
      - mo:stt:
        - mgconso_stt_snomedct: mo:VCW
      - mo:ts:
        - mgconso_ts_snomedct: mo:P
      - rdfs:label+:
        - mgconso_label_snomedct: "Acute myelocytic leukemia"
      - dct:source:
        - mgconso_source_snomedct: mo:SNOMEDCT_US
  - mo:mgsat+:
    - []:
      - a: mo:MGSAT
      - mo:metaui:
        - metaui: "AN0169990"
      - mo:stype:
        - stype: "AUI"
      - dct:identifier:
        - mgsat_identifier: "ATN13265373"
      - dct:source:
        - mgsat_source: mo:GTR
      - rdf:value:
        - mgsat_value: "CN004254"
      - rdfs:label+:
        - metaui_label: "NCBI_ALTERNATE_ID"
- []:
  - a: mo:MGREL
  - dct:identifier:
    - mgrel_identifiler: "R113838251"
  - mo:cui1:
    - mgrel_cui1: medgen:C0000731
  - mo:aui1:
    - mgrel_aui1: "A11974505"
  - mo:cui2:
    - mgrel_cui2: medgen:C1848586
  - mo:aui2:
    - mgrel_aui2: "A12031072"
  - mo:rela:
    - mgrel_rela: "has_manifestation"
  - dct:source:
    - mgrel_source: mo:OMIM
  - mo:supress:
    - mgrel_supress: mo:N
