title: GGDonto
website: http://acgg.asia/db/diseases/
description: GGDonto is the Ontology of the Genetic Diseases related to the Glycan Metabolism. GGDonto describes the knowledge about Congenital Disorders of Glycosylation (CDG) and Lysosomal Storage Diseases (LSD). GGDonto provides the information on 120 genetic diseases of the glycan synthesis and the degradation and their causative genes.
tags: [Other biomolecule, Health/Disease, Gene, Ontology/Terminology/Nomenclature, Interaction/Pathway]
provider: Glycoscience and Glycotechnology Research Group, Biotechnology Research Institute for Drug Discovery, National Institute of Advanced Industrial Science and Technology (AIST)
creators:
  - name: Hisashi Narimatsu
    affiliation: Glycoscience and Glycotechnology Research Group, Biotechnology Research Institute for Drug Discovery, National Institute of Advanced Industrial Science and Technology (AIST)
  - name: Toshihide Shikanai
    affiliation: Glycoscience and Glycotechnology Research Group, Biotechnology Research Institute for Drug Discovery, National Institute of Advanced Industrial Science and Technology (AIST)
  - name: Elena Solovieva
    affiliation: Glycoscience and Glycotechnology Research Group, Biotechnology Research Institute for Drug Discovery, National Institute of Advanced Industrial Science and Technology (AIST)
  - name: Noriaki Fujita
    affiliation: Glycoscience and Glycotechnology Research Group, Biotechnology Research Institute for Drug Discovery, National Institute of Advanced Industrial Science and Technology (AIST)
version: v.1.0
issued: 2017-01-25
licenses:
  - Attribution-NonCommercial-ShareAlike 2.1 Japan (CC BY-NC-SA 2.1) 
