rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dct: <http://purl.org/dc/terms/>
faldo: <http://biohackathon.org/resource/faldo#>
gvo: <http://genome-variation.org/resource#>
vcf: <http://genome-variation.org/resource/vcf#>
vep: <http://genome-variation.org/resource/vep#>
so: <http://purl.obolibrary.org/obo/SO_>
ensg: <http://rdf.ebi.ac.uk/resource/ensembl/>
mgi: <http://identifiers.org/mgi/>
