dataset:
  name: dbVar
  description: "dbVar is NCBI's database of human genomic Structural Variation \u2014 large variants >50 bp including insertions, deletions, duplications, inversions, mobile elements, translocations, and complex variants"
