hco: <http://identifiers.org/hco/11#>
taxon: <http://identifiers.org/taxonomy/>
dbvar_vcall: <http://med2rdf.org/dbvar/variant_call/>
dbvar_vcall_essv1_grch37: <http://med2rdf.org/dbvar/variant_call/essv1/position/GRCh37/>
dbvar_vcall_essv1_grch37_chr9: <http://med2rdf.org/dbvar/variant_call/essv1/position/GRCh37/NC_000011.9/>
dbvar_vcall_essv1_grch37_chr9_begin: <http://med2rdf.org/dbvar/variant_call/essv1/position/GRCh37/NC_000011.9/begin#>
dbvar_vcall_essv1_grch37_chr7_end: <http://med2rdf.org/dbvar/variant_call/essv1/position/GRCh37/NC_000011.9/end#>
dbvar: <http://med2rdf.org/dbvar/variation/>
med2rdf: <http://med2rdf.org/ontology/med2rdf#>
purl_dbvar: <http://purl.jp/bio/10/dbvar/>
faldo: <http://biohackathon.org/resource/faldo#>
obo: <http://purl.obolibrary.org/obo/>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>