LDRelation:
  - source("PASS.autosome_PAR_ploidy_2.biallelic.chr22.tsv") 
  - variables:
    - snv1:
      - csv("SNPA1")
    - snv2: 
      - csv("SNPB")
    - r2_value:
      - csv("R2")
    - dprime_value:
      - csv("Dprime")