clinvar: <http://ncbi.nlm.nih.gov/clinvar/variation/>
dbsnp: <http://identifiers.org/dbsnp/>
dc: <http://purl.org/dc/elements/1.1/>
dct: <http://purl.org/dc/terms/>
ensembl: <http://rdf.ebi.ac.uk/terms/ensembl/>
ensembl_id: <http://identifiers.org/ensembl/>
ensg: <http://rdf.ebi.ac.uk/resource/ensembl/>
enst: <http://rdf.ebi.ac.uk/resource/ensembl.transcript/>
faldo: <http://biohackathon.org/resource/faldo#>
foaf: <http://xmlns.com/foaf/0.1/>
gvo: <http://genome-variation.org/resource#> .
hco: <http://identifiers.org/hco/>
hgnc: <http://identifiers.org/hgnc/>
jaxmice: <https://identifiers.org/jaxmice/>
mco: <http://identifiers.org/mco/>
obo: <http://purl.obolibrary.org/obo/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
sio: <http://semanticscience.org/resource/>
so: <http://purl.obolibrary.org/obo/so#>
tgvo: <http://togovar.org/vocabulary/>