dataset:
  name: 'SSBD: Meta-information of quantitative data and microscopy images'
  description: Meta-information of quantitative data and datasets of microscopy images provided from SSBD database
