title: >
    SSBD: Meta-information of quantitative data and microscopy images
website: http://ssbd.qbic.riken.jp/
description: Meta-information of quantitative data and datasets of microscopy images provided from SSBD database
tags: [Cell, Organism, Other biomolecule, Image/Movie, Gene expression, Others]
provider:
creators:
  - name: Yukako Tohsato
    affiliation: Osaka Electro-Communication University, Department of Engineering Informatics
  - name: Koji Kyoda
    affiliation: RIKEN Quantitative Biology Center, Laboratory for Developmental Dynamics
  - name: Kenneth H. L. Ho
    affiliation: RIKEN Quantitative Biology Center, Laboratory for Developmental Dynamics
  - name: Shuichi Onami
    affiliation: RIKEN Quantitative Biology Center, Laboratory for Developmental Dynamics
version: SSBD31_20171218 release 20180324
issued: 2018-03-24
licenses:
  - Creative Commons Attribution-ShareAlike 2.1 Japan (CC BY-SA 2.1 JP)
