ccbyncsa40: <http://creativecommons.org/licenses/by-nc-sa/4.0/>
ssbd: <http://metadb.riken.jp/db/SSBD/>
ssbdo: <http://metadb.riken.jp/ontology/SSBD/>
pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
obo: <http://purl.obolibrary.org/obo/>
dct: <http://purl.org/dc/terms/>
sio: <http://semanticscience.org/resource/>
vcard: <http://www.w3.org/2006/vcard/ns#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>