dataset:
  name: Mondo Disease Ontology
  description: The Mondo Disease Ontology (MONDO) is a harmonized, logic-based disease classification that unifies and standardizes terminology across diverse medical sources by integrating mappings (with precise semantics) from databases such as OMIM, Orphanet, SNOMED CT, and ICD
