title: Mondo Disease Ontology
website: https://mondo.monarchinitiative.org/
description: The Mondo Disease Ontology (MONDO) is a harmonized, logic-based disease classification that unifies and standardizes terminology across diverse medical sources by integrating mappings (with precise semantics) from databases such as OMIM, Orphanet, SNOMED CT, and ICD 
tags: [Health/Disease, Ontology/ Terminology/Nomenclature]
provider: 
creators:
  - name: 
version: v2025-05-06
issued: 2025-05-28
licenses:
  - Creative Commons License (CC BY 4.0)
