title: Metadata of JCM resources
website: http://jcm.brc.riken.jp/ja/
description: A RDF-based meta-database of microbial strains used in various researches such as biology, environment and human health as bioresources. Microbial strains are available from Japan Collection of Microorganisms (JCM) in RIKEN BioResource Center. Please visit data browser at http://metadb.riken.jp/metadb/db/rikenbrc_jcm_microbe
tags: [Organism, Bioresource]
provider: RIKEN
creators:
  - name: Terue Takatsuki
    affiliation: Database Center for Life Science
  - name: Hiroshi Masuya
    affiliation: RIKEN Bioresource research center
  - name: Moriya Ohkuma
    affiliation: Microbe Division, RIKEN Bioresource research center
version: 2019-06-04
issued: 2019-06-04
licenses:
  - Attribution 4.0 International (CC BY 4.0) 
