atcc: <http://identifiers.org/atcc/>
ncbitaxnomy: <http://identifiers.org/taxonomy/>
jcm: <http://metadb.riken.jp/db/rikenbrc_jcm_microbe/>
gm: <http://purl.jp/bio/10/gm/>
mccv: <http://purl.jp/bio/10/mccv#>
mpo: <http://purl.jp/bio/10/mpo/>
pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
rikenJCMimage: <http://www.jcm.riken.jp/JCM/img/>
rikenJCM: <http://www.jcm.riken.jp/cgi-bin/jcm/>
wfcc: <http://www.wfcc.info/ccinfo/collection/by_id/>
insdc: <https://identifiers.org/insdc:>
obo: <http://purl.obolibrary.org/obo/>
dct: <http://purl.org/dc/terms/>
sio: <http://semanticscience.org/resource/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
foaf: <http://xmlns.com/foaf/0.1/>
meo: <http://purl.jp/bio/11/meo/>
pdo: <http://purl.jp/bio/11/pdo/>