- CCLE:
    - source("Cell_lines_annotations_20181226.txt")
    - subject:
        - tsv("CCLE_ID")
        - prepend("cclec:")
    - objects:
        - ccle_label:
            - tsv("Name")
            - skip("NA")
        - hist_primary:
            - tsv("Histology")
            - skip("NA")
        - hist_secondary:
            - tsv("Hist_Subtype1")
            - skip("NA", "NS")
        - site_primary:
            - tsv("Site_Primary")
            - skip("NA")
        - gender:
            - switch("Gender"):
                "male": obo:PATO_0000384
                "female": obo:PATO_0000383

        # [] a m2r:Assay
        # 取得方法不明
        # - assay_gene: ccleg:ENSG00000000003
        - assay_sample:
            - tsv("CCLE_ID")
            - prepend("cclec:")
        # 取得方法不明
        # - exp_val: # for test
        #     - str("12.26012")
        #     - to_float

- EnsemblGene:
    - source("CCLE_DepMap_18q3_RNAseq_RPKM_20180718_head1001.txt")
    # - source("CCLE_DepMap_18q3_RNAseq_RPKM_20180718.txt")
    - subject:
        - tsv("Name")
        - delete(/\.\d+$/)
        - prepend("ccleg:")
    - objects:
        - ensg_label: tsv("Description")
        - ensg_see_also:
            - tsv("Name")
            - delete(/\.\d+$/)
            - prepend("http://rdf.ebi.ac.uk/resource/ensembl/")

- EntrezGene:
    - source("CCLE_DepMap_18q3_maf_20180718_head1001.txt")
    # - source("CCLE_DepMap_18q3_maf_20180718.txt")
    - subject:
        - tsv("Hugo_Symbol")
        - prepend("ccleg:")
    - objects:
        - entrez_gene_label: tsv("Hugo_Symbol")
        - entrez_gene_id:
            - tsv("Entrez_Gene_Id")
            - skip("0")

- Variation:
    - source("CCLE_DepMap_18q3_maf_20180718_head1001.txt")
    # - source("CCLE_DepMap_18q3_maf_20180718.txt")
    - $chr: tsv("Chromosome")
    - $ncbi_build: tsv("NCBI_Build")
    - $gene: tsv("Hugo_Symbol")
    - $label:
          - tsv("Protein_Change")
          - delete(/^p\./)
    # - subject: "cclev:$gene-$label"
    - subject:
        # - tsv("Protein_Change")
        # - delete(/^p\./)
        - $label
        - replace('>', '_')
        - prepend("cclev:$gene-")
    - objects:
        - variation_label: $label
        - alternative_allele: tsv("Tumor_Seq_Allele1")
        - variant_gene: "ccleg:$gene"
        - reference_allele: tsv("Reference_Allele")
        - variant_consequence:
            - switch("Variant_Classification"):
                "Missense_Mutation": sio:SO_0001583
                "Silent": sio:SO_0001819
                "Splice_Site": sio:SO_0001630
                "De_novo_Start_OutOfFrame": sio:SO_0001589
                "Nonsense_Mutation": sio:SO_0001587
                "Nonstop_Mutation": sio:SO_0001578
                "Start_Codon_SNP": sio:SO_0002012
        - variant_type: tsv("Variant_Type")
        - codon_change: tsv("Codon_Change")
        - dna_change: tsv("cDNA_Change")
        - protein_change: tsv("Protein_Change")

        # Transcript
        - variant_transcript_label: tsv("Annotation_Transcript")
        - variant_transcript_gene:
            - tsv("Hugo_Symbol")
            - prepend("ccleg:")
        - variant_transcript_see_also:
            - tsv("Annotation_Transcript")
            - delete(/\.\d+$/)
            - prepend("transcript:")
        - snp_start_pos: tsv("Start_position")
        - snp_start_reference: "hco:$chr#GRCh$ncbi_build"
        - snp_end_pos: tsv("End_position")
        - snp_end_reference: "hco:$chr#GRCh$ncbi_build"
