rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
ccle: <http://med2rdf.org/ontology/ccle#>
cclec: <https://portals.broadinstitute.org/ccle/page?cell_line=>
ccleg: <https://portals.broadinstitute.org/ccle/page?gene=>
faldo: <http://biohackathon.org/resource/faldo#>
hco: <http://identifiers.org/hco/>
m2r: <http://med2rdf.org/ontology#>
obo: <http://purl.obolibrary.org/obo/>
sio: <http://semanticscience.org/resource/>
transcript: <http://rdf.ebi.ac.uk/resource/ensembl.transcript/>
