Person:
  - root("/persons/person")
  - $id: xml("@id")
  - "http://example.org/ontology/person/$id"
  - variables:
    - id: $id
    - name:
      - $first_name: xml("first_name/text()")
      - $last_name: xml("last_name/text()")
      - "$first_name $last_name"
