title: ClinVar RDF
website: https://www.ncbi.nlm.nih.gov/clinvar/
description: ClinVar is a freely available archive describing relationships between medically important variants and phenotypes.
tags: [ Polymorphism, Health/Disease, Sequence ]
provider: National Center for Biotechnology Information
creators: National Center for Biotechnology Information
rdf_creators:
  - name: Med2RDF project
    affiliation: http://med2rdf.org/
version: release_20250623
issued: 2025-06-23
licenses:
  - https://www.ncbi.nlm.nih.gov/clinvar/docs/maintenance_use/
  - Source\: U.S. National Library of Medicine.
