idcv: <http://identifiers.org/clinvar.record:>
refseq: <http://identifiers.org/refseq/>
med2rdf: <http://med2rdf.org/ontology/med2rdf#>
clinvar: <http://ncbi.nlm.nih.gov/clinvar/variation/>
ncbigene: <http://ncbi.nlm.nih.gov/gene/>
medgen: <http://ncbi.nlm.nih.gov/medgen/>
omim: <http://omim.org/entry/>
cvo: <http://purl.jp/bio/10/clinvar/>
bibo: <http://purl.org/ontology/bibo/>
faldo: <http://biohackathon.org/resource/faldo#>
dct: <http://purl.org/dc/terms/>
sio: <http://semanticscience.org/resource/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
hco: <http://identifiers.org/hco/>
hgnc: <http://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:HGNC:>