endpoint: 
  - https://rdfportal.org/primary/sparql
  - graph:
    - http://jpost.org/graph/database
    - http://jpost.org/graph/ontology
another_endpoint: 
  - https://tools.jpostdb.org/proxy/sparql
  - graph:
    - http://jpost.org/graph/database
    - http://jpost.org/graph/ontology
