title: jPOST databse RDF
website: https://globe.jpostdb.org/
description: jPOST database RDF is described the re-analyzed proteome dataset in the jPOST project.
tags: [ Protein, Organism, Health/Disease ]
provider:
creators:
  - name: Yuki Moriya
    affiliation: Database Center for Life Science
version: 202509
issued: 2025-09-04
licenses:
  - Attribution 4.0 International (CC BY 4.0)
