- JpostProject jpostdb:JPST000810:
  - a: jpost:Project
  - dct:contributor+:
    - []:
      - a:
        - foaf:Person
        - obo:MS_1002332 # lab head
      - foaf:name:
        - lab_head: "Yasushi Ishihama"
    - []:
      - a:
        - foaf:Person
        - obo:MS_1002037 # dataset submitter
      - vcard:organization_name:
        - organization_name: "Kyoto university"
      - foaf:name:
        - dataset_submitter: "Michio Funahashi"
  - dct:date:
    - jpost_project_date: 2016-07-21
  - dct:dateSubmitted:
    - jpost_project_submitted: 2016-06-22
  - dct:description:
    - project_description: "Proteome analyses of human induced pluripotent stem cell line (201B7-P32) were carried out using a two-meter monolithic silica C18 capillary columns without prefractionation. Tryptic peptides from 4 μg cell lysates were directly injected onto the 100 μm i.d. monolithic silica-C18 column and an 8-h gradient was applied at 500 nL/min. Triplicate measurements were conducted and the merged results were searched against UniProt DB to identify peptides and proteins. The obtained results were filtered at 1% FDR thresholds by searching against the randomized decoy DB both at peptide and protein levels. This dataset with the PX complete submission format will be further used to generate a customized DB in this jPOST project."
  - dct:identifier:
    - project_identifier: "JPST000810"
  - dct:title:
    - project_title: "Human iPS cell_201B7-P32"
  - jpost:hasDataset+:
    - jpost_dataset: JpostDataset
  - rdfs:label:
    - project_label: "Human iPS cell_201B7-P32"
  - rdfs:seeAlso+:
    - pxd: pxd:PXD004615
  - foaf:page:
    - repository: jporep:JPST000810

- JpostDataset jpostdb:DS810_1:
  - a: jpost:Dataset
  - dct:identifier:
    - dataset_identifier: "DS810_1"
#  - jpost:hasPeptide+:
#    - peptide: jpostdb:PEP810_1_14507
#    - unique_peptide_at_ms_level: jpostdb:PEP810_1_14508
#    - shared_peptide_at_ms_level: jpostdb:PEP810_1_14609
  - jpost:hasProfile:
    - profile: Profile
  - jpost:hasProtein+:
    - protein: Protein
#    - spectrum_sub_set_protein: jpostdb:PRT810_1_A0A1B0GTU1
#    - spectrum_subsumable_protein: jpostdb:PRT810_1_P10321 # P10321
#    - spectrum_same_set_protein: jpostdb:PRT810_1_P0CG08
  - sio:SIO_000216+: # has measurement value
    - []:
      - a: jpost:NumOfRawData
      - sio:SIO_000300: # has value
        - number_of_raw_data: 5
    - []:
      - a: jpost:NumOfPsms
      - sio:SIO_000300: # has value
        - number_of_psms: 43516
    - []:
      - a: jpost:NumOfLeadingProteins
      - sio:SIO_000300: # has value
        - number_of_leading_proteins: 3650
    - []:
      - a: jpost:NumOfPeptides
      - sio:SIO_000300: # has value
        - number_of_peptides: 19690
    - []:
      - a: jpost:NumOfProteinsWithUniquePeptide
      - sio:SIO_000300: # has value
        - number_of_proteins_with_unique_peptide: 3545
    - []:
      - a: jpost:NumOfSpectra
      - sio:SIO_000300: # has value
        - number_of_spectra: 43510
    - []:
      - a: jpost:NumOfMatchedProteins
      - sio:SIO_000300: # has value
        - number_of_matched_proteins: 4248

- Protein jpostdb:PRT810_1_A0A0B4J2D5:
  - a:
    - jpost:Protein
    - obo:MS_1002401 # leading protein
#    - jpost:RepresentativeIsoform
#    - obo:MS_1001591 # anchor protein
  - dct:identifier:
    - protein_identifier: "PRT810_1_A0A0B4J2D5"
  - jpost:hasDatabaseSequence:
    - db_seq: up:A0A0B4J2D5
  - jpost:hasIsoform:
    - protein_isoform: jpostdb:ISO810_1_A0A0B4J2D5-2
  - jpost:hasPeptideEvidence+:
    - []:
      - a: jpost:PeptideEvidence
      - faldo:location:
        - []:
          - a: faldo:Region
          - faldo:begin:
            - []:
              - a: faldo:ExactPosition
              - faldo:position:
                - begin: 117
          - faldo:end:
            - []:
              - a: faldo:ExactPosition
              - faldo:position:
                - end: 141
      - jpost:hasPeptide:
        - peptide: Peptide
  - jpost:inProteinGroup:
    - protein_group: bid:PG810_1_1
  - sio:SIO_000216+: # has measurement value
    - []:
      - a: obo:MS_1001097 # distinct peptide sequences
      - sio:SIO_000300: # has value
        - distinct_peptide_sequences: 5
    - []:
      - a: obo:MS_1002153 # protein level PSM counts
      - sio:SIO_000300: # has value
        - protein_level_psm_counts: 14
  - rdfs:label:
    - protein_label: "A0A0B4J2D5"
  - rdfs:seeAlso+:
    - uniprot: idup:A0A0B4J2D5

- Peptide jpostdb:PEP810_1_15421:
  - a:
    - jpost:Peptide
#    - jpost:SharedPeptide
  - dct:identifier:
    - peptide_identifier: "PEP810_1_15421"
  - jpost:hasPsm+:
    - peptide_spectrum_match: PeptideSpectrumMatch
  - jpost:hasSequence:
    - []:
      - a: obo:MS_1001344 # AA sequence
      - rdf:value:
        - aa_sequence: "ITDLANLSAANHDAAIFPGGFGAAK"
  - sio:SIO_000216+: # has measurement value
    - []:
      - a: jpost:NumOfPsms
      - sio:SIO_000300: # has value
        - number_of_peptide_psms: 6
    - []:
      - a: jpost:JpostScore
      - sio:SIO_000300: # has value
        - max_jpost_score: 39
    - []:
      - a: obo:MS_1001364 # peptide sequence-level global FDR
      - sio:SIO_000300: # has value
        - peptide_sequence_level_global_fdr: 0

- PeptideSpectrumMatch jpostdb:PSM810_1_5259:
  - a: jpost:PeptideSpectrumMatch
  - dct:identifier:
    - peptide_spectrum_match_identifier: "PSM810_1_5259"
  - jpost:hasSpectrum:
    - spectrum: Spectrum
  - sio:SIO_000216+: # has measurement value
    - []:
      - a: jpost:ExperimentalMassToCharge
      - sio:SIO_000221: # has unit
        - experimental_mass_to_charge_ratio_unit: obo:MS_1000040 # m/z
      - sio:SIO_000300: # has value
        - experimental_mass_to_charge_ratio: 814.7493
    - []:
      - a: obo:MS_1000894 # retention time
      - sio:SIO_000221: # has unit
        - retention_time_unit: obo:UO_0000031 # minute
      - sio:SIO_000300: # has value
        - retention_time: 59.20288
    - []:
      - a: jpost:JpostScore
      - sio:SIO_000300: # has value
        - jpost_score: 35
    - []:
      - a: jpost:CalculatedMassToCharge
      - sio:SIO_000300: # has value
        - calculated_mass_to_charge_ratio: 814.7519
    - []:
      - a: obo:MS_1000041 # charge state
      - sio:SIO_000300: # has value
        - charge_state: 3
  - jpost:hasModification*:
    - modification: [Phospho, Acetyl, Oxidation]

- Phospho:
  - a: unimod:UNIMOD_21
  - jpost:modificationSite:
    - phospho_modification_site: "S"
  - faldo:location:
    - []:
      - a: faldo:ExactPosition
      - faldo:position:
        - phospho_position: 5
      - faldo:reference:
        - phospho_ref_peptide: jpostdb:PEP810_1_15421

- Acetyl:
  - a: unimod:UNIMOD_1
  - jpost:modificationSite:
    - acetyl_modification_site: "S"
  - faldo:location:
    - []:
      - a: faldo:ExactPosition
      - faldo:position:
        - acetyle_position: 5
      - faldo:reference:
        - acetyl_ref_peptide: jpostdb:PEP810_1_15421

- Oxidation:
  - a: unimod:UNIMOD_35
  - jpost:modificationSite:
    - oxidation_modification_site: "M"
  - faldo:location:
    - []:
      - a: faldo:ExactPosition
      - faldo:position:
        - oxidation_position: 5
      - faldo:reference:
        - oxidation_ref_peptide: jpostdb:PEP810_1_15421

- Spectrum bid:SPC810_1_3_1.1.2188.10:
  - a: jpost:Spectrum
  - jpost:inRawData:
    - in_raw_data: bid:RAW810_1_3
  - rdfs:label:
    - spectrum_label: "1.1.2188.10"

- Profile bid:PRF810_1:
  - a: jpost:Profile
  - jpost:hasSample:
    - sample: Sample
  - jpost:hasEnzymeAndModification:
    - enzyme_modification: EnzymeModification
  - jpost:hasFractionation:
    - fractionation: Fractionation
  - jpost:hasMsMode:
    - ms_instrument_mode: MsInstrumentMode
  - jpost:hasRawData+:
    - raw_data: RawData

- Sample bid:SMP810_1:
  - a:
    - sio:SIO_001050 # sample
    - jpost:Sample
  - jpost:cellLine:
    - []:
      - a: jpost:CellLine
      - rdfs:label:
        - cell_line_bnode_label: "201B7-P32"
  - jpost:sampleType:
    - sample_type: ncit:C16403 # Cell Line
  - rdfs:comment:
    - sample_note: "201B7-P32 human iPS cell line"
  - jpost:species:
    - taxonomy: idtax:9606

- EnzymeModification bid:ENZ810_1:
  - a: jpost:EnzymeAndModification
  - jpost:enzyme+:
    - enzyme: obo:MS_1001251 # Trypsin
  - jpost:species:
    - taxonomy_mod: idtax:9606
  - jpost:variableModification:
    - []:
      - a: unimod:UNIMOD_35 # Oxidation
      - jpost:modificationClass:
        - modifiaction_class: jpost:JPO_026 # Artefact
      - jpost:modificationSite:
        - modification_site: "M"

- Fractionation bid:FRC810_1:
  - a: jpost:Fractionation
  - jpost:hasFractionationType:
    - []:
      - a: jpost:SubcellularFractionation
      - jpost:fractions:
        - subcellular_fractions: 1
      - jpost:replicates:
        - subcellular_replicates: 1
      - rdfs:label:
        - subcellular_fractionation_bnode_label: "Whole"

- MsInstrumentMode bid:MSM810_1:
  - a: jpost:MsMode
  - jpost:instrument:
    - instrument: obo:MS_1000932 # TripleTOF 5600
  - jpost:instrumentMode:
    - instrument_mode: jpost:JPO_005 # DDA-high res.
  - jpost:quantificationMethod:
    - quantification_method: obo:MS_1001905 # emPAI value
  - rdfs:comment:
    - comment: "One LC/MS run consists of five raw data."

- RawData bid:RAW810_1_1:
  - a: jpost:RawData
  - rdfs:label:
    - raw_data_label: "120118ry_201B7-32_1_1.wiff"