idtax: <http://identifiers.org/taxonomy/>
idup: <http://identifiers.org/uniprot/>
ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
pxd: <http://proteomecentral.proteomexchange.org/dataset/>
up: <http://purl.uniprot.org/uniprot/>
bid: <http://rdf.jpostdb.org/bid/>
jpostdb: <http://rdf.jpostdb.org/entry/>
jpost: <http://rdf.jpostdb.org/ontology/jpost.owl#>
unimod: <http://www.unimod.org/obo/unimod.obo#>
vcard: <http://www.w3.org/2006/vcard/ns#>
jporep: <https://repository.jpostdb.org/entry/>
faldo: <http://biohackathon.org/resource/faldo#>
obo: <http://purl.obolibrary.org/obo/>
dct: <http://purl.org/dc/terms/>
sio: <http://semanticscience.org/resource/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
foaf: <http://xmlns.com/foaf/0.1/>