rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct:  <http://purl.org/dc/terms/>
skos: <http://www.w3.org/2004/02/skos/core#>
hgnc: <http://identifiers.org/hgnc/>
ido:  <http://rdf.identifiers.org/ontology/>
idt:  <http://identifiers.org/>
m2r:  <http://med2rdf.org/ontology/med2rdf#>
obo:  <http://purl.obolibrary.org/obo/>
