title: dbNSFP  
website: https://sites.google.com/site/jpopgen/dbNSFP  
description: dbNSFP is a database developed for functional prediction and annotation of all potential non-synonymous single-nucleotide variants (nsSNVs) in the human genome.   
tags: ["nsSNVs", "functional prediction"]
provider: USF Genomics, College of Public Health, University of South Florida 
creators:
  - name: Med2RDF project  
    affiliation: http://med2rdf.org/ 
version: 4.9
issued: 2024-8-8
licenses:
  - See CITATION at https://sites.google.com/site/jpopgen/dbNSFP 
