dbnsfp: <http://purl.jp/bio/10/med2rdf/dbnsfp/>
dct: <http://purl.org/dc/terms/>
ensg: <http://rdf.ebi.ac.uk/resource/ensembl/>
ensp: <http://rdf.ebi.ac.uk/resource/ensembl.protein/>
enst: <http://rdf.ebi.ac.uk/resource/ensembl.transcript/>
faldo: <http://biohackathon.org/resource/faldo#>
m2r: <http://med2rdf.org/ontology/med2rdf#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
