faldo: <http://biohackathon.org/resource/faldo#>
dcmiterms: <http://dublincore.org/documents/dcmi-terms/>
hco: <http://identifiers.org/hco/1#>
med2rdf: <http://med2rdf.org/ontology/med2rdf#>
dbnsfp: <http://purl.jp/bio/10/med2rdf/dbnsfp/>
dbnsfp_algorithm: <http://purl.jp/bio/10/med2rdf/dbnsfp/algorithm/>
dbnsfp_conservation: <http://purl.jp/bio/10/med2rdf/dbnsfp/conservation/>
dbnsfp_faldo: <http://purl.jp/bio/10/med2rdf/dbnsfp/faldo/>
dbnsfp_gene: <http://purl.jp/bio/10/med2rdf/dbnsfp/gene/>
dbnsfp_variation: <http://purl.jp/bio/10/med2rdf/dbnsfp/variation/>
ensembl_gene: <http://rdf.ebi.ac.uk/resource/ensembl.gene/>
sio: <http://semanticscience.org/ontology/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>