sparql:
  description: SPARQL description.
  variables: [Dbnsfpvariation, dbnsfp_location_grch38, gene, dbnsfp_variation, allele_conservation, damage_prediction, dbnsfp_algorithm, sio_000216, dbnsfp_conservation_algorithm, phastcons100way_vertebrate_cscore, phastcons100way_vertebrate_crankscore, dbsnp_variation_location_grch37]