Composer:
  - json("composers.name")
  - prepend("http://hoge.org/openopus/composer/")
complete_name: json("composers.complete_name")
epoch: json("composers.epoch")
birth: json("composers.birth")
death: json("composers.death")

# Work:
#   - json("composers.works.id")
#   - prepend("http://hoge.org/openopus/work/")
title: json("composers.works.title")
subtitle: json("composers.works.subtitle")
genre: json("composers.works.genre")
recommended:
  - json("composers.works.recommended")
  - to_bool
