- ConvertTest:
  - a: ex:ConvertTest
  - dct:identifier:
    - id: ID1
  - ex:ex_ids:
    - ex_ids: a,b,c
  - rdfs:label:
    - label: hoge
  - ex:int_value:
    - int_value: 1
  - ex:float_value:
    - float_value: 1.23
  - ex:kebab:
    - kebab: aa-bb-cc
  - ex:repeat:
    - repeat: aaa
  - ex:date:
    - published: 2021-08-24
  - ex:bool:
    - bool: true
