title: GlyTouCan
website: https://glytoucan.org/
description: GlyTouCan is the international glycan structure repository.
tags: [ Other biomolecule, Structure ]
provider: National Institute of Advanced Industrial Science and Technology (AIST)
creators:
  - name: Hisashi Narimatsu
    affiliation: Glycoscience and Glycotechnology Research Group, Biotechnology Research Institute for Drug Discovery, National Institute of Advanced Industrial Science and Technology (AIST)
  - name: Kiyoko F. Aoki-Kinoshita
    affiliation: Soka University
  - name: Daisuke Shinmachi
    affiliation: Soka University
version: Ver1.0
issued: 2015-09-04
licenses:
  - Creative Commons Attribution 2.1 Japan (CC BY 2.1 JP)
  - GlyTouCan licensed under CC Attribution 2.1 Japan
