- Book ex:bk101:
    - a: ex:Book
    - dct:identifier:
        - id: bk101
    - ex:author:
        - author: Gambardella, Matthew
    - dct:title:
        - title: XML Developer's Guide
    - ex:genre:
        - genre: Computer
    - ex:price:
        - price: 44.95
    - ex:publish_date:
        - publish_date: 2000-10-01
    - dct:description:
        - description: An in-depth look at creating applications with XML.
