- CpdbHuman cpdb:MK03_HUMAN:
  - a: m2r:MacromolecularComplex
  - rdfs:label:
    - label: MK03_HUMAN
  - m2r:participant:
    - participant: uniprot_id:P27361
  # - cpdbo:evidence:
  #   - evidence: reference
  - dct:references:
    - reference: pmid:22307056
  - m2r:provenance:
    - data_source: http://identifiers.org/reactome
  - cpdbo:confidence:
    - confidence: 0.998051
  - obo:RO_0002162:
    - taxonomy: taxid:9606
