rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dc: <http://purl.org/dc/elements/1.1/>
dct: <http://purl.org/dc/terms/>
skos: <http://www.w3.org/2004/02/skos/core#>
obo: <http://purl.obolibrary.org/obo/>
pmid: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
pdb: <https://rdf.wwpdb.org/pdb/>
m2r: <http://med2rdf.org/ontology/med2rdf#>
cpdb: <http://med2rdf.org/dataset/cpdb/>
cpdbo: <http://med2rdf.org/ontology/cpdb#>
taxid: <http://identifiers.org/taxonomy/>
uniprot_id: <http://identifiers.org/uniprot/>
uniprot_entry: <http://purl.uniprot.org/core/mnemonic#>
