title: LigandBox
website: https://www.ncbi.nlm.nih.gov/gene/
description: LigandBox is a database of small chemical compounds for drug screening on computer docking studies. This database contains 3D molecular structures produced by calculation based on 2D structural data of chemicals those are provided by companies and KEGG databases.
tags: [Drug/Chemical, Structure]
provider: Technology Research Association for Next generation natural products chemistry
creators:
  - name: Yoshifumi Fukunishi
    affiliation: Molecular Profiling Research Center for Drug Discovery (molprof), The National Institute of Advanced Industrial Science and Technology (AIST)
  - name: Takeshi Kawabata
    affiliation: Institute for Protein Research, Osaka University
  - name: Yusuke Sugihara
    affiliation: Fujitsu Kyushu Systems, Ltd
  - name: Kohta Sakai
    affiliation: Fujitsu Kyushu Systems, Ltd
  - name: Hiroshi Kusudo
    affiliation: Hitachi Solutions East Japan, Ltd.
  - name: Yoshiaki Mikami
    affiliation: Hitachi Solutions East Japan, Ltd.
  - name: Tadaaki Mashimo
    affiliation: IMSBIO Co., Ltd
  - name: Haruki Nakamura
    affiliation: Institute for Protein Research, Osaka University
version: 2021-05-25
issued: 2021-05-25
licenses:
  - Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
  - LigandBox © Technology Research Association for Next generation natural products chemistry licensed under CC Attribution-Share Alike 4.0 International 
