dataset:
  name: Linked ICGC Dataset
  description: Linked ICGC Dataset is a linked data version of the public ICGC (International Cancer Genome Consortium) data. This includes the information of the donors and the somatic mutations.
