icgc: <http://icgc.link/>
detection: <http://icgc.link/Detection/>
donor: <http://icgc.link/Donor/>
effect: <http://icgc.link/Effect/>
gene: <http://icgc.link/Gene/>
mutation: <http://icgc.link/Mutation/>
project: <http://icgc.link/Project/>
vocab: <http://icgc.link/vocab/>
ensembl: <http://identifiers.org/ensembl/>
ivocab: <inv-http://icgc.link/vocab/>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
