DruMAPActivityGroup:
  - $id: csv("id")
  - "https://drumap.nibiohn.go.jp/rdf/activity_group/$id"
  - variables:
    - drumap_activity_group_id: $id
    - drumap_activity_group_label: "ActivityGroup:$id"
    - drumap_activity_group_description: csv("description")
