DruMAPActivityGroup:
  - source("activity_groups.csv")
  - $id: csv("id")
  - subject:
    - "https://drumap.nibiohn.go.jp/rdf/activity_group/$id"
  - objects:
    - drumap_activity_group_id: $id
    - drumap_activity_group_label: "ActivityGroup:$id"
    - drumap_activity_group_description: csv("description")
