DruMAPAssayType:
  - source("~/workspace/rdf-config-convert/drumap/csv_files/assay_types.csv")
  - $id: csv("id")
  - "https://drumap.nibiohn.go.jp/rdf/assay_type/$id"
  - variables:
    - drumap_assay_type_id: $id
    - drumap_assay_type_label: csv("name")
