DruMAPAssayTissue:
  - source("assay_tissues_subset.csv")
  - $id: csv("id")
  - subject:
    - "https://drumap.nibiohn.go.jp/rdf/assay_tissue/$id"
  - objects:
    - drumap_assay_tissue_id: $id
    - drumap_assay_tissue_label: csv("name")
    - drumap_assay_tissue_label:
      - csv("jname")
      - lang("ja")
    - drumap_assay_tissue_description: csv("description")
