DruMAPDocumentType:
  - $id: csv("id")
  - "https://drumap.nibiohn.go.jp/rdf/document_type/$id"
  - variables:
    - drumap_document_type_id: $id
    - drumap_document_type_label: csv("name")
    - drumap_document_type_description: csv("description")
