DruMAPDocumentType:
  - source("document_types.csv")
  - $id: csv("id")
  - subject:
    - "https://drumap.nibiohn.go.jp/rdf/document_type/$id"
  - objects:
    - drumap_document_type_id: $id
    - drumap_document_type_label: csv("name")
    - drumap_document_type_description: csv("description")
