DruMAPExperiment:
  - source("~/workspace/rdf-config-convert/drumap/csv_files/experiments.csv")
  - $id: csv("id")
  - "https://drumap.nibiohn.go.jp/rdf/experiment/$id"
  - variables:
    - drumap_experiment_id: $id
    - drumap_experiment_label: csv("description")
    - drumap_experiment_date: csv("date")
