DruMAPNameType:
  - $id: csv("id")
  - "https://drumap.nibiohn.go.jp/rdf/name_type/$id"
  - variables:
    - drumap_name_type_id: $id
    - drumap_name_type: csv("name")
    - drumap_name_type_description: csv("description")
