DruMAPNameType:
  - source("name_types.csv")
  - $id: csv("id")
  - subject:
    - "https://drumap.nibiohn.go.jp/rdf/name_type/$id"
  - objects:
    - drumap_name_type_id: $id
    - drumap_name_type: csv("name")
    - drumap_name_type_description: csv("description")
