DruMAPStructureType:
  - source("~/workspace/rdf-config-convert/drumap/csv_files/structure_types.csv")
  - $id: csv("id")
  - "https://drumap.nibiohn.go.jp/rdf/structure_type/$id"
  - variables:
    - drumap_structure_type_id: $id
    - drumap_structure_type: csv("name")
