DruMAPStructureType:
  - source("structure_types.csv")
  - $id: csv("id")
  - subject:
    - "https://drumap.nibiohn.go.jp/rdf/structure_type/$id"
  - objects:
    - drumap_structure_type_id: $id
    - drumap_structure_type: csv("name")
