DruMAPStructureSource:
  - source("~/workspace/rdf-config-convert/drumap/csv_files/structure_sources.csv")
  - $id: csv("id")
  - "https://drumap.nibiohn.go.jp/rdf/structure_source/$id"
  - variables:
    - drumap_structure_source_id: $id
    - drumap_structure_source: csv("name")
