DruMAPStructureSource:
  - source("structure_sources.csv")
  - $id: csv("id")
  - subject:
    - "https://drumap.nibiohn.go.jp/rdf/structure_source/$id"
  - objects:
    - drumap_structure_source_id: $id
    - drumap_structure_source: csv("name")
