Composer:
  - json("composers/name")
  - prepend("http://hoge.org/")
complete_name: json("composers/complete_name")
epoch: json("composers/epoch")
birth: json("composers/birth")
death: json("composers/death")

# Work:
#   - json("composers/works/title")
#   - prepend("http://hoge.org/")

# subtitle:
#   - json("composers/works/subtitle")

# genre:
#   - json("composers/works/genre")
