- Composer composer:Beethoven:
  - a: openopus:Composer
  - composer:complete_name:
    - complete_name: Ludwig van Beethoven
  - composer:epoch:
    - epoch: Early Romantic
  - composer:birth:
    - birth: 1770-01-01
  - composer:death:
    - death: 1827-01-01
  - composer:work:
    - work: Work

- Work work:Beethoven00001:
  - a: openopus:Work
  - work:title:
    - title: "Abschiendsgesang an Wiens Burger, WoO 121"
  - work:subtitle?:
    - subtitle: ""
  - work:genre:
    - genre: "Vocal"
  - work:recommended:
    - recommended: true
