- Composer hoge:Beethoven:
  - a: hoge:Composer
  - hoge:complete_name:
    - complete_name: Ludwig van Beethoven
  - hoge:epoch:
    - epoch: Early Romantic
  - hoge:birth:
    - birth: 1770-01-01
  - hoge:death:
    - death: 1827-01-01
  - hoge:work:
    - work: Work

- Work hoge:work1:
  - a: hoge:Work
  - hoge:title:
    - title: "Abschiendsgesang an Wiens Burger, WoO 121"
  - hoge:subtitle?:
    - subtitle: ""
  - hoge:genre:
    - genre: "Vocal"
