title: Fanta.bio RDF
website: https://fanta.bio/
description: Fanta.bio is a collection of functional genome annotations with transcriptional activities.
tags: [ Cis-regulatory elements, CREs, Transcription factors, TFs, Transcriptional Activity ]
provider: RIKEN Center for Integrative Medical Sciences
creators:
  - name: Yuki Moriya
    affiliation: Database Center for Life Science
  - name: Masaki Morioka
    affiliation: Database Center for Life Science
version: v1.1.0
issued: 2025-09-25
licenses:
  - Creative Commons Attribution 4.0 International (CC BY 4.0)