fanta:    <http://fanta.bio/cre/>
reftss:   <http://reftss.riken.jp/reftss/TSS:>
fantao:   <http://fanta.bio/ontology/>
dct:      <http://purl.org/dc/terms/>
skos:     <http://www.w3.org/2004/02/skos/core#>
obo:      <http://purl.obolibrary.org/obo/>
ncbigene: <http://identifiers.org/ncbigene/>
hgnc:     <http://identifiers.org/hgnc/>
ensembl:  <http://identifiers.org/ensembl/>
refseq:   <http://identifiers.org/refseq/>
insdc:    <http://identifiers.org/insdc/>
mgi:      <http://identifiers.org/MGI:>
uniprot:  <http://purl.uniprot.org/uniprot/>
sra:      <http://identifiers.org/insdc.sra/>
hco:      <http://identifiers.org/hco/>
mco:      <http://identifiers.org/mco/>
faldo:    <http://biohackathon.org/resource/faldo#>
tax:      <http://identifiers.org/taxonomy/>
sio:      <http://semanticscience.org/resource/>
rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
screen:   <https://screen.encodeproject.org/search/?assembly=GRCh38&q=>
foaf:     <http://xmlns.com/foaf/0.1/>
