chembl_molecule: <http://rdf.ebi.ac.uk/resource/chembl/molecule/>
dct: <http://purl.org/dc/terms/>
dgidb_drug: <http://identifiers.org/dgidb/drug/>
dgidb_gene: <http://identifiers.org/dgidb/gene/>
dgidb_interaction: <http://identifiers.org/dgidb/interaction/>
dgio: <http://purl.jp/bio/10/dgidb/>
ncbi_gene: <http://identifiers.org/ncbigene/>
pubmed: <http://identifiers.org/pubmed/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
skos: <http://www.w3.org/2004/02/skos/core#>
