- Diseaseconcept paconto:DIS093:
  - a:
    - skos:Concept
    - pacsch:DiseasesPACDB
  - gdgsch:diseaseName:
    - disease_name: "Cystitis"
  - ggdsch:conceptType:
    - concept_type: ConceptType
  - gmsch:causedBy+:
    - upec: Upec # UPEC
    - ecoli: Ecoli # Escherichia coli
  - pacsch:diseaseClass:
    - disease_class: "Urologic Disease"
  - pacsch:diseasesClassificationSystems+:
    - diseases_classification_systems: DiseasesClassificationSystems # Cystitis
  - pacsch:inDiseasesClassification:
    - diseases_classification: pacsch:DiseasesClassificationSystems
  - dct:identifier:
    - name: "DIS093"
  - rdfs:label:
    - disease_names: "Cystitis"
  - rdfs:seeAlso+:
    - mesh_id: mesh:D003556
  - skos:inScheme:
    - concept_scheme_pacdb: pacsch:ConceptSchemePACDB

- ConceptType pacsch:DiseasesNameAndClass:
  - a:
    - owl:Thing
    - ggdsch:ConceptType
  - rdfs:label:
    - concept_type_label: "Diseases Name and Class"

- Upec paconto:SPE381:
  - a:
    - skos:Concept
    - up:Strain
  - ggdsch:conceptType:
    - concept_type: ConceptType
  - gmsch:causes+:
    - causes: paconto:DIS043 # Sepsis
  - pacsch:organismForm:
    - organism_form: OrganismForm
  - pacsch:pathogenMaterialType:
    - pathogen_material: "strain"
  - pacsch:speciesForStrain:
    - species_strain: "Escherichia coli"
  - pacsch:strainName:
    - strain_name: "UPEC"
  - pacsch:tropismInReference+:
    - tropism_in_reference: paconto:SOU072_PUB216
  - dct:identifier:
    - upec_identifier: "SPE381"
  - up:rank:
    - rank: pacsch:NoRank
  - rdfs:label:
    - upec_label: "UPEC"

- Ecoli paconto:SPE009:
  - a:
    - skos:Concept
    - pacsch:Microorganisms
  - gmsch:causes+:
    - causes: paconto:DIS018 # Diarrhea
  - pacsch:ncbiTaxonomyId:
    - ncbi_taxonomy_id: "562"
  - pacsch:tropismInReference+:
    - tropism_in_reference: TropismInReference
  - glycan:has_strain+:
    - strain: "DS17"
  - dct:identifier:
    - ecoli_identifier: "SPE009"
  - up:rank:
    - rank_species: up:Species
  - up:scientificName:
    - scientific_name: "Escherichia coli"
  - up:strain+:
    - strain: paconto:SPE130 # str. 346
  - rdfs:label:
    - ecoli_label: "Escherichia coli"
  - rdfs:seeAlso:
    - taxonomy_id: taxo:562

- DiseasesClassificationSystems paconto:DIC111:
  - a:
    - skos:Concept
    - pacsch:DiseasesPACDB
  - gdgsch:diseaseName:
    - disease_name: "Cystitis"
  - ggdsch:conceptType:
    - concept_type: ConceptType
  - ggdsch:meshUniqueID:
    - mesh_id: "D003556"
  - ggdsch:umlsCUI:
    - umls_cui: "C0010692"
  - pacsch:broaderInDisClassifSystems:
    - pacdb_diseases: PacdbDiseases # Urinary Bladder Diseases
  - dct:identifier:
    - diseases_classification_systems_identifier: "DIC111"
  - rdfs:label:
    - diseases_classification_systems_label: "Cystitis"

- ConceptType pacsch:DiseasesClassifications:
  - a:
    - owl:Thing
    - ggdsch:ConceptType
  - rdfs:comment:
    - comment: "Classifications of infectious diseases recorded in PACDB by using MeSH (Medical Subject Headings) vocabulary"
  - rdfs:label:
    - concept_type_label: "Classifications of Diseases"

- PacdbDiseases paconto:DIC181:
  - a:
    - skos:Concept
    - pacsch:DiseasesPACDB
  - gdgsch:diseaseName:
    - disease_name: "Urinary Bladder Diseases"
  - ggdsch:meshUniqueID:
    - mesh_id: "D001745"
  - ggdsch:umlsCUI:
    - umls_cui: "C0005686"
  - pacsch:broaderInDisClassifSystems:
    - pacdb_diseases: paconto:DIC185 # Urologic Diseases
  - dct:identifier:
    - pacdb_diseases_identifier: "DIC181"
  - rdfs:label:
    - pacdb_diseases_label: "Urinary Bladder Diseases"
  - rdfs:seeAlso+:
    - mesh_id: mesh:D001745

- ConceptType pacsch:PathogenicMicroorganisms:
  - a:
    - owl:Thing
    - ggdsch:ConceptType
  - rdfs:label:
    - concept_type_label: "Pathogenic Microorganisms"
  - rdfs:seeAlso:
    - node_54: pacsch:Microorganisms

- OrganismForm pacsch:Bacteria:
  - a:
    - owl:Thing
    - pacsch:OrganismForms
  - rdfs:label:
    - thing_label: "Bacteria"
  - rdfs:seeAlso:
    - uniprot_bacteria: taxo:2
  - skos:altLabel:
    - alt_label: "SUPERKINGDOM Bacteria"

- TropismInReference paconto:SOU173_PUB089:
  - a: pacsch:TropismInReference
  - pacsch:describedInReference:
    - pacdb_references: paconto:PUB089
  - pacsch:hasTropismTo:
    - target_tissues_and_cells: TargetTissuesAndCells # Eukaryotic cells
  - dct:references:
    - pacdb_references: paconto:PUB089

- TargetTissuesAndCells paconto:SOU173:
  - a:
    - skos:Concept
    - pacsch:TargetTissuesAndCells
  - ggdsch:conceptType:
    - concept_type: pacsch:SourcesInHost
  - pacsch:bioSourceName:
    - bio_source_name: "Eukaryotic cells"
  - pacsch:targetClassification+:
    - target_classification: TargetClassification # Human
  - dct:identifier:
    - target_tissues_and_cells_identifier: "SOU173"
  - rdfs:label:
    - target_tissues_and_cells_label: "Eukaryotic cells"

- TargetClassification paconto:SOC020:
  - a:
    - skos:Concept
    - pacsch:TargetTissuesAndCells
  - ggdsch:conceptType:
    - concept_type: ConceptType
  - ggdsch:umlsCUI:
    - umls_cui: "C0086418"
  - dct:identifier:
    - target_classification_identifier: "SOC020"
  - rdfs:label:
    - target_classification_label: "Human"
  - skos:altLabel:
    - alt_label: "Humans"
  - skos:broader:
    - broader: paconto:SOC019 # Hominidae
  - skos:prefLabel:
    - pref_label: "Human"

- ConceptType pacsch:TargetsClassificationNCIT:
  - a:
    - owl:Thing
    - ggdsch:ConceptType
  - rdfs:comment:
    - comment: "Classifications of target sources in host-pathogen interactions based on the National Cancer Institute Thesaurus (NCIT), with adaptations to PACDB data"
  - rdfs:label:
    - concept_type_label: "Classification of targets in host-pathogen interactions based on the NCIT, with adaptations to PACDB data."

