endpoint: https://id.nlm.nih.gov/mesh/sparql

med2rdf:
  - http://sparql.med2rdf.org/sparql
  - graph:
    - http://med2rdf.org/graph/mesh

integbio:
  - https://integbio.jp/togosite/sparql
  - graph:
    - http://rdf.integbio.jp/dataset/togosite/mesh