title: Medical Subject Headings (MeSH) RDF Dataset Description
website: https://id.nlm.nih.gov/mesh/
description: A linked data representation of the MeSH biomedical vocabulary produced by the National Library of Medicine.
tags: [ Ontology/ Terminology/Nomenclature ]
provider: National Library of Medicine
creators:
  - name: National Library of Medicine
    affiliation: 
version: 2025
issued: 2024-12-05
license:
  - name: Creative commons 1.0 Universal (CC0 1.0)
    url: http://creativecommons.org/publicdomain/zero/1.0/
    credit: Genebank Project, NARO licensed under CC Atribution 4.0 International License.

