title:
  description: MeSH data model structure

main_subjects:
  description: A list of selected subjects from the MeSH data model.
  variables: [ Concept, Term, Descriptor, Geographic, Qualifier, TreeNumber, Chemical, Disease, Protocol, Organism ]

main_objects:
  description: A list of selected objects. Other objects will be ommitted from the schema diagram.
  variables: [ concept_label, concept_id, term_label, term_id, descriptor_label, descriptor_id, qualifier_label, qualifier_id, tree_number_label ]

some_subjects_and_objects:
  description: A list of subjects and objects which will be drawn on the schema diagram.
  variables: [ Concept, term_label, term_id, descriptor_label, descriptor_id, qualifier_label, qualifier_id, tree_number_label ]
