endpoint:
  - https://rdfportal.org/primary/sparql
  - graph:
    - http://rdf.integbio.jp/dataset/nikkaji/main
    - http://rdf.integbio.jp/dataset/nikkaji/inchi
    - http://rdf.integbio.jp/dataset/nikkaji/canonical_smiles
    - http://rdf.integbio.jp/dataset/nikkaji/link2jglobal
    - http://rdf.integbio.jp/dataset/nikkaji/mwmf
    - http://rdf.integbio.jp/dataset/nikkaji/link2jglobal_basedon_unichem
    - http://rdf.integbio.jp/dataset/nikkaji/link2jglobal_basedon_pubchem
    - http://rdf.integbio.jp/dataset/nikkaji/core
