dataset:
  name: Ensembl RDF
  description: Ensembl is a collection of automatically annotated genome databases for vertebrates and a number of eukaryotes, integrated with all other relevant biological data available.
