# ENSG
- EnsemblGene ens_resource:ENSG00000000003:
  - a:
    - obo:SO_0001217   # protein_coding_gene
    - ens_terms:protein_coding
    - ens_terms:miRNA
    - ens_terms:pseudogene
    - ens_terms:scaRNA
    - ens_terms:snoRNA
    - obo:SO_0000336   # pseudogene
    - ens_terms:processed_pseudogene
    - ens_terms:IG_J_gene
    - ens_terms:snRNA
    - obo:SO_0001263   # ncRNA_gene
    - ens_terms:TR_V_gene
    - ens_terms:IG_V_gene
    - ens_terms:misc_RNA
    - ens_terms:Mt_tRNA
    - ens_terms:Mt_rRNA
    - ens_terms:ribozyme
    - ens_terms:rRNA
    - ens_terms:TR_J_gene
    - ens_terms:vault_RNA
    - ens_terms:lncRNA
    - ens_terms:sRNA
    - ens_terms:IG_V_pseudogene
    - ens_terms:TR_C_gene
    - ens_terms:IG_C_gene
    - ens_terms:rRNA_pseudogene
    - ens_terms:TR_D_gene
    - ens_terms:unprocessed_pseudogene
    - ens_terms:TEC
    - ens_terms:IG_C_pseudogene
    - ens_terms:IG_pseudogene
    - ens_terms:polymorphic_pseudogene
    - ens_terms:transcribed_unprocessed_pseudogene
    - ens_terms:IG_J_pseudogene
    - ens_terms:TR_V_pseudogene
    - ens_terms:transcribed_processed_pseudogene
    - ens_terms:transcribed_unitary_pseudogene
    - ens_terms:translated_processed_pseudogene
    - ens_terms:unitary_pseudogene
    - ens_terms:TR_J_pseudogene
    - ens_terms:translated_unprocessed_pseudogene
    - ens_terms:scRNA
    - ens_terms:IG_D_gene
  - rdfs:label:
    - ensg_label: "TSPAN6"
  - rdfs:seeAlso+:
    - ensg_xref: EnsemblDBEntry   #ensi:ENSG00000000003, # hgnc:HGNC:11858, ncbigene:7105, omim:300191, uniprot:A0A087WYV6, wikigenes:7105
  - dc:description:
    - ensg_description: "tetraspanin 6 [Source:HGNC Symbol;Acc:HGNC:11858]"
  - dc:identifier:
    - ensg_id: "ENSG00000000003"
  - ens_terms:DEPENDENT:
    - ensg_dependent: EnsemblDBEntry   # ncbigene:7105, omim:300191, wikigenes:7105, uniprot:A0A087WYV6
  - ens_terms:DIRECT:
    - ensg_direct: EnsemblDBEntry   # hgnc:HGNC:11858, ens_resource:ArrayExpress/ENSG00000000003, ens_resource:Reactome_gene/R-HSA-1640170
  - ens_terms:MISC:
    - ensg_misc: EnsemblDBEntry   # <http://identifiers.org/mirbase/MI0000289>, ens_resource:Clone_based_ensembl_gene/AC068775.1
  - obo:RO_0002162:
    - ensg_taxonomy: taxonomy:9606
  - sio:SIO_000558:
    - ensg_orthlogous_to: EnsemblGene   # ens_resource:ENSG00000064201   # ens_resource:ENSANIG00000015960, ens_resource:ENSAPOG00000011926, ens_resource:ENSAMEG00000002204  #その他多数
  - faldo:location:
    - ensg_location: ens_resource:102/homo_sapiens/GRCh38/X:100627108-100639991:-1
  - skos:altlabel:
    - ensg_altlabel: "TM4SF6"
    
# ENST
- EnsemblTranscript enst:ENST00000207457:
  - a:
    - obo:SO_0000234   # mRNA
    - ens_terms:protein_coding
    - ens_terms:miRNA
    - ens_terms:pseudogene
    - ens_terms:scaRNA
    - ens_terms:snoRNA
    - obo:SO_0000013   # scRNA
    - obo:SO_0000275   # snoRNA
    - obo:SO_0000276   # miRNA
    - obo:SO_0000516   # pseudogenic_transcript
    - ens_terms:processed_pseudogene
    - ens_terms:IG_J_gene
    - ens_terms:snRNA
    - obo:SO_0000274   # snRNA
    - ens_terms:TR_V_gene
    - ens_terms:IG_V_gene
    - obo:SO_0000466   # V_gene_segment
    - ens_terms:misc_RNA
    - obo:SO_0000655   # ncRNA
    - ens_terms:Mt_tRNA
    - obo:SO_0000253   # tRNA
    - ens_terms:Mt_rRNA
    - ens_terms:ribozyme
    - ens_terms:rRNA
    - obo:SO_0000252   # rRNA
    - ens_terms:TR_J_gene
    - obo:SO_0000470   # J_gene_segment
    - ens_terms:vault_RNA
    - ens_terms:lncRNA
    - obo:SO_0001877   # lncRNA
    - ens_terms:sRNA
    - ens_terms:IG_V_pseudogene
    - ens_terms:TR_C_gene
    - ens_terms:IG_C_gene
    - obo:SO_0000478   # C_gene_segment
    - ens_terms:rRNA_pseudogene
    - ens_terms:TR_D_gene
    - obo:SO_0000458   # D_gene_segment
    - ens_terms:unprocessed_pseudogene
    - ens_terms:TEC
    - obo:SO_0002139   # unconfirmed_transcript
    - ens_terms:non_stop_decay
    - ens_terms:nonsense_mediated_decay
    - ens_terms:processed_transcript
    - ens_terms:retained_intron
    - ens_terms:IG_C_pseudogene
    - ens_terms:IG_pseudogene
    - ens_terms:polymorphic_pseudogene
    - ens_terms:transcribed_unprocessed_pseudogene
    - ens_terms:IG_J_pseudogene
    - ens_terms:TR_V_pseudogene
    - ens_terms:LRG_gene
    - ens_terms:transcribed_processed_pseudogene
    - ens_terms:transcribed_unitary_pseudogene
    - ens_terms:translated_processed_pseudogene
    - ens_terms:unitary_pseudogene
    - ens_terms:TR_J_pseudogene
    - ens_terms:translated_unprocessed_pseudogene
    - ens_terms:scRNA
    - ens_terms:IG_D_gene
  - rdfs:label:
    - enst_label: "TEKT2-201"
  - rdfs:seeAlso+:
    - enst_xref: EnsemblDBEntry   # http://identifiers.org/go/GO:0005634
  - dc:identifier:
    - enst_id: "ENST00000207457"
  - ens_terms:DIRECT:
    - enst_direct: EnsemblDBEntry   # <http://identifiers.org/ccds/CCDS401>
  - ens_terms:INFERRED_FROM_TRANSCRIPT:
    - enst_inferred_from_transcript: EnsemblDBEntry   # go:GO:0038096
  - ens_terms:CHECKSUM:
    - enst_checksum: EnsemblDBEntry   # <http://identifiers.org/rnacentral/URS0000255F92>
  - ens_terms:MISC:
    - enst_misc: EnsemblDBEntry   # ens_resource:HGNC_trans_name/TEKT2-201
  - obo:RO_0002162:   # in taxon
    - enst_taxonomy: taxonomy:9606
  - obo:SO_has_part+:
    - enst_has_exon: EnsemblExon
  - obo:SO_transcribed_from:
    - enst_transcribed_from: EnsemblGene
  - obo:SO_translates_to+:
    - enst_translates_to: EnsemblProtein
  - sio:SIO_000974+:
    - enst_has_ordered_exon: EnsemblExon
  - faldo:location:
    - enst_location: ens_resource:102/homo_sapiens/GRCh38/1:36084094-36088275:1
  - ens_terms:COORDINATE_OVERLAP:
    - enst_coordinate_overlap: ens_resource:UCSC/uc001bzr.4    # enst:ENST00000560726
  - ens_terms:SEQUENCE_MATCH:
    - enst_sequence_match: EnsemblDBEntry   # <http://identifiers.org/refseq/XR_243165>

# EnsemblExon
- EnsemblExon ense:ENSE00002619687:
  - a: obo:SO_0000147   # exon
  - rdfs:label:
    - ense_label: "ENSE00002619687"
  - rdfs:seeAlso+:
    - ense_xref: EnsemblDBEntry
  - dc:identifier:
    - ense_id: "ENSE00002619687"
  - obo:RO_0002162:   # in taxon
    - ense_taxonomy: taxonomy:9606
  - faldo:location:
    - ense_location: ens_resource:102/homo_sapiens/GRCh38/16:18792879-18793370:-1
    
#ENSP
- EnsemblProtein ensp:ENSP00000473889:
  - a: ens_terms:protein
  - rdfs:seeAlso:
    - ensp_xref: EnsemblDBEntry   # ena:AC244226, uniparc:UPI00034F23B3, uniprot:P01817, reactome:R-HSA-2871837, ensi:ENSP00000473889
  - dc:identifier:
    - ensp_id: "ENSP00000473889"
  - ens_terms:CHECKSUM:
    - ensp_checksum: EnsemblDBEntry   # uniparc:UPI00034F23B3
  - ens_terms:DEPENDENT:
    - ensp_dependent: EnsemblDBEntry   # ena:AC244226   # reactome:R-HSA-2871837
  - ens_terms:DIRECT:
    - ensp_direct: EnsemblDBEntry   # uniprot:P01817
  - ens_terms:INFERRED_PAIR:
    - ensp_inferred_pair: EnsemblDBEntry   # http://identifiers.org/refseq/XP_011523843
  - ens_terms:SEQUENCE_MATCH:
    - ensp_sequence_match: uniprot:A0A024R1S2   # http://purl.uniprot.org/uniprot/A0A024R1S2
  - obo:RO_0002162:   # in taxon
    - ensp_taxonomy: taxonomy:9606 
    
# ENST_Exon
- ENSTExon enst:ENST00000207457#Exon_2:
  - a: sio:SIO_001261   # ordered list item
  - sio:SIO_000628:   # is related to
    - enst_exon_related_to: EnsemblExon
  - sio:SIO_000300:   # has value
    - enst_exon_has_value: 2
    
# LRG
- LRG ens_resource:LRG_1076:
  - a: ens_terms:LRG_gene
  - obo:RO_0002162:   # in taxon
    - lrg_taxon: taxonomy:9606
  - rdfs:label:
    - lrg_label: "HMBS"
  - rdfs:seeAlso+:
    - lrg_xref: EnsemblDBEntry   # hgnc:HGNC:4982
  - dc:description:
    - lrg_description: "hydroxymethylbilane synthase [Source:HGNC Symbol;Acc:HGNC:4982]"
  - dc:identifier:
    - lrg_identifier: "LRG_1076"
  - ens_terms:DEPENDENT:
    - lrg_dependent: EnsemblDBEntry   # ncbigene:3145
  - ens_terms:DIRECT:
    - lrg_direct: EnsemblDBEntry   # hgnc:HGNC:4982
  - faldo:location:
    - lrg_location: ens_resource:102/homo_sapiens/LRG_1076:5005-13673:1
  - skos:altlabel*:
    - lrg_altlabel: "PORC"

- EnsemblDBEntry <http://identifiers.org/go/GO:0045944>:
  - a:
    - ens_terms:EnsemblDBEntry
    - <http://identifiers.org/ensembl>
    - <http://identifiers.org/uniprot>
    - <http://identifiers.org/uniparc>
    - <http://identifiers.org/go>
    - <http://identifiers.org/hgnc>
    - <http://identifiers.org/rfam>
    - <http://identifiers.org/merops>
    - <http://identifiers.org/rnacentral>
    - <http://identifiers.org/pdb>
    - <http://identifiers.org/ccds>
    - <http://identifiers.org/ena.embl>
    - <http://identifiers.org/hpa>
    - <http://identifiers.org/insdc>
    - <http://identifiers.org/lrg>
    - <http://identifiers.org/mirbase>
    - <http://identifiers.org/ncbigene>
    - <http://identifiers.org/omim>
    - <http://identifiers.org/reactome>
    - <http://identifiers.org/refseq>
    - <http://identifiers.org/wikigenes>
    - <http://identifiers.org/genedb>
    - <http://identifiers.org/chembl.target>
    - ens_resource:HGNC_trans_name
    - ens_resource:KEGG_Enzyme
    - ens_resource:RFAM_trans_name
    - ens_resource:EntrezGene_trans_name
    - ens_resource:ArrayExpress
    - ens_resource:Clone_based_ensembl_gene
    - ens_resource:Clone_based_ensembl_transcript
    - ens_resource:DBASS3
    - ens_resource:DBASS5
    - ens_resource:Reactome_gene
    - ens_resource:Reactome_transcript
    - ens_resource:UCSC
    - ens_resource:Uniprot_isoform
    - ens_resource:miRBase_trans_name
  - sio:SIO_000671:
    - has_identifier:
      - []:
        - a:
          - <http://idtype.identifiers.org/ensembl>
          - <http://idtype.identifiers.org/uniprot>
          - <http://idtype.identifiers.org/uniparc>
          - <http://idtype.identifiers.org/go>
          - <http://idtype.identifiers.org/hgnc>
          - <http://idtype.identifiers.org/rfam>
          - <http://idtype.identifiers.org/rnacentral>
          - <http://idtype.identifiers.org/merops>
          - <http://idtype.identifiers.org/pdb>
          - <http://idtype.identifiers.org/ccds>
          - <http://idtype.identifiers.org/ena.embl>
          - <http://idtype.identifiers.org/hpa>
          - <http://idtype.identifiers.org/insdc>
          - <http://idtype.identifiers.org/ncbigene>
          - <http://idtype.identifiers.org/lrg>
          - <http://idtype.identifiers.org/mirbase>
          - <http://idtype.identifiers.org/omim>
          - <http://idtype.identifiers.org/reactome>
          - <http://idtype.identifiers.org/refseq>
          - <http://idtype.identifiers.org/wikigenes>
          - <http://idtype.identifiers.org/genedb>
          - <http://idtype.identifiers.org/chembl.target>
        - sio:SIO_000300:
          - has_value: "GO:0007417"
  - rdfs:label:
    - db_entry_label: "TSPAN6"
  - dc:description:
    - db_entry_description: "tetraspanin 6"   # "Generated via ensembl_manual"
  - dc:identifier:
    - db_entry_identifier: "HGNC:11858"
  - owl:sameAs:
    - same_as: EnsemblDBEntry   # obo:GO_0045944
