use anyhow::{Context, Result};
use regex::Regex;
use std::collections::{HashMap, HashSet};

use crate::prefix::{expand_curie, is_uri_like};
use crate::types::*;

/// Sentinel value used to mark skipped positions in a Multiple pipeline value.
/// Preserves positional alignment across split columns.
const SKIP_SENTINEL: &str = "\0__SKIP__\0";

// ─── blank node ID generation ─────────────────────────────────────

use std::cell::Cell;
thread_local! {
    static BNODE_COUNTER: Cell<u64> = Cell::new(0);
}

fn next_bnode_id() -> String {
    BNODE_COUNTER.with(|c| {
        let id = c.get();
        c.set(id + 1);
        format!("_:b{}", id)
    })
}

/// Process all rows and generate triples.
/// Returns (triples, convert_subjects) where convert_subjects is the set of
/// subject URIs generated by convert rules (as opposed to auto-generated ones).
///
/// `source_path` and `start_row` are used in warning messages.
/// `start_row` is the 1-based TSV row number of the FIRST row in `rows`
/// (header is row 1, so the first data row is row 2).
pub fn process_rows(
    rows: &[HashMap<String, String>],
    convert: &ConvertConfig,
    model: &Model,
    prefixes: &PrefixMap,
    source_path: &str,
    start_row: usize,
) -> Result<(Vec<Triple>, HashSet<String>)> {
    let mut all_triples = Vec::new();
    let mut all_convert_subjects = HashSet::new();

    for (i, row) in rows.iter().enumerate() {
        let row_num = start_row + i;
        let (triples, subjects) = process_single_row(row, convert, model, prefixes, source_path, row_num)
            .with_context(|| format!("Error processing row {}", row_num))?;
        all_triples.extend(triples);
        all_convert_subjects.extend(subjects);
    }

    Ok((all_triples, all_convert_subjects))
}

/// Process a single TSV row through all subject rules
fn process_single_row(
    row: &HashMap<String, String>,
    convert: &ConvertConfig,
    model: &Model,
    prefixes: &PrefixMap,
    source_path: &str,
    row_num: usize,
) -> Result<(Vec<Triple>, HashSet<String>)> {
    // Global variables shared across all subject rules within one row
    let mut global_vars = Variables::new();
    let mut all_triples = Vec::new();
    let mut convert_subjects = HashSet::new();

    // subject_name -> list of generated subject URIs
    let mut generated_subjects: HashMap<String, Vec<String>> = HashMap::new();

    // ── Phase 1: compute all subject URIs and variables ──
    for rule in &convert.subject_rules {
        let mut local_vars = global_vars.clone();

        for var_def in &rule.pre_variables {
            let val = exec_pipeline(&var_def.pipeline, "", row, &local_vars, prefixes)?;
            if let PipelineValue::Single(v) = &val {
                local_vars.insert(var_def.name.clone(), v.clone());
            }
        }

        for var_def in &rule.subject_pipeline.variables {
            let val = exec_pipeline(&var_def.pipeline, "", row, &local_vars, prefixes)?;
            if let PipelineValue::Single(v) = &val {
                local_vars.insert(var_def.name.clone(), v.clone());
            }
        }

        // Generate subject URIs
        let subject_uris = exec_pipeline(
            &rule.subject_pipeline.steps, "", row, &local_vars, prefixes,
        )?;
        let uris = pipeline_to_vec(&subject_uris);
        // Track as convert-generated subjects
        for u in &uris {
            convert_subjects.insert(u.clone());
        }
        generated_subjects.insert(rule.name.clone(), uris);

        // Propagate variables to global scope
        for (k, v) in &local_vars {
            global_vars.insert(k.clone(), v.clone());
        }
    }

    // ── Phase 2: generate triples ──
    for rule in &convert.subject_rules {
        let mut local_vars = global_vars.clone();

        // Re-evaluate pre-variables (they might depend on other rules' vars now)
        for var_def in &rule.pre_variables {
            let val = exec_pipeline(&var_def.pipeline, "", row, &local_vars, prefixes)?;
            if let PipelineValue::Single(v) = &val {
                local_vars.insert(var_def.name.clone(), v.clone());
            }
        }
        for var_def in &rule.subject_pipeline.variables {
            let val = exec_pipeline(&var_def.pipeline, "", row, &local_vars, prefixes)?;
            if let PipelineValue::Single(v) = &val {
                local_vars.insert(var_def.name.clone(), v.clone());
            }
        }

        let subject_uris = generated_subjects.get(&rule.name).cloned().unwrap_or_default();
        if subject_uris.is_empty() {
            continue;
        }

        let model_subject = model.find_subject(&rule.name);

        // ── rdf:type triples ──
        if let Some(ms) = model_subject {
            for subj in &subject_uris {
                for rdf_type in &ms.rdf_types {
                    all_triples.push(Triple {
                        subject: subj.clone(),
                        predicate: "a".to_string(),
                        object: RdfTerm::Curie(rdf_type.clone()),
                    });
                }
            }
        }

        // ── object triples ──
        let mut obj_vars = local_vars.clone();

        // Separate inline variable defs ($xxx) from real object rules
        let mut real_obj_rules: Vec<&ObjectRule> = Vec::new();
        for obj_rule in &rule.object_rules {
            if obj_rule.name.starts_with('$') {
                // Variable definition in objects section
                let val = exec_pipeline(&obj_rule.pipeline, "", row, &obj_vars, prefixes)?;
                if let PipelineValue::Single(v) = &val {
                    obj_vars.insert(obj_rule.name.clone(), v.clone());
                }
            } else {
                real_obj_rules.push(obj_rule);
            }
        }

        // Track blank node IDs: key = "subject|outer_pred|inner_pred" → bnode_id
        let mut bnode_map: HashMap<String, String> = HashMap::new();

        for obj_rule in &real_obj_rules {
            // ── Check if this object belongs to a blank node group ──
            let bng_info = model.find_blank_node_group_for_object(&rule.name, &obj_rule.name);

            let pred_info = model_subject.and_then(|ms| {
                ms.predicates.iter().find(|p| {
                    p.objects.iter().any(|o| o.name == obj_rule.name) ||
                        p.blank_node_groups.iter().any(|bng|
                            bng.objects.iter().any(|o| o.name == obj_rule.name))
                })
            });

            let obj_def = model_subject.and_then(|ms| {
                ms.predicates.iter()
                    .flat_map(|p| {
                        p.objects.iter().chain(
                            p.blank_node_groups.iter().flat_map(|bng| bng.objects.iter())
                        )
                    })
                    .find(|o| o.name == obj_rule.name)
            });

            let predicate_uri = pred_info.map(|p| p.uri.clone())
                .unwrap_or_else(|| format!("unknown:{}", obj_rule.name));

            // Execute pipeline, handling inline var defs
            let mut pipeline_vars = obj_vars.clone();
            let pipeline_result = exec_object_pipeline(
                &obj_rule.pipeline, "", row, &mut pipeline_vars, prefixes,
            )?;

            // Detect lang/datatype from pipeline operations
            let pipeline_lang = find_lang_in_ops(&obj_rule.pipeline, &pipeline_vars);
            let pipeline_dt = find_datatype_in_ops(&obj_rule.pipeline, &pipeline_vars);

            // Determine how to create the RDF term
            let value_type = obj_def.map(|o| &o.value_type);

            // ── Helper closure to emit triples (handles blank node or direct) ──
            let object_cols = extract_col_refs(&obj_rule.pipeline);
            let object_name = obj_rule.name.clone();
            let emit_triple = |subj: &str, val: &str,
                               all: &mut Vec<Triple>,
                               bmap: &mut HashMap<String, String>|
                {
                    if val.is_empty() { return; }
                    let term = make_rdf_term(val, value_type, &pipeline_lang, &pipeline_dt, prefixes);

                    // Warn if a boolean was expected but the value didn't parse as one
                    if matches!(value_type, Some(ObjectValueType::LiteralBoolean))
                        && !matches!(term, RdfTerm::LiteralBoolean(_))
                    {
                        warn_boolean_parse_failure(
                            source_path, row_num,
                            &object_name, &object_cols, val, row,
                        );
                    }

                    if let Some((outer_pred, bng)) = &bng_info {
                        // Blank node path
                        let bkey = format!("{}|{}|{}", subj, outer_pred, bng.inner_predicate);
                        let bnode_id = bmap.entry(bkey).or_insert_with(|| {
                            let id = next_bnode_id();
                            // Emit outer triple: subject → outer_pred → bnode
                            all.push(Triple {
                                subject: subj.to_string(),
                                predicate: outer_pred.to_string(),
                                object: RdfTerm::BlankNode(id.clone()),
                            });
                            id
                        }).clone();
                        // Emit inner triple: bnode → inner_pred → value
                        all.push(Triple {
                            subject: bnode_id,
                            predicate: bng.inner_predicate.clone(),
                            object: term,
                        });
                    } else {
                        // Direct path (no blank node)
                        all.push(Triple {
                            subject: subj.to_string(),
                            predicate: predicate_uri.clone(),
                            object: term,
                        });
                    }
                };

            match &pipeline_result {
                PipelineValue::Single(val) => {
                    if !val.is_empty() {
                        for subj in &subject_uris {
                            emit_triple(subj, val, &mut all_triples, &mut bnode_map);
                        }
                    }
                }
                PipelineValue::Multiple(vals) => {
                    // Pair subjects and values position-by-position.
                    // - When values < subjects: extra subjects get no triple
                    // - When values > subjects: extra values are truncated
                    // - When values == subjects: 1-to-1
                    let pair_count = vals.len().min(subject_uris.len());

                    // Warn if both subject and object were split, but counts differ.
                    let subject_was_split = rule.subject_pipeline.steps.iter()
                        .any(|op| matches!(op, Operation::Split(_)));
                    let object_was_split = obj_rule.pipeline.iter()
                        .any(|op| matches!(op, Operation::Split(_)));
                    if subject_was_split && object_was_split && vals.len() != subject_uris.len() {
                        let subject_cols = extract_col_refs(&rule.subject_pipeline.steps);
                        let object_cols = extract_col_refs(&obj_rule.pipeline);
                        warn_split_mismatch(
                            source_path, row_num,
                            &rule.name, &subject_cols, subject_uris.len(),
                            &obj_rule.name, &object_cols, vals.len(),
                            row,
                        );
                    }

                    for i in 0..pair_count {
                        let val = &vals[i];
                        if val == SKIP_SENTINEL || val.is_empty() {
                            continue;
                        }
                        emit_triple(&subject_uris[i], val, &mut all_triples, &mut bnode_map);
                    }
                }
                PipelineValue::Skip => {}
            }

            // ── Emit rdf:type triples for Reference-typed objects ──
            if let Some(ObjectValueType::Reference(ref_name)) = value_type {
                let ref_uris: Vec<String> = match &pipeline_result {
                    PipelineValue::Single(val) if !val.is_empty() => vec![val.clone()],
                    PipelineValue::Multiple(vals) => vals.iter()
                        .filter(|v| *v != SKIP_SENTINEL && !v.is_empty())
                        .cloned()
                        .collect(),
                    _ => vec![],
                };
                emit_ref_type_triples(ref_name, &ref_uris, model, &mut all_triples);
            }

            // Merge vars back
            for (k, v) in &pipeline_vars {
                obj_vars.insert(k.clone(), v.clone());
            }
        }

        // ── Reference objects (defined in model but not in convert) ──
        if let Some(ms) = model_subject {
            for pred_def in &ms.predicates {
                for obj_def in &pred_def.objects {
                    let has_rule = rule.object_rules.iter().any(|r| r.name == obj_def.name);
                    if has_rule {
                        continue;
                    }

                    match &obj_def.value_type {
                        ObjectValueType::Reference(ref_name) => {
                            if let Some(ref_uris) = generated_subjects.get(ref_name.as_str()) {
                                // Broadcast rules:
                                // - 1 subject + N refs:  subject gets all N refs (e.g. HGNC → PubMed[])
                                // - N subjects + 1 ref:  all subjects share the same ref (e.g. DbNSFP → Variation)
                                // - N == M:              1-to-1
                                // - N != M (both > 1):   1-to-1 with truncation
                                if subject_uris.len() == 1 {
                                    for ref_uri in ref_uris {
                                        all_triples.push(Triple {
                                            subject: subject_uris[0].clone(),
                                            predicate: pred_def.uri.clone(),
                                            object: RdfTerm::Uri(ref_uri.clone()),
                                        });
                                    }
                                } else if ref_uris.len() == 1 {
                                    for subj in &subject_uris {
                                        all_triples.push(Triple {
                                            subject: subj.clone(),
                                            predicate: pred_def.uri.clone(),
                                            object: RdfTerm::Uri(ref_uris[0].clone()),
                                        });
                                    }
                                } else {
                                    let pair_count = ref_uris.len().min(subject_uris.len());
                                    for i in 0..pair_count {
                                        all_triples.push(Triple {
                                            subject: subject_uris[i].clone(),
                                            predicate: pred_def.uri.clone(),
                                            object: RdfTerm::Uri(ref_uris[i].clone()),
                                        });
                                    }
                                }
                                emit_ref_type_triples(ref_name, ref_uris, model, &mut all_triples);
                            }
                        }
                        ObjectValueType::ReferenceList(ref_names) => {
                            for ref_name in ref_names {
                                if let Some(ref_uris) = generated_subjects.get(ref_name.as_str()) {
                                    if subject_uris.len() == 1 {
                                        for ref_uri in ref_uris {
                                            all_triples.push(Triple {
                                                subject: subject_uris[0].clone(),
                                                predicate: pred_def.uri.clone(),
                                                object: RdfTerm::Uri(ref_uri.clone()),
                                            });
                                        }
                                    } else if ref_uris.len() == 1 {
                                        for subj in &subject_uris {
                                            all_triples.push(Triple {
                                                subject: subj.clone(),
                                                predicate: pred_def.uri.clone(),
                                                object: RdfTerm::Uri(ref_uris[0].clone()),
                                            });
                                        }
                                    } else {
                                        let pair_count = ref_uris.len().min(subject_uris.len());
                                        for i in 0..pair_count {
                                            all_triples.push(Triple {
                                                subject: subject_uris[i].clone(),
                                                predicate: pred_def.uri.clone(),
                                                object: RdfTerm::Uri(ref_uris[i].clone()),
                                            });
                                        }
                                    }
                                    emit_ref_type_triples(ref_name, ref_uris, model, &mut all_triples);
                                }
                            }
                        }
                        _ => {}
                    }
                }
            }
        }

        // Merge local vars back to global
        for (k, v) in &obj_vars {
            global_vars.insert(k.clone(), v.clone());
        }
    }

    Ok((all_triples, convert_subjects))
}

// ─── Pipeline execution ────────────────────────────────────────────

fn exec_pipeline(
    ops: &[Operation],
    initial: &str,
    row: &HashMap<String, String>,
    vars: &Variables,
    prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    exec_pipeline_from(ops, PipelineValue::Single(initial.to_string()), row, vars, prefixes)
}

/// Execute a pipeline starting from a given PipelineValue
fn exec_pipeline_from(
    ops: &[Operation],
    initial: PipelineValue,
    row: &HashMap<String, String>,
    vars: &Variables,
    prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    let mut current = initial;
    for op in ops {
        current = apply_op(&current, op, row, vars, prefixes)?;
    }
    Ok(current)
}

/// Execute object pipeline with inline variable definitions
fn exec_object_pipeline(
    ops: &[Operation],
    initial: &str,
    row: &HashMap<String, String>,
    vars: &mut Variables,
    prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    exec_object_pipeline_from(ops, PipelineValue::Single(initial.to_string()), row, vars, prefixes)
}

/// Execute object pipeline from a given PipelineValue, with support for
/// InlineVarDef and Switch (which need mutable vars).
fn exec_object_pipeline_from(
    ops: &[Operation],
    initial: PipelineValue,
    row: &HashMap<String, String>,
    vars: &mut Variables,
    prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    let mut current = initial;
    for op in ops {
        match op {
            Operation::InlineVarDef(name, sub_ops) => {
                // Pass current pipeline value so pick() etc. can operate on it
                let val = exec_pipeline_from(sub_ops, current.clone(), row, vars, prefixes)?;
                if let PipelineValue::Single(v) = &val {
                    vars.insert(name.clone(), v.clone());
                }
                // current value unchanged
            }
            Operation::Switch { input, cases, default_case } => {
                let switch_val = match input {
                    Some(var_name) => expand_vars(var_name, vars),
                    None => match &current {
                        PipelineValue::Single(s) => s.clone(),
                        _ => String::new(),
                    }
                };
                let matched = cases.iter()
                    .find(|(cv, _)| *cv == switch_val)
                    .map(|(_, ops)| ops)
                    .or(default_case.as_ref());
                if let Some(case_ops) = matched {
                    current = exec_object_pipeline_from(case_ops, current, row, vars, prefixes)?;
                }
            }
            _ => {
                current = apply_op(&current, op, row, vars, prefixes)?;
            }
        }
    }
    Ok(current)
}

fn apply_op(
    current: &PipelineValue,
    op: &Operation,
    row: &HashMap<String, String>,
    vars: &Variables,
    _prefixes: &PrefixMap,
) -> Result<PipelineValue> {
    match op {
        Operation::Col(col_name) => {
            let resolved = expand_vars(col_name, vars);
            let val = row.get(&resolved).cloned().unwrap_or_default();
            Ok(PipelineValue::Single(val))
        }

        Operation::Split(sep) => {
            match current {
                PipelineValue::Single(s) => {
                    if s.is_empty() {
                        return Ok(PipelineValue::Skip);
                    }
                    let mut parts: Vec<String> = s.split(sep.as_str())
                        .map(|p| {
                            let trimmed = p.trim();
                            if trimmed.is_empty() {
                                SKIP_SENTINEL.to_string()
                            } else {
                                trimmed.to_string()
                            }
                        })
                        .collect();
                    // Trim trailing sentinels (caused by trailing delimiters like "a;b;")
                    while parts.last().map_or(false, |p| p == SKIP_SENTINEL) {
                        parts.pop();
                    }
                    if parts.is_empty() || parts.iter().all(|p| p == SKIP_SENTINEL) {
                        Ok(PipelineValue::Skip)
                    } else {
                        Ok(PipelineValue::Multiple(parts))
                    }
                }
                PipelineValue::Multiple(vals) => {
                    let mut all = Vec::new();
                    for v in vals {
                        if v == SKIP_SENTINEL {
                            all.push(SKIP_SENTINEL.to_string());
                            continue;
                        }
                        let mut parts: Vec<String> = v.split(sep.as_str())
                            .map(|p| {
                                let trimmed = p.trim();
                                if trimmed.is_empty() {
                                    SKIP_SENTINEL.to_string()
                                } else {
                                    trimmed.to_string()
                                }
                            })
                            .collect();
                        // Trim trailing sentinels
                        while parts.last().map_or(false, |p| p == SKIP_SENTINEL) {
                            parts.pop();
                        }
                        all.extend(parts);
                    }
                    if all.is_empty() || all.iter().all(|p| p == SKIP_SENTINEL) {
                        Ok(PipelineValue::Skip)
                    } else {
                        Ok(PipelineValue::Multiple(all))
                    }
                }
                PipelineValue::Skip => Ok(PipelineValue::Skip),
            }
        }

        Operation::Prepend(prefix) => {
            let resolved = expand_vars(prefix, vars);
            map_values(current, |s| format!("{}{}", resolved, s))
        }

        Operation::Append(suffix) => {
            let resolved = expand_vars(suffix, vars);
            map_values(current, |s| format!("{}{}", s, resolved))
        }

        Operation::Join(args) => {
            if args.len() < 2 {
                return Ok(current.clone());
            }
            let sep = expand_vars(args.last().unwrap(), vars);
            let parts: Vec<String> = args[..args.len() - 1]
                .iter()
                .map(|a| expand_vars(a, vars))
                .collect();
            Ok(PipelineValue::Single(parts.join(&sep)))
        }

        Operation::Skip(skip_vals) => {
            let resolved: Vec<String> = skip_vals.iter().map(|v| expand_vars(v, vars)).collect();
            match current {
                PipelineValue::Single(s) => {
                    if resolved.contains(s) {
                        Ok(PipelineValue::Skip)
                    } else {
                        Ok(current.clone())
                    }
                }
                PipelineValue::Multiple(vals) => {
                    // Replace matching values with sentinel to preserve positional alignment
                    let replaced: Vec<String> = vals.iter()
                        .map(|v| {
                            if resolved.contains(v) {
                                SKIP_SENTINEL.to_string()
                            } else {
                                v.clone()
                            }
                        })
                        .collect();
                    // If all values are sentinels, skip entirely
                    if replaced.iter().all(|v| v == SKIP_SENTINEL) {
                        Ok(PipelineValue::Skip)
                    } else {
                        Ok(PipelineValue::Multiple(replaced))
                    }
                }
                PipelineValue::Skip => Ok(PipelineValue::Skip),
            }
        }

        Operation::Replace(pattern, replacement) => {
            let rp = expand_vars(replacement, vars);
            let rpa = expand_vars(pattern, vars);
            if let Ok(re) = Regex::new(&rpa) {
                map_values(current, |s| re.replace_all(&s, rp.as_str()).to_string())
            } else {
                map_values(current, |s| s.replace(&rpa, &rp))
            }
        }

        Operation::Delete(pattern) => {
            let rpa = expand_vars(pattern, vars);
            if let Ok(re) = Regex::new(&rpa) {
                map_values(current, |s| re.replace_all(&s, "").to_string())
            } else {
                map_values(current, |s| s.replace(&rpa, ""))
            }
        }

        Operation::Pick(n) => {
            match current {
                PipelineValue::Multiple(vals) => {
                    // Extract nth element (0-based), skipping sentinels
                    if let Some(val) = vals.get(*n) {
                        if val == SKIP_SENTINEL {
                            Ok(PipelineValue::Skip)
                        } else {
                            Ok(PipelineValue::Single(val.clone()))
                        }
                    } else {
                        Ok(PipelineValue::Skip)
                    }
                }
                PipelineValue::Single(_s) => {
                    if *n == 0 {
                        Ok(current.clone())
                    } else {
                        Ok(PipelineValue::Skip)
                    }
                }
                PipelineValue::Skip => Ok(PipelineValue::Skip),
            }
        }

        // lang/datatype are metadata-only – don't change the flowing value
        Operation::Lang(_) | Operation::Datatype(_) => Ok(current.clone()),

        Operation::Capitalize => {
            map_values(current, |s| {
                let mut c = s.chars();
                match c.next() {
                    None => String::new(),
                    Some(ch) => ch.to_uppercase().to_string() + c.as_str(),
                }
            })
        }

        Operation::Upcase => map_values(current, |s| s.to_uppercase()),
        Operation::Downcase => map_values(current, |s| s.to_lowercase()),

        Operation::VarRef(var_name) => {
            let resolved = expand_vars(var_name, vars);
            Ok(PipelineValue::Single(resolved))
        }

        Operation::StringTemplate(tpl) => {
            let resolved = expand_vars(tpl, vars);
            Ok(PipelineValue::Single(resolved))
        }

        Operation::InlineVarDef(_, _) => {
            // Handled in exec_object_pipeline_from
            Ok(current.clone())
        }

        Operation::Switch { input, cases, default_case } => {
            // Simple switch (without mutable vars).
            // For full support with InlineVarDefs in cases, use exec_object_pipeline_from.
            let switch_val = match input {
                Some(var_name) => expand_vars(var_name, vars),
                None => match current {
                    PipelineValue::Single(s) => s.clone(),
                    _ => return Ok(current.clone()),
                }
            };
            let matched = cases.iter()
                .find(|(cv, _)| *cv == switch_val)
                .map(|(_, ops)| ops)
                .or(default_case.as_ref());
            if let Some(case_ops) = matched {
                exec_pipeline_from(case_ops, current.clone(), row, vars, _prefixes)
            } else {
                Ok(current.clone())
            }
        }
    }
}

// ─── helpers ───────────────────────────────────────────────────────

fn map_values<F>(current: &PipelineValue, f: F) -> Result<PipelineValue>
where
    F: Fn(String) -> String,
{
    match current {
        PipelineValue::Single(s) => Ok(PipelineValue::Single(f(s.clone()))),
        PipelineValue::Multiple(vs) => {
            Ok(PipelineValue::Multiple(vs.iter().map(|v| {
                if v == SKIP_SENTINEL { v.clone() } else { f(v.clone()) }
            }).collect()))
        }
        PipelineValue::Skip => Ok(PipelineValue::Skip),
    }
}

fn vec_to_pipeline(v: Vec<String>) -> PipelineValue {
    match v.len() {
        0 => PipelineValue::Skip,
        1 => PipelineValue::Single(v.into_iter().next().unwrap()),
        _ => PipelineValue::Multiple(v),
    }
}

fn pipeline_to_vec(pv: &PipelineValue) -> Vec<String> {
    match pv {
        PipelineValue::Single(s) => vec![s.clone()],
        PipelineValue::Multiple(v) => v.clone(),
        PipelineValue::Skip => vec![],
    }
}

/// Expand $var references in a string (longest match first)
fn expand_vars(s: &str, vars: &Variables) -> String {
    let mut result = s.to_string();
    let mut names: Vec<&String> = vars.keys().collect();
    names.sort_by(|a, b| b.len().cmp(&a.len()));
    for name in names {
        if let Some(val) = vars.get(name) {
            result = result.replace(name.as_str(), val);
        }
    }
    result
}

/// Look for lang() in a flat list of ops
fn find_lang_in_ops(ops: &[Operation], vars: &Variables) -> Option<String> {
    for op in ops {
        if let Operation::Lang(tag) = op {
            return Some(expand_vars(tag, vars));
        }
    }
    None
}

/// Look for datatype() in a flat list of ops
fn find_datatype_in_ops(ops: &[Operation], vars: &Variables) -> Option<String> {
    for op in ops {
        if let Operation::Datatype(dt) = op {
            return Some(expand_vars(dt, vars));
        }
    }
    None
}

/// Build an RdfTerm from a string value + model type + pipeline metadata
fn make_rdf_term(
    value: &str,
    value_type: Option<&ObjectValueType>,
    pipeline_lang: &Option<String>,
    pipeline_dt: &Option<String>,
    prefixes: &PrefixMap,
) -> RdfTerm {
    let value = value.trim();

    // Pipeline-level lang/datatype override model-level types
    if let Some(lang) = pipeline_lang {
        return RdfTerm::LiteralLangString(value.to_string(), lang.clone());
    }
    if let Some(dt) = pipeline_dt {
        return RdfTerm::LiteralDatatype(value.to_string(), dt.clone());
    }

    match value_type {
        Some(ObjectValueType::Uri) => {
            if value.starts_with("http://") || value.starts_with("https://") {
                RdfTerm::Uri(value.to_string())
            } else if value.starts_with('<') && value.ends_with('>') {
                RdfTerm::Uri(value[1..value.len() - 1].to_string())
            } else if let Some(expanded) = expand_curie(value, prefixes) {
                RdfTerm::Uri(expanded)
            } else {
                RdfTerm::Curie(value.to_string())
            }
        }
        Some(ObjectValueType::Reference(_)) => {
            RdfTerm::Uri(value.to_string())
        }
        Some(ObjectValueType::LiteralInteger) => {
            if let Ok(i) = value.parse::<i64>() {
                RdfTerm::LiteralInteger(i)
            } else if value.parse::<f64>().is_ok() {
                RdfTerm::LiteralFloat(ensure_decimal_point(value))
            } else {
                RdfTerm::LiteralString(value.to_string())
            }
        }
        Some(ObjectValueType::LiteralFloat) => {
            if value.parse::<f64>().is_ok() {
                RdfTerm::LiteralFloat(ensure_decimal_point(value))
            } else {
                RdfTerm::LiteralString(value.to_string())
            }
        }
        Some(ObjectValueType::LiteralBoolean) => {
            match value.to_lowercase().as_str() {
                "true" | "1" | "yes" | "y" | "t" => RdfTerm::LiteralBoolean(true),
                "false" | "0" | "no" | "n" | "f" => RdfTerm::LiteralBoolean(false),
                _ => RdfTerm::LiteralString(value.to_string()),
            }
        }
        Some(ObjectValueType::LiteralLangString { lang }) => {
            RdfTerm::LiteralLangString(value.to_string(), lang.clone())
        }
        Some(ObjectValueType::LiteralDatatype { datatype }) => {
            RdfTerm::LiteralDatatype(value.to_string(), datatype.clone())
        }
        Some(ObjectValueType::LiteralString) | None => {
            // Auto-detect
            if value.starts_with("http://") || value.starts_with("https://") {
                RdfTerm::Uri(value.to_string())
            } else if is_uri_like(value, prefixes) {
                if let Some(expanded) = expand_curie(value, prefixes) {
                    RdfTerm::Uri(expanded)
                } else {
                    RdfTerm::Curie(value.to_string())
                }
            } else {
                RdfTerm::LiteralString(value.to_string())
            }
        }
        _ => RdfTerm::LiteralString(value.to_string()),
    }
}

/// Ensure a numeric string has a decimal point so it serializes as xsd:decimal
/// shorthand (e.g. "10" → "10.0", "3.14" → "3.14", "1e5" → "1e5").
/// Emit rdf:type triples for URIs that reference a model subject.
/// E.g., if `ref_name` is "TCGAProject" and model defines `TCGAProject: a tcgao:Project`,
/// then for each `ref_uri`, emit `<ref_uri> a tcgao:Project`.
/// Extract all `col(...)` column names referenced in a pipeline.
/// Returns column names in the order they appear.
fn extract_col_refs(ops: &[Operation]) -> Vec<String> {
    let mut cols = Vec::new();
    for op in ops {
        match op {
            Operation::Col(name) => cols.push(name.clone()),
            Operation::InlineVarDef(_, sub_ops) => cols.extend(extract_col_refs(sub_ops)),
            Operation::Switch { cases, default_case, .. } => {
                for (_, sub_ops) in cases {
                    cols.extend(extract_col_refs(sub_ops));
                }
                if let Some(d) = default_case {
                    cols.extend(extract_col_refs(d));
                }
            }
            _ => {}
        }
    }
    cols
}

/// Format columns as "name1=value1, name2=value2" for warning messages.
fn format_cols(cols: &[String], row: &HashMap<String, String>) -> String {
    if cols.is_empty() {
        return "<no col() reference>".to_string();
    }
    cols.iter()
        .map(|c| format!("{}={:?}", c, row.get(c).map(|s| s.as_str()).unwrap_or("")))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Emit a warning about subject/object split mismatch.
fn warn_split_mismatch(
    source_path: &str,
    row_num: usize,
    subject_name: &str,
    subject_cols: &[String],
    subject_count: usize,
    object_name: &str,
    object_cols: &[String],
    object_count: usize,
    row: &HashMap<String, String>,
) {
    eprintln!(
        "warning: split count mismatch at {}:{}: subject '{}' (count={}, cols: {}) vs object '{}' (count={}, cols: {})",
        source_path, row_num,
        subject_name, subject_count, format_cols(subject_cols, row),
        object_name, object_count, format_cols(object_cols, row),
    );
}

/// Emit a warning about boolean parse failure.
fn warn_boolean_parse_failure(
    source_path: &str,
    row_num: usize,
    object_name: &str,
    object_cols: &[String],
    value: &str,
    row: &HashMap<String, String>,
) {
    eprintln!(
        "warning: cannot parse as boolean at {}:{}: object '{}' (cols: {}) value={:?}",
        source_path, row_num,
        object_name, format_cols(object_cols, row), value,
    );
}

fn emit_ref_type_triples(ref_name: &str, ref_uris: &[String], model: &Model, triples: &mut Vec<Triple>) {
    if let Some(ref_subject) = model.find_subject(ref_name) {
        for rdf_type in &ref_subject.rdf_types {
            for ref_uri in ref_uris {
                triples.push(Triple {
                    subject: ref_uri.clone(),
                    predicate: "a".to_string(),
                    object: RdfTerm::Curie(rdf_type.clone()),
                });
            }
        }
    }
}

fn ensure_decimal_point(s: &str) -> String {
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s.to_string()
    } else {
        format!("{}.0", s)
    }
}
