use std::collections::HashSet;
use indexmap::IndexMap;
use oxrdf::{NamedNode, BlankNode, Literal, NamedOrBlankNode, vocab::{rdf, xsd}};

use crate::prefix::expand_curie;
use crate::types::*;

/// Convert an internal Triple to an oxrdf::Triple.
/// Returns None if IRI creation fails.
pub fn to_oxrdf_triple(triple: &Triple, prefixes: &PrefixMap) -> Option<oxrdf::Triple> {
    // Resolve subject (may be a blank node)
    let subject: NamedOrBlankNode = if triple.subject.starts_with("_:") {
        let local = &triple.subject[2..]; // strip "_:"
        BlankNode::new(local).ok()?.into()
    } else {
        let subject_iri = resolve_to_iri(&triple.subject, prefixes);
        NamedNode::new(&subject_iri).ok()?.into()
    };

    // Resolve predicate
    let predicate_iri = if triple.predicate == "a" {
        rdf::TYPE.as_str().to_string()
    } else {
        resolve_to_iri(&triple.predicate, prefixes)
    };
    let predicate = NamedNode::new(&predicate_iri).ok()?;

    // Convert object
    let object: oxrdf::Term = match &triple.object {
        RdfTerm::Uri(uri) => {
            let resolved = resolve_to_iri(uri, prefixes);
            NamedNode::new(&resolved).ok()?.into()
        }
        RdfTerm::Curie(curie) => {
            let expanded = resolve_to_iri(curie, prefixes);
            NamedNode::new(&expanded).ok()?.into()
        }
        RdfTerm::BlankNode(id) => {
            let local = id.strip_prefix("_:").unwrap_or(id);
            BlankNode::new(local).ok()?.into()
        }
        RdfTerm::LiteralString(s) => {
            Literal::new_simple_literal(s.as_str()).into()
        }
        RdfTerm::LiteralInteger(i) => {
            Literal::new_typed_literal(i.to_string(), xsd::INTEGER).into()
        }
        RdfTerm::LiteralFloat(s) => {
            Literal::new_typed_literal(s.as_str(), xsd::DECIMAL).into()
        }
        RdfTerm::LiteralBoolean(b) => {
            Literal::new_typed_literal(if *b { "true" } else { "false" }, xsd::BOOLEAN).into()
        }
        RdfTerm::LiteralLangString(s, lang) => {
            Literal::new_language_tagged_literal_unchecked(s.as_str(), lang.as_str()).into()
        }
        RdfTerm::LiteralDatatype(s, dt) => {
            let dt_iri = resolve_to_iri(dt, prefixes);
            let dt_node = NamedNode::new(&dt_iri).ok()?;
            Literal::new_typed_literal(s.as_str(), dt_node).into()
        }
    };

    Some(oxrdf::Triple::new(subject, predicate, object))
}

/// Filter out convert-generated subjects that only have rdf:type predicates.
/// Auto-generated subjects (from Reference type emission, not in convert_subjects)
/// are always kept.
///
/// `convert_subjects`: the set of subject URIs generated by convert rules.
pub fn filter_type_only_subjects(triples: &[Triple], convert_subjects: &HashSet<String>) -> Vec<Triple> {
    // Identify type-only subjects among convert-generated subjects only
    let mut has_non_type: IndexMap<&str, bool> = IndexMap::new();
    for t in triples {
        // Only consider convert-generated subjects for type-only check
        if !convert_subjects.contains(&t.subject) {
            continue;
        }
        let entry = has_non_type.entry(&t.subject).or_insert(false);
        if t.predicate != "a" && t.predicate != "rdf:type" {
            *entry = true;
        }
    }
    let type_only: HashSet<&str> = has_non_type.iter()
        .filter(|(_, has)| !**has)
        .map(|(subj, _)| *subj)
        .collect();

    // Filter triples: remove type-only subjects and references to them
    triples.iter()
        .filter(|t| {
            if type_only.contains(t.subject.as_str()) {
                return false;
            }
            match &t.object {
                RdfTerm::Uri(uri) if type_only.contains(uri.as_str()) => false,
                RdfTerm::Curie(c) if type_only.contains(c.as_str()) => false,
                _ => true,
            }
        })
        .cloned()
        .collect()
}

/// Resolve a string (CURIE or full URI) to a full IRI
pub fn resolve_to_iri(value: &str, prefixes: &PrefixMap) -> String {
    if value.starts_with("http://") || value.starts_with("https://") {
        return value.to_string();
    }
    if let Some(expanded) = expand_curie(value, prefixes) {
        return expanded;
    }
    value.to_string()
}

