dataset:
  name: CIVIC
  description: CIViC is a knowledgebase for Clinical Interpretation of Variants in Cancer. It has collected knowledge of the therapeutic, prognostic, diagnostic and predisposing relevance of inherited and somatic variants in cancer based on expert-crowdsourcing.
