
- QuantoReport quanto:ERR026579_1_fastqc:
  - a: sos:SequenceStatisticsReport
  - sos:encoding:
    - encoding: "Sanger / Illumina 1.9"
  - sos:fastqcVersion:
    - fastqc_version: "0.10.0"
  - sos:fileType:
    - file_type: "Conventional base calls"
  - sos:filename:
    - filename: "ERR026579_1.fastq"
  - sos:filteredSequences:
    - []:
      - a: sos:SequenceReadAmount
      - rdf:value+:
        - node_39: 0
  - sos:maxSequenceLength:
    - []:
      - a: sos:SequenceReadLength
      - rdf:value+:
        - max_sequence_length: 62
  - sos:meanSequenceLength:
    - []:
      - a: sos:SequenceReadLength
      - sos:hasUnit+:
        - basepair: obo:UO_0000244 # base pair
      - rdf:value+:
        - mean_sequence_length: 62.0
  - sos:medianSequenceLength:
    - []:
      - a: sos:SequenceReadLength
      - rdf:value+:
        - median_sequence_length: 62.0
  - sos:minSequenceLength:
    - []:
      - a: sos:SequenceReadLength
      - rdf:value+:
        - min_sequence_length: 62
  - sos:overallMeanBaseCallQuality:
    - []:
      - a: sos:PhredQualityScore
      - sos:hasUnit+:
        - count_unit: obo:UO_0000189 # count unit
      - rdf:value+:
        - overall_mean_base_call_quality: 33.1428
  - sos:overallMedianBaseCallQuality:
    - []:
      - a: sos:PhredQualityScore
      - rdf:value+:
        - overall_median_base_call_quality: 33.909
  - sos:overallNContent:
    - []:
      - a: sos:BaseRatio
      - sos:hasUnit+:
        - percent: obo:UO_0000187 # percent
      - rdf:value+:
        - overall_n_content: 0.00158011
  - sos:percentGC:
    - []:
      - a: sos:BaseRatio
      - rdf:value+:
        - percent_gc: 40.0
  - sos:totalSequences:
    - []:
      - a: sos:SequenceReadAmount
      - rdf:value+:
        - total_sequences: 4254262
  - dct:contributor+:
    - contributor: "Tazro Ohta"
  - dct:created+:
    - datecreated: "2016-07-10"
  - dct:identifier+:
    - identifier: "ERR026579_1_fastqc"
  - dct:license+:
    - resource: cc4
  - dct:publisher+:
    - publisher: dbcls
  - pav:version+:
    - version: "0.1.2"
  - rdfs:seeAlso+:
    - insdc_sra: sra:ERR026579
  - foaf:page+:
    - page: base:quanto.dbcls.jp
