endpoint:
  - https://rdfportal.org/sib/sparql
  - graph:
    - http://sparql.uniprot.org/uniprot
    - http://sparql.uniprot.org/obsolete
    - http://sparql.uniprot.org/citationmapping
    - http://sparql.uniprot.org/taxonomy
    - http://sparql.uniprot.org/citations
    - http://sparql.uniprot.org/proteomes
    - http://sparql.uniprot.org/go
    - http://sparql.uniprot.org/enzyme
    - http://sparql.uniprot.org/diseases
    - http://sparql.uniprot.org/journal
    - http://sparql.uniprot.org/pathways
    - http://sparql.uniprot.org/keywords
    - http://sparql.uniprot.org/locations
    - http://sparql.uniprot.org/tissues
    - http://sparql.uniprot.org/core
    - http://sparql.uniprot.org/databases
another_endpoint:
  - https://sparql.uniprot.org/sparql
  - https://rdfportal.org/sib/sparql
