- UniProt <http://rdf.uniprot.org/protein/P06493>:
    - a: core:Protein
    - core:recommendedName:
        - structured_recommended_name: StructuredRecommendedName
    - core:alternativeName:
        - structured_alternative_name: StructuredAlternativeName
    - core:mnemonic:
        - mnemonic: "CDK1_HUMAN"
    - core:oldMnemonic:
        - old_mnemonic: ["CC2_HUMAN", "CDC2_HUMAN"]
    - core:reviewed:
        - reviewed: true
    - core:existence:
        - existence: core:Evidence_at_Protein_Level_Existence
    - core:sequence:
        - sequence: Sequence
    - core:conflictingSequence:
        - conflicting_sequence: ConflictingSequence
    - core:created:
        - created: 1988-01-01
    - core:modified:
        - modified: 2020-08-12
    - core:version:
        - version: 253
    - core:organism:
        - organism: taxonomy:9606
    - core:encodedBy:
        - encoded_by: EncodedBy
    - core:enzyme:
        - enzyme: ["enzyme:2.7.11.22", "enzyme:2.7.11.23"]
    - core:proteome:
        - proteome: <http://purl.uniprot.org/proteomes/UP000005640#Chromosome%2010>
    - core:classifiedWith:
        - classified_with: ["obo:GO_0000086", "keywords:1017"]
    - core:annotation:
        - activity_regulation_annotation: ActivityRegulationAnnotation
    - core:annotation:
        - allergen_annotation: 
    - core:annotation:
        - alternative_sequence_annotation: AlternativeSequenceAnnotation
    - core:annotation:
        - natural_variant_annotation: 
    - core:annotation:
        - alternative_initiation_annotation: 
    - core:annotation:
        - alternative_promoter_usage_annotation: 
    - core:annotation:
        - alternative_splicing_annotation: AlternativeSplicingAnnotation
    - core:annotation:
        - ribosomal_frameshifting: RibosomalFrameshifting
    - core:annotation:
        - absorption_annotation: 
    - core:annotation:
        - kinetics_annotation: 
    - core:annotation:
        - ph_dependence_annotation: 
    - core:annotation:
        - redox_potential_annotation: 
    - core:annotation:
        - temperature_dependence_annotation: 
    - core:annotation:
        - biotechnology_annotation: 
    - core:annotation:
        - catalitic_activity_annotation: CataliticActivityAnnotation
    - core:annotation:
        - caution_annotation: 
    - core:annotation:
        - cofactor_annotation: 
    - core:annotation:
        - developmental_stage_annotation: 
    - core:annotation:
        - disease_annotation: 
    - core:annotation:
        - disruption_phenotype_annotation: 
    - core:annotation:
        - domain_annotation: 
    - core:annotation:
        - function_annotation: FunctionAnnotation
    - core:annotation:
        - induction_annotation: InductionAnnotation
    - core:annotation:
        - pathway_annotation:
    - core:annotation:
        - pharmaceutical_annotation: 
    - core:annotation:
        - polymorphism_annotation: 
    - core:annotation:
        - ptm_annotation: PtmAnnotation
    - core:annotation:
        - rna_editing_annotation: 
    - core:annotation:
        - beta_strand_annotation: BetaStrandAnnotation
    - core:annotation:
        - helix_annotation: HelixAnnotation
    - core:annotation:
        - turn_annotation: TurnAnnotation
    - core:annotation:
        - active_site_annotation: ActiveSiteAnnotation
    - core:annotation:
        - binding_site_annotation: BindingSiteAnnotation
    - core:annotation:
        - metal_binding_annotation: 
    - core:annotation:
        - chain_annotation: ChainAnnotation
    - core:annotation:
        - initiator_methionine_annotation: InitiatorMethionineAnnotation
    - core:annotation:
        - peptide_annotation: 
    - core:annotation:
        - propeptide_annotation: 
    - core:annotation:
        - signal_peptide_annotation: 
    - core:annotation:
        - transit_peptide_annotation: 
    - core:annotation:
        - cross_link_annotation: CrossLinkAnnotation
    - core:annotation:
        - disulfide_bond_annotation: 
    - core:annotation:
        - glycosylation_annotation: 
    - core:annotation:
        - lipidation_annotation: 
    - core:annotation:
        - modified_residue_annotation: ModifiedResidueAnnotation
    - core:annotation:
        - non_standard_residue_annotation:
    - core:annotation:
        - calcium_binding_annotation:
    - core:annotation:
        - coiled_coil_annotation:
    - core:annotation:
        - compositional_bias_annotation:
    - core:annotation:
        - domain_extent_annotation: DomainExtentAnnotation
    - core:annotation:
        - intramembrane_annotation:
    - core:annotation:
        - motif_annotation:
    - core:annotation:
        - np_binding_annotation: NpBindingAnnotation
    - core:annotation:
        - nucleotide_binding_annotation:
    - core:annotation:
        - repeat_annotation:
    - core:annotation:
        - topological_domain_annotation:
    - core:annotation:
        - transmembrane_annotation:
    - core:annotation:
        - zinc_finger_annotation:
    - core:annotation:
        - erroneous_gene_model_prediction_annotation: ErroneousGeneModelPredictionAnnotation
    - core:annotation:
        - erroneous_initiation_annotation:
    - core:annotation:
        - erroneous_termination_annotation:
    - core:annotation:
        - erroneous_translation_annotation:
    - core:annotation:
        - frameshift_annotation:
    - core:annotation:
        - mass_spectrometry_annotation:
    - core:annotation:
        - mutagenesis_annotation: MutagenesisAnnotation
    - core:annotation:
        - non_adjacent_residues_annotation:
    - core:annotation:
        - non_terminal_residues_annotation:
    - core:annotation:
        - sequence_confilict_annotation:
    - core:annotation:
        - sequence_uncertainty_annotation:
    - core:annotation:
        - similarity_annotation: SimilarityAnnotation
    - core:annotation:
        - subcellular_location_annotation: SubcellularLocationAnnotation
    - core:annotation:
        - subunit_annotation: SubunitAnnotation
    - core:annotation:
        - tissue_specificity_annotation: TissueSpecificityAnnotation
    - core:annotation:
        - toxic_dose_annotation: 
    - core:interaction:
        - self_interaction: SelfInteraction
    - core:interaction:
        - non_self_interaction: 
    - core:attribution:
        - attribution: Attribution
    - core:citation:
        - book_citation: 
    - core:citation:
        - electronic_citation: 
    - core:citation:
        - journal_citation: JournalCitation
    - core:citation:
        - patent_citation: 
    - core:citation:
        - submission_citation: SubmissionCitation
    - core:citation:
        - thesis_citation: 
    - core:citation:
        - observation_citation: 
    - rdfs:seeAlso:
        - see_also: 
            - <http://egp.gs.washington.edu/data/cdc2/>
            - <http://identifiers.org/ncbigene/983>

- StructuredRecommendedName up:P06493\#SIP5A4FD37A407EF4B7:
    - a: core:Structured_Name
    - core:ecName:
        - ec_name: "2.7.11.22"
    - core:fullName:
        - full_name: "Cyclin-dependent kinase 1"
    - core:shortName:
        - short_name: "CDK1"

- StructuredAlternativeName up:P06493\#SIP00349E63D97E99F2:
    - a: core:Structured_Name
    - core:fullName:
        - alternative_name: "p34 protein kinase"

- EncodedBy up:P06493\#gene-MD5066A21D78DD806AEF8C6D2D66E098AF8:
    - a: core:Gene
    - skos:altLabel:
        - alt_label: ["CDC2", "CDC28A", "CDKN1", "P34CDC2"]
    - skos:prefLabel:
        - pref_label: "CDK1"

- Sequence isoform:P06493-1:
    - a: core:Simple_Sequence
    - core:mass:
        - mass: 34095
    - core:md5Checksum:
        - md5_checksum: "c5f024db8fdfc09c76e40635fc0aa6f1"
    - core:modified:
        - isoform_modified: "2011-05-31"
    - core:name:
        - isoform_name: "1"
    - core:version:
        - isoform_version: 3
    - rdf:value:
        - isoform_sequence: "MEDYTKIEKIGEGTYGVVYKGRHKTTGQVVAMKKIRLESEEEGVPSTAIREISLLKELRHPNIVSLQDVLMQDSRLYLIFEFLSMDLKKYLDSIPPGQYMDSSLVKSYLYQILQGIVFCHSRRVLHRDLKPQNLLIDDKGTIKLADFGLARAFGIPIRVYTHEVVTLWYRSPEVLLGSARYSTPVDIWSIGTIFAELATKKPLFHGDSEIDQLFRIFRALGTPNNEVWPEVESLQDYKNTFPKWKPGSLASHVKNLDENGLDLLSKMLIYDPAKRISGKMALNHPYFNDLDNQIKKM"


- ConflictingSequence up:P06493\#SIP57DD48EE8AF6F997:
    - a: core:External_Sequence
    - core:translatedFrom:
        - translated_from: up:P06493\#SIP57DD48EE8AF6F997

- SelfInteraction intact:297353-444308 intact:347640-444308:
    - a: ["core:Interaction", "core:Non_Self_Interaction"]
    - core:experiments:
        - experiments: 3
    - core:participant:
        - participant: ["intact:EBI-297353", "intact:EBI-444308"]
    - core:xeno:
        - xeno: false

- ActiveSiteAnnotation up:P06493\#SIPFC95A5358FA31F92:
    - a: core:Active_Site_Annotation
    - core:range:
        - active_site_annotation_range: Range
    - rdfs:comment:
        - active_site_annotation_comment: "Proton acceptor"

- ActivityRegulationAnnotation up:P06493\#SIPBD7EB44EAA4E6471:
    - a: core:Activity_Regulation_Annotation
    - rdfs:comment:
        - activity_regulation_annotation_comment: ""

- AlternativeSequenceAnnotation annotation:VSP_021375:
    - a: core:Activity_Sequence_Annotation
    - core:substitution:
        - alternative_sequence_annotation_substitution: ""
    - rdfs:comment:
        - alternative_sequence_annotation_comment: "In isoform 2."

- AlternativeSplicingAnnotation up:P06493\#SIPDE7757750C226E88:
    - a: core:Alternative_Splicing_Annotation
    - core:sequence:
        - alternative_splicing_annotation_sequence: Sequence
    - rdfs:comment:
        - alternative_splicing_annotation_comment: ""

- RibosomalFrameshifting up:P06710\#SIPFCC4F752FDF91CCD:
    - a: core:Ribosomal_Frameshifting
    - core:sequence:
        - ribosomal_frameshifting_sequence: Sequence
    - rdfs:comment:
        - ribosomal_frameshifting_comment: "The production of the two protein products from this region is due to programmed ribosomal frameshifting. Frameshifting is about 40% efficient."

- BetaStrandAnnotation up:P06493\#SIP1448A8D6AB07AC9C:
    - a: core:Beta_Strand_Annotation
    - core:range:
        - beta_strand_annotation_range: Range

- BindingSiteAnnotation up:P06493\#SIP1BFF64E6E353741A:
    - a: core:Binding_Site_Annotation
    - core:range:
        - binding_site_annotation_range: Range
    - rdfs:comment:
        - binding_site_annotation_comment: "ATP"

- CataliticActivityAnnotation up:P06493\#SIP11972EF825D39FC9:
    - a: core:Catalytic_Activity_Annotation
    - core:catalyticActivity:
        - catalytic_activity: CatalyticActivity

- ChainAnnotation annotation:PRO_0000085724:
    - a: core:Chain_Annotation
    - core:range:
        - chain_annotation_range: Range
    - rdfs:comment:
        - chain_annotation_comment: "Cyclin-dependent kinase 1"

- InitiatorMethionineAnnotation up:P06710\#SIP1A9E0754F14CA9D9:
    - a: core:Initiator_Methionine_Annotation
    - core:range:
        - initiator_methionine_annotation_range: Range
    - rdfs:comment:
        - initiator_methionine_comment: "Removed"

- CrossLinkAnnotation up:P06493\#SIP5ADD2238697D7EC1:
    - a: core:Cross-link_Annotation
    - core:range:
        - cross_link_annotation_range: Range
    - rdfs:comment:
        - cross_link_annotation_comment: "Glycyl lysine isopeptide (Lys-Gly) (interchain with G-Cter in SUMO2); alternate"

- DomainExtentAnnotation up:P06493\#SIP5D2AA8085B997591:
    - a: core:Domain_Extent_Annotation
    - core:range:
        - domain_extent_annotation_range: Range
    - rdfs:comment:
        - domain_extent_annotation_comment: "Protein kinase"

- ErroneousGeneModelPredictionAnnotation up:P06493\#SIPD13D69F1F4CD4A8C:
    - a: core:Erroneous_Gene_Model_Prediction_Annotation
    - core:confilictingSequence:
        - erroneous_gene_model_prediction_annotation_conflicting_sequence: ConflictingSequence

- ErroneousInitiationAnnotation:
    - a: core:Erroneous_Initiation_Annotation
    - core:confilictingSequence:
        - erroneous_initiation_annotation_conflicting_sequence: ConflictingSequence
    - rdfs:comment:
        - erroneous_initiation_annotation_comment: "Truncated N-terminus."

- FunctionAnnotation up:P06493\#SIP6117914ED102E3B4:
    - a: core:Function_Annotation
    - rdfs:comment:
        - function_annotation_comment: "(Microbial infection) Acts as a receptor for hepatitis C virus (HCV) in hepatocytes and facilitates its cell entry."

- HelixAnnotation up:P06493\#SIP04650F2717A2389F:
    - a: core:Helix_Annotation
    - core:range:
        - helix_annotation_range: Range

- InductionAnnotation up:P06493\#SIP60D3BB366B1B62FD:
    - a: core:Induction_Annotation
    - rdfs:comment:
        - induction_annotation_comment: ""

- ModifiedResidueAnnotation up:P06493\#SIP1D4CE85C9D16B1C6:
    - a: core:Modified_Residue_Annotation
    - core:range:
        - modified_residue_annotation_range: Range
    - rdfs:commnet:
        - modified_residue_annotation_comment: "N-acetylmethionine"

- MutagenesisAnnotation up:P06493\#SIP17E8382E82A8BDCF:
    - a: core:Mutagenesis_Annotation
    - core:range:
        - mutagenesis_annotation_range: Range
    - core:substitution:
        - substitution: "AF" 
    - rdfs:comment:
        - mutagenesis_annotation_comment: "Abnormal cell cycle exhibiting only M-phase without completing either karyokinesis or cytokinesis."

- NpBindingAnnotation up:P06493\#SIPFB79E981CA8AFD16:
    - a: core:NP_Binding_Annotation
    - core:range:
        - np_binding_annotation_range: Range
    - rdfs:comment:
        - np_binding_annotation_comment: "ATP"

- PtmAnnotation up:P06493\#SIP5F0B9E399D9A0ED0:
    - a: core:PTM_Annotation
    - rdfs:comment:
        - ptm_annotation_comment: "Polyubiquitinated upon genotoxic stress."

- SimilarityAnnotation up:P06493\#SIP5D84D02C743C70EC:
    - a: core:Similarity_Annotation
    - rdfs:comment:
        - similarity_annotation_comment: "Belongs to the protein kinase superfamily. CMGC Ser/Thr protein kinase family. CDC2/CDKX subfamily."

- SubcellularLocationAnnotation up:P06493\#SIPBDDAAC56DB8E1DC1:
    - a: core:Subcellular_Location_Annotation
    - core:locatedIn:
        - located_in: LocatedIn
    - rdfs:comment:
        - subcellular_location_annotation_comment: ""

- LocatedIn up:P06493\#SIP299AB8A3C68F818C:
    - a: rdfs:Resource
    - core:cellularComponent:
        - cellular_component: location:48

- SubunitAnnotation up:P06493\#SIP66A719E19256ABED:
    - a: core:Subunit_Annotation
    - rdfs:comment:
        - subunit_annotation_comment: "" 

- TissueSpecificityAnnotation up:P06493\#SIP0AAA804FAD004C35:
    - a: core:Tissue_Specificity_Annotation
    - rdfs:comment:
        - tissue_specificity_annotation_comment: "Isoform 2 is found in breast cancer tissues."

- TurnAnnotation up:P06493\#SIP15A2B5D13031AF2F:
    - a: core:Turn_Annotation
    - core:range:
        - turn_annotation_range: Range

- CatalyticActivity core:P06493\#SIP33DD9A7A16603D04:
    - a: core:Catalytic_Activity
    - core:catalyticReaction:
        - catalytic_reaction: <http://rdf.rhea-db.org/10216>
    - core:enzymeClass:
        - enzyme_class: enzyme:2.7.11.23

- Range range:22571007499383598tt128tt128:
    - a: faldo:Region
    - faldo:begin:
        - begin: Begin
    - faldo:end:
        - end: End

- Begin position:22571007499383598tt285:
    - a: faldo:ExactPosition
    - a: faldo:Position
    - faldo:position:
        - begin_position: 285
    - faldo:reference:
        - begin_reference: isoform:P06493-1

- End position:22571007499383598tt287:
    - a: faldo:ExactPosition
    - a: faldo:Position
    - faldo:position:
        - end_position: 287
    - faldo:reference:
        - end_reference: isoform:P06493-1

- AnnotationStatement:
    - a: rdf:Statement
    - core:attribution:
        - annotation_statement_attribution: Attribution
    - rdf:subject:
        - annotation_subject: up:P06493\#SIP04650F2717A2389F
    - rdf:predicate:
        - annotation_predicate: core:annotation
    - rdf:object:
        - annotation_object: up:P06493

- Attribution:
    - a: rdfs:Resource
    - core:evidence:
        - evidence: obo:ECO_0000244
    - core:manual:
        - manual: true
    - core:source:
        - source: <http://rdf.wwpdb.org/pdb/6GU2>

- ClassifiedWithStatement:
    - a: core:Statement
    - core:attribution: 
        - classified_with_attribution: ClassifiedWithAttribution
    - rdf:subject:
        - classified_with_subject: up:P06493
    - rdf:predicate:
        - classified_with_predicate: core:classifiedWith
    - rdf:object:
        - classified_with_object: obo:GO_009715

- ClassifiedWithAttribution up:P06493\#attribution-9EB47BD232F33339DA82C00F0D8F8AF6:
    - a: rdfs:Resource
    - dct:creator:
        - classified_with_creator: <http://purl.uniprot.org/goa-projects/CAFA>
    - core:evidence:
        - classified_with_evedence: obo:ECO_0000315
    - core:manual:
        - classified_with_attribution_manual: true
    - core:source:
        - classified_with_source: citation:24746669

- JournalCitation citation:12775724 citation:14654843:
    - a: core:Journal_Citation
    - dct:identifier:
        - citation_identifier: "doi:10.1074/jbc.m302191200"
    - core:author:
        - citation_author: ["Camonis J.", "L'Hoste S.", "Offner N.", "Picard A.", "Rosse C."]
    - core:date:
        - citation_data: 2003
    - core:name:
        - citation_name: "J. Biol. Chem."
    - core:pages:
        - citation_pages: "30597-30604"
    - core:title:
        - citation_title: "RLIP, an effector of the Ral GTPases, is a platform for Cdk1 to phosphorylate epsin during the switch off of endocytosis in mitosis."
    - core:volume:
        - citation_volume: "278"
    - skos:exactMatch:
        - citation_exact_match: citation:12775724
    - foaf:primaryTopicOf:
        - citation_primary_topic_of: pubmed:12775724

- SubmissionCitation citation:SIPFBEFD2D28C06C51B citation:SIPBD8C26D9D54E5891:
    - a: core:Submission_Citation
    - core:date:
        - submission_citation_date: 2002-05
    - core:author:
        - submission_citation_author: ["Taro Togo", "Hanako Togo"]
    - core:group:
        - submission_citation_group: "NIEHS SNPs program"
    - core:submittedTo:
        - submitted_to:

