sparql:
  description: SPARQL description
  variables: [mnemonic, created, organism, enzyme, ec_name, full_name, short_name, mass, binding_site_annotation_comment, np_binding_annotation_comment, ptm_annotation_comment, cellular_component, region_annotation_comment, citation_identifier]
