title: TogoID RDF
website: https://togoid.dbcls.jp/
description: TogoID is a service to search and convert links between database identifiers.
tags: [ Others ]
provider: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems, Japan
creators:
  - name: Database Center for Life Science, Joint Support-Center for Data Science Research, Research Organization of Information and Systems, Japan
  - affiliation: --
version: 2022-04-01
issued: 2022-04-01
license: 
  name: NA
  url: NA
  credit: NA
