title: TogoID RDF
website: https://togoid.dbcls.jp/
description: TogoID は、データベースIDの関係をもとに、IDの検索や変換を行うサービスです。
tags: [ Others ]
provider: 情報・システム研究機構、データサイエンス共同利用基盤施設、ライフサイエンス統合データベースセンター
creators:
  - name: 情報・システム研究機構、データサイエンス共同利用基盤施設、ライフサイエンス統合データベースセンター
  - affiliation: --
version: 2022-04-01
issued: 2022-04-01
license:
  name: NA
  url: NA
  credit: NA
