endpoint:
  - https://rdfportal.org/primary/sparql
  - graph:
    - http://mbgd.genome.ad.jp/rdf/resource/default
    - http://mbgd.genome.ad.jp/rdf/resource/gene
    - http://mbgd.genome.ad.jp/rdf/resource/organism
    - http://mbgd.genome.ad.jp/rdf/resource/nucseq
    - http://mbgd.genome.ad.jp/rdf/resource/xref_uniprot
    - http://purl.jp/bio/11/orth
    - http://purl.jp/bio/11/mbgd
