- Cluster cluster:2018-01_default_3927:
  - a: orth:OrthologsCluster
  - dct:identifier:
    - cluster_id: "3927"
  - rdfs:label:
    - cluster_label: "psbA"
  - dct:description:
    - cluster_descr: "Photosystem II reaction center protein"
  - mbgd:score:
    - score: 0
  - mbgd:dist:
    - dist: 0
  - mbgd:funcMbgd:
    - func_mbgd: "6"
  - mbgd:funcCog:
    - func_cog: "4.2"
  - mbgd:funcKegg:
    - func_kegg: "1.2"
  - mbgd:funcTigr:
    - func_tigr: "6.15"
  - foaf:page:
    - cluster_page: <http://mbgd.genome.ad.jp/htbin/hcluster?prog=hcluster&clustid=O3927&tabid=default>
  - void:inDataset:
    - dataset: Dataset
  - orth:hasHomologous+:
    - member_domain: Domain

- Dataset resource:default:
  - a:
    - void:Dataset
    - orth:OrthologyDataset
  - dct:title:
    - dataset_title: "MBGD ortholog groups"
  - dct:description:
    - dataset_descr: "RDF representation of ortholog groups in MBGD."
  - dct:license:
    - license: https://creativecommons.org/licenses/by-sa/4.0/
  - pav:version:
    - dataset_version: "2018-01"
  - dct:created:
    - date_time: 2018-09-20T14:36:24+09:00
  - dct:creator:
    - creator: <http://mbgd.genome.ad.jp>
  - dct:publisher:
    - publisher: <http://www.nibb.ac.jp>
  - dct:source:
    - source: <http://mbgd.genome.ad.jp>
  - pav:derivedFrom:
    - original_dataset: <http://mbgd.genome.ad.jp/dist/mbgd_2018-01/mbgd_2018-01_default.dclst.gz>
  - void:dataDump:
    - dataset_dump: <http://mbgd.genome.ad.jp/rdf/archive/mbgd_2018-01/mbgd_2018-01_default.ttl.gz>
  - foaf:page:
    - dataset_page: <http://mbgd.genome.ad.jp/htbin/cluster_map?tabid=default&show_summary=1>

- Domain <http://mbgd.genome.ad.jp/rdf/resource/domain/2018-01_default/dsl:DACSA_RS08170/0>:
  - a:
    - orth:Subgene
    - mbgd:Domain
    - faldo:Region
  - mbgd:gene:
    - gene: Gene

- Gene <http://mbgd.genome.ad.jp/rdf/resource/gene/dsl:DACSA_RS08170>:
  - a:
    - orth:Gene
    - mbgd:CDS
  - dct:identifier:
    - gene_id: "dsl:DACSA_RS08170"
  - rdfs:label:
    - gene_label: ""
  - dct:description:
    - gene_descr: "photosystem II DII subunit, Q(A) protein"
  - mbgd:aaLength:
    - aa_length: 353
  - foaf:page:
    - gene_page: <http://mbgd.genome.ad.jp/htbin/MBGD_gene_info_frame.pl?name=dsl:DACSA_RS08170>
  - mbgd:domain:
    - domain: <http://mbgd.genome.ad.jp/rdf/resource/domain/2018-01_default/dsl:DACSA_RS08170/0>
  - sio:SIO_000028:
    - gene_part: <http://mbgd.genome.ad.jp/rdf/resource/domain/2018-01_default/dsl:DACSA_RS08170/0>
  - mbgd:protein:
    - protein: ncbiprotein:WP_015229298.1
  - mbgd:uniprot:
    - uniprot: uniprot:K9YTN9
  - sio:SIO_010078+:
    - encoded_protein: ncbiprotein:WP_015229298.1
  - dct:source:
    - gene_refseq: ncbi:refseq
  - mbgd:nucSeq:
    - nucseq: Nucseq # Chromosome 1
  - mbgd:taxon:
    - gene_taxid: taxid:13035 # Dactylococcopsis salina PCC 8305
  - obo:RO_0002162: # in taxon
    - gene_in_taxon: taxid:13035 # Dactylococcopsis salina PCC 8305
  - mbgd:organism:
    - organism: Organism

- Nucseq nucseq:13397:
  - a:
    - mbgd:Chromosome
    - mbgd:Circular
  - rdfs:label:
    - nucseq_label: "Chromosome 1"
  - dct:identifier:
    - nucseq_id: 1
  - mbgd:nucLength:
    - nuc_length: 3781008
  - mbgd:geneCount:
    - gene_count: 3437
  - rdfs:seeAlso:
    - nuc_see_also: <http://www.ncbi.nlm.nih.gov/nuccore/NC_019780.1>

- Organism organism:dsl:
  - a:
    - mbgd:Genome
    - mbgd:CompleteGenome
  - dct:identifier:
    - organism_id: "dsl"
  - rdfs:label:
    - organism_label: "Dactylococcopsis salina PCC 8305"
  - mbgd:abbrev:
    - abbrev: "D.salina"
  - mbgd:family:
    - family: ""
  - mbgd:genus:
    - genus: "Dactylococcopsis"
  - mbgd:species:
    - species: "Dactylococcopsis salina"
  - mbgd:strain:
    - strain: "PCC 8305"
  - mbgd:spid:
    - spid: "gm02198"
  - obo:RO_0002162: # in taxon
    - taxon: taxid:13035 # Dactylococcopsis salina PCC 8305
  - up:organism:
    - organism_uniprot: uptax:13035
  - mbgd:inTaxon:
    - taxid: taxid:1117 # Cyanobacteria
  - mbgd:inSuperkingdom:
    - superkingdom_taxid: taxid:2
  - mbgd:inPhylum:
    - phylum_taxid: taxid:1117 # Cyanobacteria
  - mbgd:inOrder:
    - order_taxid: taxid:1890424 # Synechococcales
  - mbgd:inFamily:
    - family_taxid: taxid:1890426 # Synechococcaceae
  - mbgd:inGenus:
    - genus_taxid: taxid:13034 # Dactylococcopsis
  - mbgd:inSpecies:
    - species_taxid: taxid:292566 # Dactylococcopsis salina
  - foaf:page:
    - organism_page: <http://mbgd.genome.ad.jp/htbin/MBGD_whole_html.pl?spec=dsl>
  - mbgd:assembly:
    - assembly: <http://www.ncbi.nlm.nih.gov/assembly/GCF_000317615.1>
  - dct:issued:
    - organism_issued_date: 2012-12-07+09:00
  - mbgd:assemblyLevel:
    - assembly_level: "Complete Genome"
  - mbgd:assemblyTotalLength:
    - assembly_total_length: 3781008
  - mbgd:assemblyTotalGapLength:
    - assembly_total_gap_length: 0
  - mbgd:assemblyContigCount:
    - assembly_contig_count: 0
  - mbgd:assemblyContigN50:
    - assembly_contig_n50: 0
  - mbgd:assemblyMoleculeCount:
    - assembly_molecule_count: 1
  - mbgd:assemblyTopLevelCount:
    - assembly_top_level_count: 1
  - mbgd:unlocalized_total_length:
    - unlocalized_total_length: 0
  - mbgd:unlocalizedUngappedLength:
    - unlocalized_ungapped_length: 0
