mbgd: <http://purl.jp/bio/11/mbgd#>
orth: <http://purl.org/net/orth#>
obo: <http://purl.obolibrary.org/obo/>
dct: <http://purl.org/dc/terms/>
void: <http://rdfs.org/ns/void#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
foaf: <http://xmlns.com/foaf/0.1/>
pav: <http://purl.org/pav/>
sio: <http://semanticscience.org/resource/>
ncbi: <http://www.ncbi.nlm.nih.gov/>
ncbiprotein: <http://www.ncbi.nlm.nih.gov/protein/>
taxid: <http://identifiers.org/taxonomy/>
up: <http://purl.uniprot.org/core/>
uniprot: <http://purl.uniprot.org/uniprot/>
uptax: <http://purl.uniprot.org/taxonomy/>
resource: <http://mbgd.genome.ad.jp/rdf/resource/>
organism: <http://mbgd.genome.ad.jp/rdf/resource/organism/>
nucseq: <http://mbgd.genome.ad.jp/rdf/resource/nucseq/>
cluster: <http://mbgd.genome.ad.jp/rdf/resource/cluster/>
domain: <http://mbgd.genome.ad.jp/rdf/resource/domain/2018-01_default/tax1129:1182/>
faldo: <http://biohackathon.org/resource/faldo#>
