dataset:
  name: Dataset of NBRC bioresource
  description: Dataset of NBRC bioresource is a dataset for microbes which are maintained, managed and provided from NBRC (NITE Biological Resource Center).
