dataset:
  name: HPO
  description: The Human Phenotype Ontology (HPO) provides a standardized vocabulary of phenotype specialized in human disease. The medical literatures, Orphanet, DECIPHER, and OMIM are used for developing the HPO.
