- Class obo:HP_0001903:
  - a: owl:Class
  - obo:IAO_0000115+: # definition
    - definition: "A reduction in erythrocytes volume or hemoglobin concentration."
  - oboinowl:hasAlternativeId+:
    - alternativeid: "HP:0003136"
  - oboinowl:hasDbXref+:
    - snomedct: "SNOMEDCT_US:271737000"
  - oboinowl:hasExactSynonym+:
    - exactsynonym: "Low number of red blood cells or hemoglobin"
  - oboinowl:hasOBONamespace+:
    - namespace: "human_phenotype"
  - oboinowl:hasRelatedSynonym+:
    - relatedsynonym: "Decreased hemoglobin"
  - oboinowl:id:
    - id: "HP:0001903"
  - rdfs:comment+:
    - comment: "Anemia is not a specific entity but can result from many underlying pathologic processes. The three main causes of anemia are blood loss, decreased or faulty red blood cell production, and increased destruction of red blood cells. Various classifications are in clinical use including a classification according to the mean corpuscular volume (MCV) of the erythrocytes: microcytic, macrocytic, or normocytic. Anemias can also be classified according to variations in cell size and shape, as reflected by the red-cell distribution width (RDW). Additionally, anemias can be classified into those of inadequate production and hemolytic anemias."
  - rdfs:label+:
    - class_label: "Anemia"
  - rdfs:seeAlso+:
    - hpo: hp:0001903
  - rdfs:subClassOf+:
    - superclass: obo:HP_0001877 # Abnormal erythrocyte morphology

