title: BRENDA RDF
website: https://brenda-enzymes.org/
description: BRENDA is the comprehensive enzyme information system with data on enzyme function, structure, and kinetics.
tags: [ Enzyme, Biocatalysis, Bioresource ]
provider: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
creators:
  - name: Julia Koblitz
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
  - name: Lisa Jeske
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
  - name: Mathias Krull
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
  - name: Antje Jäde
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
  - name: Julia Hauenstein
    affiliation: Leibniz Institute DSMZ-German Collection of Microorganisms and Cell Cultures
version: 2025-09
issued: 2025-09-16
licenses:
  - Creative Commons Attribution 4.0 International (CC BY 4.0)
