rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dc: <http://purl.org/dc/elements/1.1/>
dct: <http://purl.org/dc/terms/>
skos: <http://www.w3.org/2004/02/skos/core#>
obo: <http://purl.obolibrary.org/obo/>
d3o: <https://purl.dsmz.de/schema/>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
enzyme: <https://purl.dsmz.de/brenda/enzyme/>
tissue: <https://purl.dsmz.de/brenda/tissue/>
activator: <https://purl.dsmz.de/brenda/activator/>
cofactor: <https://purl.dsmz.de/brenda/cofactor/>
reaction: <https://purl.dsmz.de/brenda/reaction/>
inhibitor: <https://purl.dsmz.de/brenda/inhibitor/>
localization: <https://purl.dsmz.de/brenda/localization/>
compound: <https://purl.dsmz.de/brenda/compound/>
organism: <https://purl.dsmz.de/brenda/organism/>
ec: <https://purl.dsmz.de/brenda/ec/>
product: <https://purl.dsmz.de/brenda/product/>
substrate: <https://purl.dsmz.de/brenda/substrate/>
pathway: <https://purl.dsmz.de/brenda/pathway/>
reference: <https://purl.dsmz.de/brenda/reference/>
structure: <https://purl.dsmz.de/brenda/structure/>